Repository sakaiproject/sakai, pull requests merged in 2018-11, with the labels that each got.

#6215 SAK-40886: Samigo > retract date check can be bypassed
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java
Labels: use rebase+merge

#6214 SAK-40885: Forums > mobile view post UI's action buttons squished
  msgcntr/messageforums-app/src/webapp/css/msgcntr.css
Labels: low risk, use rebase+merge

#6213 SAK-40884: Forums > grading modal doesn't remember previously entered user data
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
Labels: use rebase+merge

#6211 SAK-40883: Wiki > fix link macro for relative links
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/SakaiLinkMacro.java
Labels: use rebase+merge

#6210 SAK-40882: PostEm > incorrect error message when uploading wrong file type
  postem/postem-app/src/bundle/org/sakaiproject/tool/postem/bundle/Messages.properties
  postem/postem-app/src/java/org/sakaiproject/tool/postem/PostemTool.java
Labels: use rebase+merge

#6209 SAK-40879: CKEditor > allow tools to override default toolbar config
  library/src/webapp-filtered/editor/ckeditor.launch.js
Labels: use rebase+merge

#6222 SAK-40889 Ignore a null event
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
Labels: low risk

#6223 SAK-40864: Regression: Questions tab and calculated questions: It shows wrong answers despite the answers are right
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
Labels: low risk

#6182 SAK-40844 Lock groups for deletion when assigned to assessments
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  edu-services/sections-service/sections-api/src/java/org/sakaiproject/section/api/coursemanagement/CourseSection.java
  edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseSectionImpl.java
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityGroup.java
  kernel/api/src/main/java/org/sakaiproject/site/api/Group.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemoveAssessmentListener.java
  sections/sections-app-util/src/java/org/sakaiproject/tool/section/decorator/SectionDecorator.java
  sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/LocalSectionModel.java
  sections/sections-app/src/webapp/overview.jsp
  site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupDelProducer.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupListProducer.java
  site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupList.html
Labels: BLOCKER

#6207 SAK-40877: Kernel > inappropriate sort option causes kernel code to create broken SQL statement
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
Labels: use rebase+merge

#6208 SAK-40878: Portal > improve instructions and contrast of Organize Favourites UI (a11y)
  library/src/morpheus-master/sass/_defaults.scss
  library/src/morpheus-master/sass/modules/more-sites/_base.scss
  portal/portal-impl/impl/src/bundle/sitenav.properties
Labels: accessibility, use rebase+merge

#6252 SAK-40914 allow samigo via lessons or url
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
Labels: BLOCKER

#6242 SAK-40921 - Fix content Item / deep link flow
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LineItemUtil.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  basiclti/basiclti-oidc/maven.xml
  basiclti/basiclti-oidc/pom.xml
  basiclti/basiclti-oidc/src/bundle/oidc.properties
  basiclti/basiclti-oidc/src/java/org/sakaiproject/lti13/OIDCServlet.java
  basiclti/basiclti-oidc/src/webapp/WEB-INF/applicationContext.xml
  basiclti/basiclti-oidc/src/webapp/WEB-INF/web.xml
  basiclti/basiclti-oidc/src/webapp/whatisthis.htm
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/pom.xml
  basiclti/tsugi-util/src/java/org/tsugi/ags2/objects/LineItem.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/DeepLinkResponse.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13ConstantsUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13JwtUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13KeySetUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/DeepLink.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
Labels: work in progress

#6260 SAK-40951 - Document lti13.deployment_id property
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-docs/resources/docs/BLTI_TestPlan.xls
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: low risk

#6282 SAK-40702 wicket tools don't work if site id has a blank space
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
Labels: BLOCKER

#6319 SAK-40357 - Syllabus Bulk Add not working
  syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java
  syllabus/syllabus-hbm/src/java/org/sakaiproject/component/app/syllabus/SyllabusItemImpl.hbm.xml
  syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusManagerImpl.java
  syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
Labels: BLOCKER

#6317 SAK-40770 Samigo: Score value not updated (HARD)
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScorePagerListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetQuestionScoreListener.java
Labels: BLOCKER

#6308 SAK-41011 - Samigo file upload error in Windows systems.
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
Labels: BLOCKER
