Repository sakaiproject/sakai, pull requests merged in 2018-12, with the labels that each got.

#6332 SAK-41027: GBNG > incorrect default tooltip when toggling mutually exclusive drop/keep settings
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Labels: low risk, use rebase+merge

#6313 SAK-40998 Hide forums/topics student has no permissions in
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateOrganize.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyAllAuthoredMsg.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyFullTextForOne.jsp
Labels: BLOCKER

#6337 SAK-41030 - Resolve a startup issue
  samigo/samigo-app/src/webapp/WEB-INF/applicationContext.xml
Labels: BLOCKER, priority

#6338 SAK-38308 Samigo Hotspot: Provide alt to images
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemMetaDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/author/preview_item/ImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/author/search_preview_item/ImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/item/displayImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/print/preview_item/ImageMapQuestion.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemHashUtil.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/facade/ItemHashUtilTest.java
Labels: accessibility

#6336 SAK-41034 make findSubmissionForUser method Transactional to avoid crash
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
Labels: use squash+merge

#6356 SAK-41054: Drop Box > fix inconsistencies in UI messaging when referring to the tool
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/type/types.properties
  content/content-bundles/resources/content.properties
  content/content-bundles/resources/types.properties
  content/content-tool/tool/src/bundle/dropbox.properties
Labels: low risk, use rebase+merge

#6331 SAK-41026: Site Info > Improve performance when displaying roster lists
  edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseManagementService.java
  edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/hibernate/org/sakaiproject/coursemanagement/impl/SectionCmImpl.hbm.xml
  edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceFederatedImpl.java
  edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceHibernateImpl.java
  edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceSampleChainImpl.java
  kernel/api/src/main/java/org/sakaiproject/authz/api/GroupProvider.java
  providers/allhands/src/java/org/sakaiproject/provider/authzGroup/AllHandsGroupProvider.java
  providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProvider.java
  providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseOfferingRoleResolver.java
  providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseSetRoleResolver.java
  providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/RoleResolver.java
  providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/SectionRoleResolver.java
  providers/sample/src/java/org/sakaiproject/provider/authzGroup/SampleGroupProvider.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge

#6377 SAK-40534. MathJax learn more link needs to be updated
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_eu.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ja.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MathJaxEnabler.java
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm
Labels: I18N, L10N

#6195 SAK-32630 Forum/Topic View Full Description does not update when toggled
  library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es_ES_Pearson.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_fa_IR.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_fr_FR.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_fr_FR_Pearson.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_hi_IN.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ja.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ja_JP_Pearson.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_mn.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_nl_NL_Pearson.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_pt_BR.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_sv.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_tr_TR.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_zh_CN.properties
  msgcntr/messageforums-app/src/webapp/js/forum.js
  msgcntr/messageforums-app/src/webapp/jsp/dfCompose.jsp
  msgcntr/messageforums-app/src/webapp/jsp/dfMessageReply.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumSettings.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/topic/dfTopicSettings.jsp
Labels: accessibility, work in progress

#6340 SAK-41036 - Add a tooltip after creating a new gradebook item.
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: accessibility

#6381 SAK-40978 - Small fix
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/GradebookIfc.java
Labels: low risk

#6357 SAK-41055: Drop Box > IndexOutOfBoundsException when uploading to top-level folder with email notification
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/SiteEmailNotificationDragAndDrop.java
Labels: use rebase+merge

#6393 SAK-41083: Site Info > duplicate course site email notification missing course term variable
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: low risk, use rebase+merge

#6401 SAK-41093: Samigo > format dates consistently in submission notification email
  samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java
Labels: use rebase+merge

#6400 SAK-41092: Drop Box > add more highlight options
  content/content-bundles/resources/content.properties
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Labels: low risk, use rebase+merge

#6402 SAK-41095: Lessons > reorder doesn't work in IE11
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ReorderProducer.java
  lessonbuilder/tool/src/webapp/css/Simplepagetool.css
  lessonbuilder/tool/src/webapp/js/reorder.js
  lessonbuilder/tool/src/webapp/templates/Reorder.html
Labels: use rebase+merge

#6392 SAK-41082: Forums > previous & next topic buttons can overlap breadcrumbs
  library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
Labels: low risk

#6407 SAK-41101 Rubrics: Remove unnecessary console.log references
  rubrics/tool/src/main/frontend/imports/sakai-rubric-criterion-grading.html
  rubrics/tool/src/main/frontend/imports/sakai-rubric-criterion-student.html
  rubrics/tool/src/main/frontend/imports/sakai-rubric-criterion.html
  rubrics/tool/src/main/frontend/imports/sakai-rubric-readonly.html
  rubrics/tool/src/main/frontend/imports/sakai-rubric.html
  rubrics/tool/src/main/frontend/imports/sakai-rubrics-manager-src.html
Labels: low risk

#6396 SAK-41088: Site Info > Manage Tools > Confirmation page no longer indicates renamed tools
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-addRemoveFeatureConfirm.vm
Labels: low risk

#6420 SAK-40946 Also ignore the maven-wrapper.jar
  .gitignore
Labels: low risk

#6405 SAK-41097: forums > topic settings > improve display of warning messages
  library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
Labels: low risk, use rebase+merge

#6430 SAK-41058 > bug fix for Double comparison
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: low risk
