Repository sakaiproject/sakai, pull requests merged in 2018-07, with the labels that each got.

#5730 SAK-40169 - “Local Rubrics” should be renamed to “Site Rubrics”
  rubrics/impl/src/main/bundle/rubricsMessages.properties
  rubrics/impl/src/main/bundle/rubricsMessages_ca.properties
  rubrics/impl/src/main/bundle/rubricsMessages_es.properties
  rubrics/impl/src/main/bundle/rubricsMessages_es_ES.properties
  rubrics/tool/src/main/frontend/imports/sakai-rubric-readonly.html
  rubrics/tool/src/main/frontend/imports/sakai-rubrics-manager-src.html
  rubrics/tool/src/main/frontend/imports/sakai-rubrics-shared-list.html
Labels: work in progress

#5751 SAK-40254: Portal > Improve messaging and styling of the 'Join Page'
  library/src/morpheus-master/sass/modules/joinpage/_base.scss
  library/src/morpheus-master/sass/tool.scss
  library/src/webapp/skin/tool_base.css
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/join.vm
Labels: low risk, use rebase+merge

#5724 SAK-40212: web content > explain why pop-up behaviour changes for https vs http links
  web/web-portlet/src/bundle/iframe.properties
  web/web-portlet/src/bundle/vm/edit.vm
Labels: low risk

#5766 SAK-40280 Sakai 12.x spanish translation update for 12.3 release
  admin-tools/src/bundle/users_es.properties
  assignment/bundles/resources/assignment_es.properties
  calendar/calendar-bundles/resources/calendar_es.properties
  content-review/impl/turnitin/src/main/resources/turnitin_es.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
  lessonbuilder/tool/src/resources/messages_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  reset-pass/account-validator-tool/src/bundle/org/sakaiproject/accountvalidator/bundle/messages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  signup/tool/src/bundle/messages_es.properties
  site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
Labels: L10N, translation

#5257 SAK-33857 Remove useless gradebook code
  edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
  edu-services/gradebook-service/api/src/java/org/sakaiproject/tool/gradebook/facades/ContextManagement.java
  edu-services/gradebook-service/api/src/java/org/sakaiproject/tool/gradebook/facades/EventTrackingService.java
  edu-services/gradebook-service/api/src/java/org/sakaiproject/tool/gradebook/facades/UserDirectoryService.java
  edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradeMapping.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/VersionedExternalizable.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/BaseEntityProducer.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/ContextManagementSakai2Impl.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/EventTrackingServiceSakai2Impl.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/GradebookConditionsProvider.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/GradebookConfigurationSakai.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/GradebookEntityProducer.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/UserDirectoryServiceSakai2Impl.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/XmlImportable.java
  edu-services/gradebook-service/sakai-pack/src/webapp/WEB-INF/components.xml
  gradebook/app/sakai-tool/src/webapp/WEB-INF/spring-facades.xml
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentDetailsBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/CourseGradeDetailsBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/EnrollmentTableBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/EntryServlet.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookDependentBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/InitializableBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/InstructorViewBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/RemoveAssignmentBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/RoleFilter.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/RosterBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/SpreadsheetUploadBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/StudentViewBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/TestGradebookTool.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/ViewByStudentBean.java
  gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/test/LoginAsBean.java
  gradebook/app/ui/src/webapp/WEB-INF/faces-beans.xml
  gradebook/app/ui/src/webapp/WEB-INF/faces-test.xml
  gradebook/app/ui/src/webapp/WEB-INF/spring-beans.xml
Labels: use rebase+merge

#5783 SAK-39953: Resources > add README documentation for copyright options
  content/README.md
  content/content-copyright/README.md
Labels: low risk

#5826 SAK-40366: Roster > improve format of group membership in export file
  roster2/src/i18n/org/sakaiproject/roster/i18n/ui.properties
  roster2/src/java/org/sakaiproject/roster/tool/entityprovider/RosterPOIEntityProvider.java
Labels: use rebase+merge

#5823 SAK-40363: Assignments > Upload All > silent failure if grades file is wrong type
  assignment/bundles/resources/assignment.properties
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: use rebase+merge

#5822 SAK-40362: Assignments > instructor feedback not visible in resubmission scenario
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Labels: use rebase+merge

#5821 SAK-40361: Assignments > visually distinguish sections of the students view of returned submission
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_feedback_attachments.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
  library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
Labels: low risk, use rebase+merge

#5811 SAK-40345: Announcements > sort order problems
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
Labels: use rebase+merge

#5810 SAK-28966: Announcements > Reorder option not persistent on update
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
Labels: use rebase+merge

#5809 SAK-39992: Announcements > new config to make email notification 'To' address match 'From' address if 'From' is replyable
  announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/SiteEmailNotificationAnnc.java
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: use rebase+merge

#5842 SAK-40248: fix styles
  library/src/morpheus-master/sass/modules/tool/_table.scss
Labels: use rebase+merge
