Repository sakaiproject/sakai, pull requests merged in 2018-09, with the labels that each got.

#5970 SAK-40576 jldap-mock: lang3 builder
  providers/jldap-mock/pom.xml
  providers/jldap-mock/src/java/edu/amc/sakai/user/UserEditStub.java
Labels: low risk

#5996 SAK-40596 Delivery is broken due to some directives
  samigo/samigo-app/src/webapp/jsf/delivery/assessmentHasBeenSubmittedContent.jsp
Labels: BLOCKER, bug, priority

#6001 SAK-40631 javax.mail 1.6.2
  master/pom.xml
Labels: merged 11x

#5999 SAK-40603 limit cells that get redrawn after each score item save.
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: use rebase+merge

#6035 SAK-40682: EntityBroker > fix wrong return type for membership
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java
Labels: low risk, use rebase+merge

#6036 SAK-40542: EntityBroker > add first and last name to membership provider
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityMember.java
Labels: low risk, use rebase+merge

#6056 SAK-40696 - Fail and Pass are hardcoded when grading an assignment
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
Labels: L10N
