Repository sakaiproject/sakai, pull requests merged in 2018-04, with the labels that each got.

#5453 SAK-34061: GBNG > Import > Omissions panels > missing students list should display student names from import file as well as IDs
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UserIdentificationReport.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
  gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
Labels: low risk

#5457 SAM-3392: ArrayIndexOutOfBoundsException protection in HistogramListener.doAnswerStatistics()
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
Labels: low risk

#5462 SAK-34067: Plus sign appears in assignment instructions on grading page
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
Labels: low risk

#5477 SAK-34082: Assignments > update wording and styling of peer review information message
  assignment/bundles/resources/assignment.properties
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Labels: low risk

#5478 SAK-34083: Assignments > invalid values are persisted for the default no submission grade
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: low risk

#5468 SAK-34076: Site Info > improve the 'Unjoin' joinable site process
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: low risk

#5447 SAM-1384: remove restriction that 'View' dropdown should only be shown if quiz allows multiple submissions
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
Labels: use rebase+merge

#5489 SAK-34090: Worksite Setup > New > 'Build your own site' radio button conditional regression
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-type.vm
Labels: use rebase+merge

#5494 KNL-1593 - Lessonbuilder event changes broke LRS
  kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseLearningResourceStoreService.java
Labels: low risk

#5495 SAK-34096: Preferences > missing active primary button for 'Sites' and 'Editor' tabs
  user/user-tool-prefs/tool/src/webapp/css/prefs.css
  user/user-tool-prefs/tool/src/webapp/prefs/editor.jsp
  user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp
Labels: low risk, use rebase+merge

#5505 SAK-29817 - Duplicated entry for uploadall.alert.wrongZipFormat
  assignment/bundles/resources/assignment.properties
Labels: low risk

#5499 SAK-34098: Portal > reinstate the quick tool dropdown for the 'Home' site
  library/src/morpheus-master/sass/modules/navigation/_base.scss
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm
Labels: low risk, use rebase+merge

#5497 SAM-3397: add space to Matrix of Choices forced ranking setting title
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
Labels: low risk, use rebase+merge

#5493 SAK-34095: Improve the styling of the fieldset legend
  library/src/morpheus-master/sass/base/_defaults.scss
Labels: low risk, use rebase+merge

#5487 SAK-34088: Duplicate draft forums/topics should duplicate as draft
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
Labels: low risk, use rebase+merge

#5508 SAK-37842: Add the Apply This Score option to the average score quiz submission page
  samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
Labels: use rebase+merge

#5485 SAK-21242 - Configure number of hours to show in Calendar's weekly an…
  calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewDay.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewWeek.vm
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: work in progress

#5539 SAK-39923 - Update CircleCI, delete all of Sakai Project Cache
  .circleci/config.yml
Labels: low risk

#5542 SAK-39927 - Support for older version sitestats properties
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/SiteStatsPersistenceConfig.java
Labels: work in progress

#5541 SAK-39926 - NPE in Sitestats if lessons is not added to site
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
Labels: low risk

#5536 SAK-38440: edu-services > implement site property to override 'gradebook.externalAssessments.updateSameScore' sakai.property
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
  edu-services/gradebook-service/sakai-pack/src/webapp/WEB-INF/components.xml
Labels: use rebase+merge
