Repository sakaiproject/sakai, pull requests merged in 2018-05, with the labels that each got.

#5543 SAK-39928: samigo > minimize redundant UPDATE queries on SAM_ITEMGRADING_T
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
Labels: use rebase+merge

#5547 SAK-39936 - Improve "includeWebjarLibraryWithVersion"
  assignment/tool/src/webapp/chef_header.vm
  library/src/webapp/js/headscripts.js
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
  site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html
Labels: low risk

#5556 SAK-39955 - Job scheduler migration job is not available in Sakai 12
  jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/DelayedInvocationDAO.java
  jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SchedulerMigrationJob.java
  jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
  jobscheduler/scheduler-events-model/src/java/org/sakaiproject/scheduler/events/hibernate/DelayedInvocation.java
Labels: work in progress

#5567 SAK-39965 - lang-datepicker.js: Cannot get property 'locale' of 'undefined'
  library/src/webapp/js/lang-datepicker/lang-datepicker.js
Labels: low risk

#5572 SAK-39971 - Certification tool: Provide an icon for default
  library/src/morpheus-master/sass/base/_icons.scss
Labels: low risk

#5574 SAK-39973 - Fix pack-bin zip files that don't open in Windows
  pack/pack-bin/build.xml
Labels: low risk

#5564 SAK-38334 use Submit buttons instead of onchange
  chat/chat-tool/tool/src/bundle/chat.properties
  chat/chat-tool/tool/src/webapp/jsp/room.jsp
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
Labels: accessibility

#5529 SAK-38386 modify custom IconWithClueTip to use qtip instead of old cluetip and add img alt tag
  commons/tool/src/webapp/WEB-INF/bootstrap.jsp
  library/pom.xml
  library/src/webapp/js/jquery/qtip/imagesloaded.pkg.min.js
  library/src/webapp/js/jquery/qtip/jquery.qtip-latest.min.css
  library/src/webapp/js/jquery/qtip/jquery.qtip-latest.min.js
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfFlatView.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThread.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
  profile2/bundle/src/resources/ProfileApplication.properties
  profile2/tool/src/java/org/sakaiproject/profile2/tool/components/IconWithClueTip.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/components/IconWithClueTip.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/components/OnlinePresenceIndicator.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/BasePage.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPictures.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MySearch.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewProfile.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/CreateWorksitePanel.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoEdit.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingEdit.html
  profile2/tool/src/webapp/css/profile2.css
  profile2/tool/src/webapp/javascript/profile2.js
  samigo/samigo-app/src/webapp/include/header.inc
Labels: accessibility

#5591 SAK-38337 explain role switch to assisted users
  library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/roleSwitch-snippet.vm
Labels: accessibility

#5598 SAK-39996 - Update tomcat 12/13 from 8.5.28 to 8.5.31
  master/pom.xml
Labels: low risk

#5544 SAK-39930: BasicLTI > extend 'Allow'/'Do not allow' configuration options to the custom tool icon setting
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
  basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
  basiclti/basiclti-impl/src/bundle/ltiservice.properties
  basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
  basiclti/web-ifp/src/bundle/iframe.properties
  basiclti/web-ifp/src/bundle/vm/edit.vm
  basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm
Labels: use rebase+merge

#5594 SAK-38346 hide the pdf icon from screenreaders
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Labels: accessibility

#5593 SAK-38388 provide a label on the remove button
  signup/tool/src/webapp/signup/signupMeetings.jsp
Labels: accessibility

#5595 SAK-39994: assignments > assign grade to participants without a grade, decimals multiplied by 100 (display issue)
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: use rebase+merge

#5618 SAK-38381 use aria-current to indicate what page is active
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
Labels: accessibility

#5535 SAK-38439: Samigo > improve performance when copying questions from pool to quiz
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/ImportQuestionsToAuthoring.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
Labels: use rebase+merge

#5545 SAK-39934 - Improvements wrt unpublishing sites with the Course Site Removal job
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSiteRemovalServiceImpl.java
  edu-services/cm-service/cm-impl/hibernate-pack/src/webapp/WEB-INF/components.xml
  jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSiteRemovalJob.java
  kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSql.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSqlDefault.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/site/impl/SiteServiceTest.java
  kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/BaseDbFlatStorage.java
Labels: use rebase+merge

#5552 SAK-37978 - Wrong style adding new forum on lesson builder
  lessonbuilder/tool/src/webapp/css/Simplepagetool.css
Labels: for discussion
