Repository sakaiproject/sakai, pull requests merged in 2018-03, with the labels that each got.

#5366 SAM-2435 - Auto-submit always sends last score which can allow zeros to override scores on multiple submissions in various cases
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/TimedAssessmentRunnable.java
  samigo/samigo-pack/src/webapp/WEB-INF/components.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/util/autosubmit/AutoSubmitQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/util/autosubmit/AutoSubmitQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/PersistenceService.java
Labels: work in progress

#5269 Fix SAK-33451 and SAK-33371: Save the owner of an external calendar and his time zone.
  calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarImporterService.java
  calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/ExternalCalendarSubscriptionService.java
  calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/ExternalSubscriptionDetails.java
  calendar/calendar-api/api/src/java/org/sakaiproject/calendar/cover/CalendarImporterService.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionService.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalSubscriptionDetails.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/CSVReader.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/MeetingMakerReader.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/OutlookReader.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/Reader.java
  calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionTest.java
  calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/SubscriptionCacheTest.java
  calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
Labels: for discussion

#5358 LSNBLDR-941 Events dissapears in calendars when adding two or more ca…
  lessonbuilder/tool/src/webapp/js/lessons-calendar.js
Labels: low risk

#5414 SAM-3113: when a late test is auto-submitted, Scores screen only shows LATE flag
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
Labels: work in progress

#5034 SAK-33534 Missing key inserting a non-number value in Categories & We…
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_ca.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_de.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_fa_IR.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_fr_CA.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_ja.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_zh_CN.properties
Labels: work in progress

#5435 SAK-34036 - Update CKEditor to 4.9.1 and update all plugins
  library/pom.xml
  library/src/morpheus-master/sass/modules/editor/_base.scss
  library/src/webapp/editor/elfinder/sakai/elfinder.html
  master/pom.xml
  portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
  webjars/ckeditor-autosave/pom.xml
  webjars/ckeditor-image2/pom.xml
  webjars/ckeditor-wordcount/pom.xml
Labels: work in progress
