Repository sakaiproject/sakai, pull requests merged in 2018-06, with the labels that each got.

#5650 SAK-40061: Appears "Pass" or "Fail" when override a student's grade instead of the translation to different languages
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Labels: low risk

#5666 SAK-40089: Group Grade text is hardcoded
  assignment/bundles/resources/assignment.properties
  assignment/bundles/resources/assignment_es.properties
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
Labels: i18n

#5675 SAK-40104 - Worksite setup: Responsive sites table
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
Labels: low risk

#5694 SAK-40030 - Support iframe return
  basiclti/basiclti-docs/resources/docs/ContentItem_TestPlan.xls
  library/src/webapp/editor/ckextraplugins/contentitem/plugin.js
Labels: low risk

#5691 SAK-40135 use a proper label for Change Profile Picture
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/loginImage-snippet.vm
Labels: accessibility

#5698 SAK-40139 cleanup accessibility issues in profile and pic changer
  library/src/morpheus-master/sass/modules/navigation/_base.scss
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/BasePage.html
  profile2/tool/src/webapp/css/profile2.css
Labels: accessibility

#5703 SAK-38408 hide the empty links so screenreader doesnt announce
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
Labels: accessibility

#5702 SAK-38320 add scope to matrix table
  library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/webapp/js/samigo-global.js
  samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/preview_item/MatrixChoicesSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/author/search_preview_item/MatrixChoicesSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/reviewAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-app/src/webapp/jsf/print/preview_item/MatrixChoicesSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
Labels: accessibility

#5716 SAK-33837 - Update the urls for ckeditor a11ychecker, affects ability…
  master/pom.xml
  webjars/ckeditor-a11ychecker/pom.xml
  webjars/ckeditor-balloonpanel/pom.xml
  webjars/pom.xml
Labels: low risk

#5731 SAK-40222: resources > add accompanying text to the 'Paste' icons
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
  library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
Labels: low risk

#5723 SAK-40211: resources > improve accuracy of new/updated resources email notification
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/SiteEmailNotificationDragAndDrop.java
Labels: low risk

#5734 SAK-40230: Email Archive > clarify email alias can be one or many
  mailarchive/mailarchive-tool/tool/src/bundle/email.properties
Labels: low risk, use rebase+merge

#5500 SAK-34097: Style the disabled checkboxes and radios (and their labels) to distinguish them from enabled ones
  library/src/morpheus-master/sass/_defaults.scss
  library/src/morpheus-master/sass/base/_defaults.scss
Labels: low risk, use rebase+merge

#5738 SAK-40239: Velocity > #toolbar macro needs updating for active tab styling
  velocity/tool/src/templates/VM_chef_library.vm
Labels: low risk

#5743 SAK-40246: Membership > Joinable Sites > improve some user facing messages
  site-manage/site-manage-tool/tool/src/bundle/membership.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
Labels: low risk

#5749 SAK-40253: Samigo > Improve the warning message for deleting a Question Pool
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_en_GB.properties
  samigo/samigo-app/src/webapp/jsf/questionpool/removePool.jsp
Labels: low risk, use rebase+merge

#5748 SAK-40252: Site Info > Improve location and language of 'Unjoin' button
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Labels: low risk, use rebase+merge
