Repository sakaiproject/sakai, pull requests merged in 2018-08, with the labels that each got.

#5879 SAK-32360 11.x merge fixes
  basiclti/basiclti-tool/src/webapp/vm/lti_content_delete.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
Labels: please merge to sakai-11

#5887 SAK-40474 Add Unit Tests and Utility Code for LTI 1.3
  basiclti/tsugi-util/pom.xml
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13ConstantsUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13JacksonUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13JwtUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/BaseJWT.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/BasicOutcome.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/Context.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/Endpoint.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchLIS.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchPresentation.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/ResourceLink.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/ToolPlatform.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13JJWTTest.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13ObjectTest.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13PKITest.java
Labels: low risk

#5880 SAK-40459: Library > JavaScript spin+clone tweak to retain visible checked state of checkboxes and radios
  library/src/webapp/js/spinner.js
Labels: low risk

#5912 SAK-40497 - Add unit tests for keysets an the Nimbus library
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13NimbusTest.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13UtilTest.java
Labels: work in progress

#5939 SAK-28174: Assignments > remove 'Close and exit' buttons
  assignment/bundles/resources/assignment.properties
  assignment/bundles/resources/assignment_ca.properties
  assignment/bundles/resources/assignment_es.properties
  assignment/bundles/resources/assignment_eu.properties
  assignment/bundles/resources/assignment_fa_IR.properties
  assignment/bundles/resources/assignment_fr_FR.properties
  assignment/bundles/resources/assignment_hi_IN.properties
  assignment/bundles/resources/assignment_ja.properties
  assignment/bundles/resources/assignment_pt_BR.properties
  assignment/bundles/resources/assignment_tr_TR.properties
  assignment/bundles/resources/assignment_zh_CN.properties
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
Labels: low risk
