Repository sakaiproject/sakai, pull requests merged in 2018-10, with the labels that each got.

#6074 SAK-40156 Rubrics: rename 'Fine tune points' option
  assignment/bundles/resources/assignment.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
Labels: L10N, low risk

#6077 SAK-40310 - Rubrics: 'Hide Rubric preview from student' rephrasing
  assignment/bundles/resources/assignment.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
Labels: L10N, low risk

#6072 SAK-40313 - Rubrics: Student comment icon displays incorrect tooltip
  rubrics/impl/src/main/bundle/rubricsMessages.properties
  rubrics/tool/src/main/frontend/imports/sakai-rubric-student-comment.html
Labels: L10N, low risk

#6073 SAK-40707 - Fix merge conflicts in properties files
  admin-su/src/bundle/tool-tool-su_pt_BR.properties
  portal/portal-impl/impl/src/bundle/sitenav_pt_BR.properties
Labels: I18N, L10N, low risk

#6076 SAK-40311 - Rubrics: Comment pop-up should contain the criterion name
  rubrics/impl/src/main/bundle/rubricsMessages.properties
  rubrics/tool/src/main/frontend/imports/sakai-rubric-grading-comment.html
  rubrics/tool/src/main/frontend/imports/sakai-rubric-student-comment.html
  rubrics/tool/src/main/frontend/imports/sakai-rubrics-language.html
  rubrics/tool/src/main/frontend/imports/sakai-rubrics-styles.html
  rubrics/tool/src/main/frontend/sass/sakai-rubrics.scss
Labels: BLOCKER, I18N, L10N

#6117 SAK-40749: Kernel > realms refresh queue uses a HashMap
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
Labels: use rebase+merge

#6114 SAK-34177: Samigo > fix poor placement of add questions drop-downs on quiz edit screen
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_en_GB.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
Labels: use rebase+merge

#6116 SAK-40748: Help > fix bug with docId
  help/help-tool/src/java/org/sakaiproject/tool/help/HelpJsfTool.java
Labels: use rebase+merge

#6113 SAK-40747: Samigo > can take quiz via /direct URL without required permissions
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AuthzQueriesFacadeAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/authz/integrated/AuthzQueriesFacade.java
Labels: use rebase+merge

#6123 SAK-38421 fix use of improper role=menuitem buttom
  lessonbuilder/tool/src/resources/messages.properties
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
Labels: accessibility

#6128 SAK-40763 Update spanish translations.
  announcement/announcement-tool/tool/src/bundle/announcement_es.properties
  assignment/bundles/resources/assignment-noti-prefs_es.properties
  assignment/bundles/resources/assignment_es.properties
  basiclti/basiclti-impl/src/bundle/ltiservice_es.properties
  basiclti/basiclti-tool/src/bundle/ltitool_es.properties
  content-review/impl/turnitin-oc/src/main/resources/turnitin_es.properties
  content/content-bundles/resources/content_es.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
  help/help-component/src/bundle/TutorialMessages_es.properties
  jsf2/jsf2-widgets/src/bundle/pager_es.properties
  lessonbuilder/tool/src/resources/messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  roster2/src/i18n/org/sakaiproject/roster/i18n/ui_es.properties
  rubrics/impl/src/main/bundle/rubricsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages_es.properties
  signup/impl/src/bundle/emailMessage_es.properties
  site-manage/site-manage-participant-helper/src/bundle/org/sakaiproject/site/tool/participant/bundle/sitesetupgeneric_es.properties
  site-manage/site-manage-tool/tool/src/bundle/membership_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitebrowser_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  sitestats/sitestats-bundle/src/resources/Events_es.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
Labels: I18N, L10N, translation, use squash+merge

#6135 SAK-40777: Polls > 'poll.add' event is never fired due to logic error
  polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
  polls/impl/src/test/org/sakaiproject/poll/logic/test/PollListManagerTest.java
Labels: low risk

#6141 SAK-40780 Assignment commons-lang => commons-lang3, commons-text
  assignment/impl/pom.xml
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/AssignmentSubmissionAccess.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/CombineDuplicateSubmissionsConversionHandler.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/O11Property.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/reminder/AssignmentDueReminderServiceImpl.java
  assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentConversionTest.java
  assignment/impl/src/test/org/sakaiproject/assignment/impl/SpreadsheetExporterTest.java
  master/pom.xml
Labels: low risk

#6132 SAK-40760: Another ClassCastException related to number of retakes
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Labels: low risk

#6139 SAK-34439: Samigo > erroneous bold styling on answers to MC, MS and T/F questions
  library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/webapp/css/tool_sam.css
Labels: use rebase+merge

#6131 SAK-40767 - Attendance tool: Provide an icon to the default skin.
  library/src/morpheus-master/sass/base/_icons.scss
Labels: low risk, use squash+merge

#6150 SAK-40685. Catalan bundles update for Sakai 19
  announcement/announcement-tool/tool/src/bundle/announcement_ca.properties
  assignment/api/src/java/org/sakaiproject/assignment/api/conversion/messages_ca.properties
  assignment/bundles/resources/assignment-noti-prefs_ca.properties
  assignment/bundles/resources/assignment_ca.properties
  basiclti/basiclti-impl/src/bundle/ltiservice_ca.properties
  basiclti/basiclti-tool/src/bundle/ltitool_ca.properties
  content-review/impl/turnitin-oc/src/main/resources/turnitin_ca.properties
  content/content-bundles/resources/content_ca.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_ca.properties
  help/help-component/src/bundle/TutorialMessages_ca.properties
  jsf2/jsf2-widgets/src/bundle/pager_ca.properties
  jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/Configuration_ca.properties
  lessonbuilder/tool/src/resources/messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  portal/portal-impl/impl/src/bundle/sitenav_ca.properties
  roster2/src/i18n/org/sakaiproject/roster/i18n/ui_ca.properties
  rubrics/impl/src/main/bundle/rubricsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/membership_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/sitebrowser_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties
  sitestats/sitestats-bundle/src/resources/Events_ca.properties
  sitestats/sitestats-bundle/src/resources/Messages_ca.properties
Labels: L10N, low risk

#6159 SAK-40798: GBNG > incorrect error message when trying to add drop/keep to a category with items of different values
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Labels: low risk, use rebase+merge

#6165 SAK-40795 Update Spring dependencies
  master/pom.xml
Labels: BLOCKER

#6164 SAK-40809 Add Turkish tool name and description which not included in Transifex for BBB and News
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_tr_TR.properties
Labels: L10N

#6167 SAK-40810 - Rubrics doesn't start due to Spring dependencies upgrade
  rubrics/api/pom.xml
  rubrics/impl/src/main/webapp/WEB-INF/components.xml
  rubrics/pom.xml
  rubrics/tool/pom.xml
Labels: BLOCKER, please merge sakai-19

#6188 SAK-40852 - Update some dependencies
  common/pom.xml
Labels: for discussion, work in progress

#6189 SAK-40857: DelegatedAccess doesn't work for provided LDAP users
  delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/logic/SakaiProxyImpl.java
Labels: use rebase+merge

#6192 SAK-32657 Keyboard controls needed for Syllabus reorder
  announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_reorder_assignment.vm
  content/content-tool/tool/src/webapp/vm/content/chef_resources_reorder.vm
  library/src/morpheus-master/js/src/sakai.morpheus.reorderer.js
  site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js
  site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
  syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages.properties
  syllabus/syllabus-app/src/webapp/js/syllabus.js
  syllabus/syllabus-app/src/webapp/syllabus/main.jsp
Labels: accessibility

#6194 SAK-40860 - Rubrics associations with other tools are not working
  rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/RubricsLocalDateTimeSerializer.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Metadata.java
  rubrics/tool/src/main/frontend/imports/sakai-rubric.html
Labels: BLOCKER, I18N
