Repository sakaiproject/sakai, pull requests merged in 2019-10, with the labels that each got.

#7390 SAK-42569 Polls: Allow creating options in batch
  polls/tool/pom.xml
  polls/tool/src/bundle/org/sakaiproject/poll/bundle/Messages.properties
  polls/tool/src/bundle/org/sakaiproject/poll/bundle/Messages_ca.properties
  polls/tool/src/bundle/org/sakaiproject/poll/bundle/Messages_es.properties
  polls/tool/src/bundle/org/sakaiproject/poll/bundle/Messages_eu.properties
  polls/tool/src/java/org/sakaiproject/poll/tool/params/OptionBatchViewParameters.java
  polls/tool/src/java/org/sakaiproject/poll/tool/params/PollToolBean.java
  polls/tool/src/java/org/sakaiproject/poll/tool/producers/AddPollProducer.java
  polls/tool/src/java/org/sakaiproject/poll/tool/producers/PollOptionBatchProducer.java
  polls/tool/src/java/org/sakaiproject/poll/tool/util/OptionsFileConverterUtil.java
  polls/tool/src/java/org/sakaiproject/poll/tool/validators/OptionValidator.java
  polls/tool/src/webapp/WEB-INF/requestContext.xml
  polls/tool/src/webapp/templates/pollOptionBatch.html
  polls/tool/src/webapp/templates/voteAdd.html
Labels: enhancement

#7410 SAK-42434 Samigo: fix advanced feedback options availability
  samigo/samigo-app/src/webapp/js/authoring.js
Labels: bug

#7412 SAK-42314 Fix Resources header, remove duplicates, check tool
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Labels: bug, priority

#7411 SAK-42586 Private Messages: Messages tool / unable to open link to si…
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Labels: bug, priority

#7420 Adding a quick test for SAK-42559
  entitybroker/api/src/test/org/sakaiproject/entitybroker/util/TemplateParseUtilTest.java
Labels: low risk

#7405 SAK-42581 WebJars: Upgrade CKEditor from 4.12.1 to 4.13.0
  library/pom.xml
  library/src/morpheus-master/sass/modules/editor/_base.scss
  library/src/webapp/js/headscripts.js
  portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
Labels: enhancement

#7404 SAK-42582 WebJars: CKEditor image2 plugin upgrade to 4.13.0
  master/pom.xml
Labels: enhancement

#7403 SAK-42583 - WebJars: Upgrade Elfinder to 2.1.50
  library/pom.xml
  library/src/webapp/editor/elfinder/sakai/elfinder.html
Labels: enhancement

#7398 SAK-42569 - Polls: Avoid options for rows with spaces
  polls/tool/src/java/org/sakaiproject/poll/tool/util/OptionsFileConverterUtil.java
Labels: bug, low risk

#7425 SAK-42617 WebJars: Upgrade datatables from 1.10.19 to 1.10.20
  library/pom.xml
  library/src/webapp/js/headscripts.js
Labels: enhancement

#7427 SAK-42618 Assessments: Use banner info when there are no assessments.
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Labels: enhancement

#7445 SAK-42650 Update Apache Tomcat 9.0.27
  master/pom.xml
Labels: low risk

#7446 SAK-42651 - Update spanish translations for master (October'19)
  commons/api/src/bundle/commons_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  content-review/impl/compilatio/src/main/resources/compilatio_es.properties
  content-review/impl/turnitin-oc/src/main/resources/turnitin-oc_es.properties
  content-review/impl/turnitin/src/main/resources/turnitin_es.properties
  content-review/impl/urkund/src/main/resources/urkund_es.properties
  content-review/impl/vericite/src/main/resources/vericite_es.properties
  content/content-bundles/resources/types_es.properties
  content/content-tool/tool/src/bundle/helper_es.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
  lessonbuilder/tool/src/resources/messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/i18n/pasystem_es.properties
  podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages_es.properties
  polls/tool/src/bundle/org/sakaiproject/poll/bundle/Messages_es.properties
  portal/portal-chat/tool/src/java/portal-chat_es.properties
  portal/portal-impl/impl/src/bundle/bullhorns_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  profile2/bundle/src/resources/ProfileApplication_es.properties
  reset-pass/reset-pass/src/bundle/org/sakaiproject/tool/resetpass/bundle/Messages_es.properties
  roster2/bundle/src/bundle/roster_es.properties
  rubrics/api/src/main/bundle/rubrics_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  sections/sections-app/src/bundle/sections_es.properties
  site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages_es.properties
  site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_es.properties
  site-manage/site-manage-participant-helper/src/bundle/org/sakaiproject/site/tool/participant/bundle/sitesetupgeneric_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitebrowser_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  site/term-manager/tool/src/java/org/sakaiproject/acadtermmanage/tool/AcademicSessionAdminApplication_es.properties
  site/term-manager/tool/src/java/org/sakaiproject/acadtermmanage/tool/pages/SemesterPage_es.properties
  syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/syllabus_es.properties
  webcomponents/bundle/src/main/bundle/maximise-button_es.properties
  webcomponents/bundle/src/main/bundle/pager_es.properties
  webcomponents/bundle/src/main/bundle/permissions_es.properties
  webcomponents/bundle/src/main/bundle/search_es.properties
Labels: I18N

#7455 SAK-42662: Double click in Sign-up -> Server goes down
  signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
Labels: BLOCKER, priority, use squash+merge

#7448 SAK-42653 WebJars: Upgrade fullcalendar from 4.2.0 to 4.3.1 (Oct-2019)
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  library/pom.xml
Labels: enhancement

#7447 SAK-42652 - WebJars: Upgrade codemirror from 5.48.2 to 5.49.0 (Oct-2019)
  library/pom.xml
  library/src/webapp/editor/elfinder/sakai/js/src/editors.js
Labels: enhancement

#7430 SAK-42624 - MSGCNTR: Move managed-bean configuration from XML to Anno…
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumSynopticBean.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumSynopticBeanLite.java
  msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml
Labels: enhancement

#7429 SAK-42623 Chat: Move managed-bean configuration from XML to Annotations
  chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
  chat/chat-tool/tool/src/webapp/WEB-INF/faces-config.xml
Labels: enhancement

#7428 SAK-42619 Tests&Quizzes: Move managed-bean configuration from XML to …
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AttachmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/DeleteConfirmBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/EventLogBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/IndexBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemConfigBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishRepublishNotificationBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentBeanie.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SearchQuestionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionActivityBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/TemplateBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/authz/AuthorizationBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/cms/CourseManagementBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/DownloadFileSubmissionsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/EvaluationResultBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramQuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/RetakeAssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/StudentScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionStatusBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/misc/BuildInfoBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/settings/PrintSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLController.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLDisplay.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLImportBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolDataBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolShareBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/samlite/SamLiteBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/select/SelectAssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/shared/BackingBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/shared/MediaBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/shared/PersonBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/shared/SubBackingBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/util/EmailBean.java
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/jsf/LinksModelBean.java
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/jsf/SubBackingBean.java
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/jsf/TestBackingBean.java
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/jsf/TestLinksBean.java
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/jsf/TestWSBean.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
Labels: enhancement

#7481 SAK-42176 - Tests & Quizzes: Can't delete exceptions
  samigo/samigo-hibernate/pom.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBaseData.java
Labels: bug, priority

#7480 NOJIRA: T&Q Extended feature, spacing cleanup
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ExtendedTime.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeQueriesAPI.java
Labels: low risk

#7495 SAK-38310 - Provide text equivalent for icon font in site info
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
Labels: low risk

#7494 SAK-31784 - No error message displayed when missing file on Postem
  postem/postem-app/src/java/org/sakaiproject/tool/postem/PostemTool.java
Labels: low risk

#7485 SAK-42680 Users can always resubmit returned assignments
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
Labels: BLOCKER, bug

#7490 SAK-42692 - WebJars: Upgrade mathjs from 6.0.3 to 6.2.3
  library/pom.xml
  library/src/webapp/js/headscripts.js
Labels: enhancement

#7507 SAK-42709 Portal: Javascript stacktrace in xlogin
  library/src/morpheus-master/js/src/sakai.morpheus.footer.js
Labels: bug

#7513 NOJIRA. Fix typo in sass configuration maven property
  library/pom.xml
Labels: low risk

#7514 NOJIRA. Update quartz logo
  jobscheduler/scheduler-tool/src/webapp/images/quartz.gif
  jobscheduler/scheduler-tool/src/webapp/images/quartz.jpg
Labels: enhancement, low risk
