Repository sakaiproject/sakai, pull requests merged in 2019-09, with the labels that each got.

#7313 SAK-42427 Podcasts: UI Revamp
  podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages.properties
  podcasts/podcasts-app/src/webapp/css/podcaster.css
  podcasts/podcasts-app/src/webapp/podcasts/podAdd.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podDelete.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podMain.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podNoResource.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podRevise.jsp
  podcasts/podcasts-app/src/webapp/scripts/popupscripts.js
Labels: enhancement, future

#7338 SAK-42432 Fix Sakai banner when passwords match
  admin-tools/src/webapp/vm/user/chef_users_edit.vm
Labels: bug, low risk

#7347 SAK-42492 update freemarker 2.3.29
  emailtemplateservice/impl/logic/pom.xml
Labels: low risk

#7343 SAK-42099 T&Q: When editing a part that has a random draw, the wrong …
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java
Labels: bug

#7344 SAK-42483 - Portal: Jump-to-Top Behavior
  library/src/morpheus-master/images/jumptotop.png
  library/src/morpheus-master/sass/modules/jumptotop/_base.scss
  library/src/morpheus-master/sass/tool.scss
  portal/portal-charon/charon/src/webapp/scripts/jumptotop.js
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
Labels: enhancement, future

#7354 SAK-42232 Calendar: Fix an issue with the iCal 3.0.7 upgrade
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java
Labels: bug, priority

#6680 SAK-34725: Submit the answers when the time is over for non-timed assessments.
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/webapp/js/saveForm.js
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
Labels: work in progress

#7389 SAK-42568 Update joda-time 2.10.4
  master/pom.xml
Labels: low risk

#7391 SAK-42570 Remove filepath from screen
  signup/tool/src/webapp/signup/newMeeting/step1.jsp
Labels: priority
