Repository sakaiproject/sakai, pull requests merged in 2019-05, with the labels that each got.

#6869 SAK-41741 Made student rubric comment view ids unique
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
Labels: low risk

#6868 SAK-41739: DA > prevent hierarchy job from auto-restarting
  delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/jobs/DelegatedAccessSiteHierarchyJob.java
Labels: use rebase+merge

#6875 SAK-41740: DA > use friendly label for over-ridden hierarcy props
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchAccessPage.java
Labels: use rebase+merge

#6847 SAK-41718: DA > more config options to enable or disable settings
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  delegatedaccess/api/src/java/org/sakaiproject/delegatedaccess/logic/SakaiProxy.java
  delegatedaccess/api/src/java/org/sakaiproject/delegatedaccess/util/DelegatedAccessConstants.java
  delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/logic/SakaiProxyImpl.java
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/DelegatedAccessApplication.properties
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchAccessPage.java
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserEditPage.html
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserEditPage.java
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserPageSiteSearch.java
Labels: use rebase+merge

#6911 SAK-41765 Update TR files from Transifex
  admin-su/src/bundle/tool-tool-su_tr_TR.properties
  announcement/announcement-impl/impl/src/bundle/siteemaanc_tr_TR.properties
  announcement/announcement-tool/tool/src/bundle/announcement_tr_TR.properties
  assignment/bundles/resources/assignment-noti-prefs_tr_TR.properties
  assignment/bundles/resources/assignment_tr_TR.properties
  assignment/bundles/resources/permissions_tr_TR.properties
  basiclti/basiclti-blis/src/bundle/blis_tr_TR.properties
  basiclti/basiclti-impl/src/bundle/basicltisvc_tr_TR.properties
  chat/chat-tool/tool/src/bundle/chat_tr_TR.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/type/types_tr_TR.properties
  content/content-bundles/resources/content_tr_TR.properties
  content/content-bundles/resources/types_tr_TR.properties
  content/content-copyright/impl/src/bundle/org/sakaiproject/content/copyright/copyright_tr_TR.properties
  roster2/bundle/src/bundle/org/sakaiproject/roster/bundle/Messages_tr_TR.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_tr_TR.properties
  sections/sections-app-util/src/bundle/sections_tr_TR.properties
  signup/tool/src/bundle/messages_tr_TR.properties
  site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_tr_TR.properties
  site-manage/site-manage-tool/tool/src/bundle/membership_tr_TR.properties
  site-manage/site-manage-tool/tool/src/bundle/sitebrowser_tr_TR.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_tr_TR.properties
  sitestats/sitestats-bundle/src/resources/Events_tr_TR.properties
  syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages_tr_TR.properties
Labels: I18N, L10N

#6925 SAK-41775 Made rubric lightbox overflow: scroll
  library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss
Labels: low risk

#6929 SAK-41812 Profile: Include new name pronunciation feature in Profile
  common/common-api/src/java/org/sakaiproject/api/common/edu/person/SakaiPerson.java
  common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.hbm.xml
  common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.java
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  library/pom.xml
  library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss
  profile2/api/src/java/org/sakaiproject/profile2/logic/ProfileLogic.java
  profile2/api/src/java/org/sakaiproject/profile2/logic/SakaiProxy.java
  profile2/api/src/java/org/sakaiproject/profile2/model/MyProfilePanelState.java
  profile2/api/src/java/org/sakaiproject/profile2/model/UserProfile.java
  profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java
  profile2/bundle/src/resources/ProfileApplication.properties
  profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileLogicImpl.java
  profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyProfilePanel.html
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyProfilePanel.java
  profile2/tool/src/webapp/css/profile2.css
  profile2/tool/src/webapp/images/mic.png
Labels: use squash+merge

#6961 SAK-41857 - Update frontend-maven-plugin version to 1.7.6
  webcomponents/pom.xml
Labels: low risk

#6969 SAK-41829 GradebookNG. Escape some inputs
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
Labels: priority
