Repository sakaiproject/sakai, pull requests merged in 2019-12, with the labels that each got.

#7633 SAK-42806 - Adding modified dates when published assessment is deleted
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: low risk

#7619 SAK-40829 Library: Remove all cases of fa-leanpub
  library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
  library/src/morpheus-master/sass/base/_icons.scss
  library/src/morpheus-master/sass/modules/_toolmenu.scss
Labels: for discussion

#7634 SAK-42841 - New recovered assessments tab should have a unique identi…
  samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
Labels: for discussion

#7630 SAK-41838 Syllabus / unable to delete attachment from edit tab
  syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusManagerImpl.java
Labels: priority

#7618 SAK-34403 T&Q: Hardcoded string message in Survey matrix of choices q…
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/webapp/js/samigo-global.js
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
Labels: L10N

#7670 SAK-42886 Update Post Em description
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
Labels: cla?
