Repository sakaiproject/sakai, pull requests merged in 2019-01, with the labels that each got.

#6399 SAK-41091: Site Info > new sakai.property for more granular control of site creation notification emails
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/UserNotificationProvider.java
  site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
  site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/UserNotificationProviderImpl.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge

#6461 SAK-41174 Solve performance problem in Samigo related to Rubrics
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Labels: BLOCKER

#6433 SAK-41138 swapped-view header color does not change when re-enabling …
  library/src/morpheus-master/sass/_defaults.scss
  library/src/morpheus-master/sass/examples/_customization_example_empty.scss
  library/src/morpheus-master/sass/modules/swapped-view/_base.scss
  library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Labels: work in progress

#6477 SAK-41209: GradebookNG > new sakai.property to disable 'Set Zero Score for Empty Cells'
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
Labels: low risk

#6486 SAK-41223: GradebookNG > Import > extend 'hide items with no changes' to external items
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
Labels: low risk, use rebase+merge

#6495 SAK-41234: GradebookNG > improve external item information message
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
Labels: low risk, use rebase+merge

#6494 SAK-41233: GradebookNG > add user's first and last name to grade log entry display
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverrideLogPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeLogPanel.java
Labels: low risk, use rebase+merge

#6492 SAK-41232: GradebookNG > improve ability to import a custom exported file
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Labels: low risk

#6496 SAK-41235: GradebookNG > restore ability for Instructor to remove all TA perms
  edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookPermissionService.java
  edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
  edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GraderPermission.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookPermissionServiceImpl.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
Labels: use rebase+merge

#6503 SAK-41251: GBNG > stack trace when entering grades in table
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/CommentValidator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.java
  gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
Labels: BLOCKER

#6501 SAK-41248: Lessons > set Settings tooltip to 'Settings'
  lessonbuilder/tool/src/resources/messages.properties
Labels: low risk
