Repository sakaiproject/sakai, pull requests merged in 2019-02, with the labels that each got.

#6530 SAK-41302: Samigo > re-word the description of the Model Short Answer field
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
Labels: low risk, use rebase+merge

#6529 SAK-41301: Samigo > rename 'right less wrong' to 'correct minus incorrect'
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_fr_FR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
Labels: low risk, use rebase+merge

#6537 SAK-32651 - Passing certification suite
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LineItemUtil.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-impl/src/bundle/ltiservice.properties
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  basiclti/basiclti-oidc/src/java/org/sakaiproject/lti13/OIDCServlet.java
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/tsugi-util/src/java/org/tsugi/ags2/objects/LineItem.java
  basiclti/tsugi-util/src/java/org/tsugi/ags2/objects/Result.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13KeySetUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/NamesAndRoles.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13ObjectTest.java
Labels: work in progress

#6542 SAK-41137 Check for defined column data
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: work in progress

#6534 SAK-41306: Samigo > incorrect button styling for Honour Pledge assessment
  samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
Labels: low risk, use rebase+merge

#6531 SAK-41303: Samigo > further quality password field label for clarity
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
Labels: low risk, use rebase+merge

#6528 SAK-41300: Samigo > importing quiz released to anon users doesn't preserve the setting
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
Labels: use rebase+merge

#6521 SAK-41287: Worksite Setup > new config for default site visibility setting
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge

#6549 SAK-41331 Lombok 1.18.6
  master/pom.xml
Labels: low risk

#6510 SAK-41264: Samigo > 'stop accepting now' not working on tests with 'no late submissions accepted'
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
Labels: use rebase+merge

#6512 SAK-41266: Email > include site title in subject line
  mailarchive/mailarchive-impl/impl/src/java/org/sakaiproject/mailarchive/impl/SiteEmailNotificationMail.java
Labels: low risk, use rebase+merge

#6533 SAK-41305: Samigo > Download File Submissions page shows internal IDs for each question
  library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
Labels: low risk, use rebase+merge

#6547 SAK-41327: Samigo > clarify text shown to students when beginning a quiz
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
Labels: low risk, use rebase+merge

#6546 SAK-41326: Site Info > new config to prevent stealthed tools being copied to duplicate sites
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: low risk, use rebase+merge

#6563 SAK-41348: Worksite Setup > position and primary action for 'continue with no roster' button
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
Labels: low risk, use rebase+merge

#6564 SAK-41351 AccountValidator ValidationLogic clean up
  reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.java
  reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/impl/jobs/CheckAccountsJob.java
  reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/impl/jobs/CheckValidations.java
  reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
  reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
Labels: low risk

#6516 SAK-41276: improve user facing content cleaned message
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content.properties
Labels: low risk, use rebase+merge

#6561 SAK-41346: Site Info > allow maintainer to delete last roster in course site
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge
