Repository sakaiproject/sakai, pull requests merged in 2019-04, with the labels that each got.

#6722 SAK-41562 Forums problems sorting private messages
  library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-app/pom.xml
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
Labels: enhancement

#6744 SAK-41618 Set bullhorn dependencies using annotations
  portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
  portal/portal-service-impl/impl/src/webapp/WEB-INF/components.xml
Labels: low risk

#6799 SAK-41663 Preferences -> Site. Error getting favorites
  user/user-tool-prefs/tool/src/webapp/js/manage-hidden-sites.js
Labels: use squash+merge

#6815 SAK-41679 Rubrics : i18n improvements
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_ca.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_es.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_tr_TR.properties
  rubrics/impl/src/main/bundle/rubricsMessages.properties
  rubrics/impl/src/main/bundle/rubricsMessages_ca.properties
  rubrics/impl/src/main/bundle/rubricsMessages_es.properties
  rubrics/impl/src/main/bundle/rubricsMessages_tr_TR.properties
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric.js
Labels: I18N, L10N

#6828 SAK-41693 page:https://confluence.sakaiproject.org/display/BOOT/Insta…
  README.md
Labels: please merge sakai-19

#6823 SAK-41687: GradebookNG > hide 'edit release settings' based on sakai.property
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
Labels: low risk

#6865 SAK-41730 If site has no groups message the participant management do…
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Labels: low risk

#6864 SAK-41727 Improved styling on ConnectionManger
  commons/tool/src/webapp/WEB-INF/templates/comment.hbs
  commons/tool/src/webapp/WEB-INF/templates/post.hbs
  commons/tool/src/webapp/js/commons_utils.js
  library/src/morpheus-master/js/src/sakai.morpheus.connection-manager.js
  library/src/morpheus-master/js/src/sakai.morpheus.profile.popup.js
  library/src/morpheus-master/sass/modules/connection-manager/_base.scss
  library/src/morpheus-master/sass/modules/profile-popup/_base.scss
  library/src/templates/connection-manager-searchresult.hbs
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/profile-popup.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/connection-manager.vm
Labels: work in progress

#6862 SAK-41725 Lessons: Populate ContentItem description
  basiclti/basiclti-tool/pom.xml
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/basiclti-tool/src/webapp/vm/lti_content_config.vm
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/ForumEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/JForumEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/BltiPickerProducer.java
  lessonbuilder/tool/src/resources/messages.properties
  lessonbuilder/tool/src/webapp/templates/BltiPicker.html
Labels: enhancement
