Repository sakaiproject/sakai, pull requests merged in 2019-07, with the labels that each got.

#7070 SAK-42044 Access: TimeService Deprecated, time.Year
  access/access-impl/impl/src/java/org/sakaiproject/access/tool/WebServlet.java
Labels: low risk

#7068 SAK-42032 lessons: TimeService => UserTimeService; ScheduledInvocatio…
  jobscheduler/scheduler-test-component-shared/src/java/org/sakaiproject/component/app/scheduler/ScheduledInvocationTestJob.java
  jobscheduler/scheduler-test-component/src/webapp/WEB-INF/components.xml
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
Labels: low risk

#7113 SAK-42134 update Joda-time 2.10.3
  master/pom.xml
Labels: low risk

#7021 SAK-41929 - Rubrics forums: Preview doesn't work in some cases
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
Labels: for discussion, work in progress

#7120 SAK-41898 - Error saving T&Q responses for other questions after nume…
  library/pom.xml
  library/src/webapp/js/headscripts.js
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fa_IR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fr_FR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_hi_IN.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ja.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_mn.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_pt_BR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_tr_TR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_zh_CN.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/validator/FinResponseValidator.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: BLOCKER, use squash+merge

#7118 SAK-42108 - Tests & Quizzes: Problem with webjars/mathjs, numeric que…
  library/src/webapp/js/headscripts.js
Labels: BLOCKER, use squash+merge

#7092 SAK-42077 : Can't show a gradebook item when clicking arrows
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: use squash+merge

#6995 SAK-41909 - Strenghten Sakai 20. Jun19 Upgrade libraries and dependencies.
  basiclti/basiclti-blis/pom.xml
  basiclti/basiclti-common/pom.xml
  basiclti/basiclti-impl/pom.xml
  basiclti/tsugi-util/pom-tsugi.xml
  basiclti/tsugi-util/pom.xml
  calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/IntegrationTests.java
  calendar/calendar-impl/impl/src/test/resources/test-resources.xml
  chat/chat-tool/tool/pom.xml
  citations/citations-tool/tool/pom.xml
  content-review/impl/urkund/pom.xml
  content/content-tool/tool/pom.xml
  deploy/pom.xml
  edu-services/cm-service/cm-impl/hibernate-impl/impl/pom.xml
  edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/job/CmSynchronizer.java
  emailtemplateservice/impl/logic/pom.xml
  emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
  entitybroker/pom.xml
  lessonbuilder/tool/pom.xml
  master/pom.xml
  msgcntr/messageforums-app/pom.xml
  pasystem/pasystem-impl/impl/pom.xml
  pasystem/pasystem-tool/tool/pom.xml
  profile2/tool/pom.xml
  rwiki/rwiki-util/jrcs/pom.xml
  samigo/samigo-app/pom.xml
  samigo/samigo-impl/pom.xml
  sections/sections-app/pom.xml
  sections/sections-app/src/test/org/sakaiproject/test/section/SectionsTestBase.java
  tags/tags-impl/impl/pom.xml
Labels: enhancement, future

#7148 SAK-42189: Improve the resource picker
  content/content-tool/tool/src/bundle/helper.properties
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
  content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
Labels: enhancement, future, use squash+merge

#7158 SAK-42197 - Webjars: Upgrade Elfinder from 2.1.48 to 2.1.49
  library/pom.xml
  library/src/webapp/editor/elfinder/sakai/elfinder.html
Labels: BLOCKER

#7175 SAK-42224 - User Urlencode instead of htmlescape
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
Labels: low risk

#7176 SAK-42223 - Fix the app stores all run together in the UI
  lessonbuilder/tool/src/webapp/templates/BltiPicker.html
Labels: low risk

#7152 SAK-42191: Site Info > Manage Participants > Sort by ID isn't sorting by ID
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
  site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteParticipantHelper.java
Labels: low risk

#7193 SAK-42242 - Improve error checking / messages
  basiclti/basiclti-docs/resources/docs/Advantage_TestPlan.xls
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java
  basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13UtilTest.java
Labels: low risk

#7194 SAK-42243 - Make lessons LTI modals prettier.
  lessonbuilder/tool/src/webapp/templates/BltiPicker.html
  library/src/webapp/js/headscripts.js
Labels: low risk
