Repository sakaiproject/sakai, pull requests merged in 2019-11, with the labels that each got.

#7512 SAK-42706 Quizzes: Removing uploaded file - stack trace
  samigo/samigo-app/src/webapp/jsf/shared/removeMedia.jsp
Labels: BLOCKER

#6536 SAK-41172 Group Locking Enhancements
  admin-tools/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
  admin-tools/src/java/org/sakaiproject/authz/tool/RealmsAction.java
  admin-tools/src/java/org/sakaiproject/site/tool/AdminSitesAction.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/RangeAndGroupsDelegate.java
  calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
  edu-services/sections-service/sections-impl/sakai/impl/src/java/org/sakaiproject/component/section/sakai/SectionManagerImpl.java
  edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseSectionImpl.java
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/SiteEntityProvider.java
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityGroup.java
  entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntitySite.java
  kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroup.java
  kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupService.java
  kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzRealmLockException.java
  kernel/api/src/main/java/org/sakaiproject/site/api/Group.java
  kernel/api/src/main/java/org/sakaiproject/site/api/Site.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroup.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/RoleAccessTest.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/RoleViewTest.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
  message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemoveAssessmentListener.java
  signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java
  site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/impl/SiteManageGroupHandler.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupDelProducer.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java
  site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupListProducer.java
Labels: BLOCKER

#7320 SAK-42289 Assignments Could not serialize to xml when archiving
  admin-tools/src/bundle/archive_es.properties
  admin-tools/src/java/org/sakaiproject/archive/tool/ArchiveAction.java
  assignment/api/pom.xml
  assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
  assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentServiceConstants.java
  assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
  assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java
  assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmissionSubmitter.java
  assignment/impl/pom.xml
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
  assignment/impl/src/test/resources/importAssignment.xml
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  deploy/pom.xml
  kernel/kernel-private/pom.xml
  kernel/kernel-private/src/main/java/org/sakaiproject/hibernate/CrudRepository.java
  kernel/kernel-private/src/main/java/org/sakaiproject/hibernate/HibernateCrudRepository.java
  kernel/kernel-private/src/main/java/org/sakaiproject/serialization/BasicSerializableRepository.java
  master/pom.xml
Labels: use rebase+merge

#7489 SAK-42686 - Edge: Error saving T&Q responses for other questions afte…
  samigo/samigo-app/src/webapp/js/finInputValidator.js
  samigo/samigo-app/src/webapp/js/saveForm.js
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
Labels: BLOCKER

#7523 SAK-42708: Hour repeated in the text of the body when 'replying to all' in a message
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Labels: I18N

#7529 SAK-42743 Update Joda-time 2.10.5
  master/pom.xml
Labels: low risk

#7525 NOJIRA tab => space
  common/common-composite-component/src/webapp/WEB-INF/components.xml
Labels: low risk

#7540 SAK-42090 Associated labels for fields properly
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-edit.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js
Labels: work in progress

#7542 SAK-42760 T&Q: Feedback by date, data is not visible to students.
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
Labels: priority

#7541 SAK-42751 - Improve layout when there are no attachments
  samigo/samigo-app/src/webapp/jsf/author/item/attachment.jsp
Labels: low risk

#7562 SAK-42686 T&Q: Validate numeric responses periodically
  samigo/samigo-app/src/webapp/js/finInputValidator.js
  samigo/samigo-app/src/webapp/js/saveForm.js
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
Labels: BLOCKER

#7566 SAK-42799 convert date to user's preferred time zone as instructor
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
  samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecording.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecordingAnswer.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/submissionStatus.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
  samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/copyPoolTree.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/movePoolTree.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/subpoolsTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/transferPoolConfirm.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/transferPoolTree.jsp
  samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivity.jsp
  samigo/samigo-app/src/webapp/jsf/template/templateIndex.jsp
Labels: I18N

#7567 SAK-40226 can now use datepicker in your preferred time zone
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/TimeUtil.java
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf
  samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Labels: I18N

#7576 SAK-42796 - GB console errors in student view once there is something…
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java
Labels: low risk

#7597 SAK-42514 Quizzes: When instructor chooses to print a quiz, the botto…
  library/src/morpheus-master/sass/print.scss
  samigo/samigo-app/src/webapp/css/print/print.css
  samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
Labels: priority

#7600 SAK-42826 Messages: Messages list Javascript error
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
Labels: priority

#7598 SAK-41927 Polls / attempting to sort columns on results page displays…
  polls/tool/src/webapp/templates/voteResults.html
Labels: priority
