Repository sakaiproject/sakai, pull requests merged in 2019-03, with the labels that each got.

#6597 Instructor sees "Sections you are a member of" instead of just "Sections"
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: low risk

#6637 SAK-41210 Small fix with parent variable
  library/src/webapp/js/sakai-reminder.js
Labels: low risk

#6646 SAK-41459 Grading forums: Portal is not defined in the modal window
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js
Labels: BLOCKER

#6651 SAK-41492 Untranslated string in Rubrics student comment
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
Labels: low risk

#6660 SAK-41497 Updated some rubrics i18n
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_ca.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_es.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_tr_TR.properties
  rubrics/tool/src/main/frontend/webcomponents/sakai-item-delete.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-readonly.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubric.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-list.js
  rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-shared-list.js
  webcomponents/src/webapp/sakai-i18n.js
Labels: I18N

#6663 SAK-41504 GradebookNg: commons-Lang => commons-Lang3
  gradebookng/tool/pom.xml
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/AssignmentGradeComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/CategorySubtotalComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/CourseGradeComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/FirstNameComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/FirstNameComparatorGbUser.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/LastNameComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/LetterGradeComparator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/CommentValidator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/GradeValidator.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbCourseGrade.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGradeInfo.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGradeLog.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGroup.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedColumn.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ProcessedGradeItem.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/GbStopWatch.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/SettingsHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbStyleableWebMarkupContainer.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ErrorPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverrideLogPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
  gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
Labels: GradebookNG

#6548 SAK-41328: Samigo > interim solution for SAK-34222
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport.properties
  samigo/samigo-app/src/webapp/jsf/qti/chooseExportType.jsp
  samigo/samigo-app/src/webapp/jsf/qti/importAssessment.jsp
Labels: low risk

#6532 SAK-41304: Samigo > improve wording of wildcard option in FITB question author screens
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
Labels: low risk

#6520 SAK-41286: site-info > provide more info when displaying rosters available for selection
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
Labels: low risk

#6655 SAK-41489 Sitestats for Students: Display the number of visits and th…
  library/src/morpheus-master/sass/modules/tool/sitestats/_sitestats.scss
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/PrefsData.java
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/StatsAuthz.java
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/StatsManager.java
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/report/ReportManager.java
  sitestats/sitestats-bundle/src/resources/Messages.properties
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAuthzImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/parser/DigesterUtil.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/ReportManagerTest.java
  sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/SiteStatsEntityProvider.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/LastJobRun.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/Menus.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/OverviewPage.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/PreferencesPage.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/providers/ReportsDataProvider.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ActivityWidget.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/LessonsWidget.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ResourcesWidget.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/StudentVisitsWidget.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/VisitsWidget.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/Widget.java
  sitestats/sitestats-tool/src/webapp/WEB-INF/tools/sakai.sitestats.xml
  sitestats/sitestats-tool/src/webapp/html/components/EventRegistryTree.html
  sitestats/sitestats-tool/src/webapp/html/pages/PreferencesPage.html
  sitestats/sitestats-tool/src/webapp/html/widget/StudentVisitsWidget.html
Labels: for discussion, future, ready to test

#6504 SAK-41240 Confusing description in instructions of markup text
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite.properties
Labels: low risk

#6697 SAK-41546 Update default url for RSS tool
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  simple-rss-portlet/src/main/webapp/WEB-INF/sakai/simple-rss-portlet.xml
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: work in progress

#6700 SAK-41552: When grading forums associated with gradebook item the grades aren't internacionalized
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
Labels: I18N

#6705 SAK-33776 Updated handsontable to Sakai's version 6.2.2
  gradebookng/tool/pom.xml
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: work in progress
