Repository sakaiproject/sakai, pull requests merged in 2019-08, with the labels that each got.

#7119 SAK-42042 - Profile: Name Pronunciation server log errors
  profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
Labels: use squash+merge

#7183 SAK-42231 - CKEDITOR IMAGE2 plugin. Update from 4.11.1 -> 4.12.1
  master/pom.xml
Labels: work in progress

#7210 SAK-42250 - Make morpheus scripts check variable before using
  library/src/morpheus-master/js/src/sakai.morpheus.session.js
Labels: low risk

#7150 SAK-42185: Site Info > Manage Participants > Filter View by Role > Remove user returns error when it shouldn't
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_eu.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_fa_IR.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_hi_IN.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ja.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_pt_BR.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_tr_TR.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_zh_CN.properties
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use squash+merge

#7218 SAK-42295 - Convert documentation to Markdown
  basiclti/README.md
  basiclti/basiclti-docs/resources/docs/README.md
  basiclti/basiclti-docs/resources/docs/sakai_basiclti_api.doc
  basiclti/basiclti-docs/resources/docs/sakai_basiclti_portlet.doc
  basiclti/basiclti-docs/resources/docs/sakai_basiclti_provider.doc
  basiclti/basiclti-docs/resources/docs/sakai_basiclti_vendor.doc
  basiclti/docs/README.md
Labels: low risk

#7225 SAK-42313 Update commons-collection4 4.4
  master/pom.xml
Labels: low risk

#7231 SAK-42321 - Admin Tools: Improve UI using bootstrap tables.
  admin-tools/src/webapp/vm/sites/chef_sites_edit.vm
  admin-tools/src/webapp/vm/sites/chef_sites_edit_group.vm
  admin-tools/src/webapp/vm/sites/chef_sites_edit_page.vm
  admin-tools/src/webapp/vm/sites/chef_sites_edit_tool.vm
  admin-tools/src/webapp/vm/sites/chef_sites_groups.vm
  admin-tools/src/webapp/vm/sites/chef_sites_page_properties.vm
  admin-tools/src/webapp/vm/sites/chef_sites_pages.vm
  admin-tools/src/webapp/vm/sites/chef_sites_properties.vm
  admin-tools/src/webapp/vm/sites/chef_sites_tool_properties.vm
  admin-tools/src/webapp/vm/sites/chef_sites_tools.vm
Labels: enhancement

#7149 SAK-42190 OneDrive integration with Sakai filepicker
  cloud-storage/README.md
  cloud-storage/onedrive/README.md
  cloud-storage/onedrive/api/pom.xml
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveFile.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveFolder.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveItem.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveItemComparator.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveParent.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveToken.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/model/OneDriveUser.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/repository/OneDriveUserRepository.java
  cloud-storage/onedrive/api/src/java/org/sakaiproject/onedrive/service/OneDriveService.java
  cloud-storage/onedrive/impl/pom.xml
  cloud-storage/onedrive/impl/src/java/org/sakaiproject/onedrive/repository/OneDriveUserRepositoryImpl.java
  cloud-storage/onedrive/impl/src/java/org/sakaiproject/onedrive/service/OneDriveServiceImpl.java
  cloud-storage/onedrive/impl/src/java/org/sakaiproject/onedrive/util/HTTPConnectionUtil.java
  cloud-storage/onedrive/impl/src/webapp/WEB-INF/components.xml
  cloud-storage/onedrive/pom.xml
  cloud-storage/onedrive/tool/pom.xml
  cloud-storage/onedrive/tool/src/main/java/org/sakaiproject/onedrive/ThymeleafConfig.java
  cloud-storage/onedrive/tool/src/main/java/org/sakaiproject/onedrive/WebAppConfiguration.java
  cloud-storage/onedrive/tool/src/main/java/org/sakaiproject/onedrive/tool/MainController.java
  cloud-storage/onedrive/tool/src/main/resources/Messages.properties
  cloud-storage/onedrive/tool/src/main/webapp/WEB-INF/templates/index.html
  cloud-storage/onedrive/tool/src/main/webapp/WEB-INF/web.xml
  cloud-storage/pom.xml
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  content/content-tool/tool/pom.xml
  content/content-tool/tool/src/bundle/helper.properties
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
  content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
  master/pom.xml
  pom.xml
Labels: enhancement, future, use squash+merge

#7229 SAK-42320 - Admin tools: Better UI to select a tool for a page
  admin-tools/src/bundle/sites.properties
  admin-tools/src/webapp/vm/sites/chef_sites_edit_tool.vm
Labels: enhancement

#7233 SAK-42320 - Admin tools: Fix small JS issue
  admin-tools/src/webapp/vm/sites/chef_sites_edit_tool.vm
Labels: low risk

#7234 SAK-42337 - Name Pronunciation: Save multiple recordings in Safari is…
  profile2/bundle/src/resources/ProfileApplication.properties
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.html
Labels: low risk

#7246 SAK-42352 - CKEditor shopping cart / LTI Advantage
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/tsugi-util/src/java/org/tsugi/basiclti/ContentItem.java
Labels: low risk

#7247 SAK-42353 - Better handling of unlinked tools
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/basiclti-tool/src/webapp/vm/lti_content_insert.vm
Labels: accessibility, low risk

#7253 SAK-42344 - Web Content invalid url displays multiple times on error
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: low risk

#7249 SAK-42358 Update commons-codec 1.3
  common/pom.xml
  master/pom.xml
Labels: low risk

#7250 SAK-42359 Update Search tool: jmock 1.2.0, cglib 3.3.0
  search/search-tool/tool/pom.xml
Labels: low risk

#7251 SAK-42360 - Term manager has wrong parent in pom
  site/term-manager/pom.xml
Labels: BLOCKER, low risk

#7239 SAK-42346: Site Info > Manage Participants > Printable Version > NoSuchMethodError runtime exception
  site-manage/site-manage-tool/tool/pom.xml
Labels: for discussion

#7264 SAK-40282: Content - multiselect has been implemented
  content/content-bundles/resources/types.properties
  content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
Labels: enhancement

#7235 SAK-40281 Announcements: Better UI to assign groups
  announcement/announcement-tool/tool/src/bundle/announcement.properties
  announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
  library/src/morpheus-master/sass/modules/tool/announcements/_announcements.scss
Labels: enhancement

#7265 SAK-42190 - Missing translation key
  cloud-storage/onedrive/tool/src/main/webapp/WEB-INF/templates/index.html
Labels: low risk

#7269 SAK-42269 - Allow Lessons launches use then comment extension
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Labels: low risk

#7271 SAK-42379 - Reload page after coming back from "Manage External Tools"
  lessonbuilder/tool/src/webapp/templates/BltiPicker.html
Labels: low risk

#7268 SAK-42338 - New Gateway for Sakai 20
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
  library/src/webapp/content/gateway/about.html
  library/src/webapp/content/gateway/about_mn.html
  library/src/webapp/content/gateway/acknowledgements.html
  library/src/webapp/content/gateway/acknowledgements_images/apache.png
  library/src/webapp/content/gateway/acknowledgements_images/awesomplete.png
  library/src/webapp/content/gateway/acknowledgements_images/basiclti.PNG
  library/src/webapp/content/gateway/acknowledgements_images/bootstrap.png
  library/src/webapp/content/gateway/acknowledgements_images/ckeditor.png
  library/src/webapp/content/gateway/acknowledgements_images/codemirror.png
  library/src/webapp/content/gateway/acknowledgements_images/cropper.png
  library/src/webapp/content/gateway/acknowledgements_images/datatables.png
  library/src/webapp/content/gateway/acknowledgements_images/dom4j.jpg
  library/src/webapp/content/gateway/acknowledgements_images/dropzone.png
  library/src/webapp/content/gateway/acknowledgements_images/elfinder.png
  library/src/webapp/content/gateway/acknowledgements_images/famfamfam.png
  library/src/webapp/content/gateway/acknowledgements_images/featherlight.png
  library/src/webapp/content/gateway/acknowledgements_images/fontawesome.png
  library/src/webapp/content/gateway/acknowledgements_images/fullcalendar.png
  library/src/webapp/content/gateway/acknowledgements_images/handlebars.png
  library/src/webapp/content/gateway/acknowledgements_images/jdom.png
  library/src/webapp/content/gateway/acknowledgements_images/jodatime.png
  library/src/webapp/content/gateway/acknowledgements_images/jquery.jpg
  library/src/webapp/content/gateway/acknowledgements_images/jsmath.png
  library/src/webapp/content/gateway/acknowledgements_images/jsonpath.png
  library/src/webapp/content/gateway/acknowledgements_images/jsoup.png
  library/src/webapp/content/gateway/acknowledgements_images/lombok.png
  library/src/webapp/content/gateway/acknowledgements_images/mathjs.png
  library/src/webapp/content/gateway/acknowledgements_images/mockito.png
  library/src/webapp/content/gateway/acknowledgements_images/momentjs.png
  library/src/webapp/content/gateway/acknowledgements_images/openscv.png
  library/src/webapp/content/gateway/acknowledgements_images/placeholder.png
  library/src/webapp/content/gateway/acknowledgements_images/pnotify.png
  library/src/webapp/content/gateway/acknowledgements_images/powermock.png
  library/src/webapp/content/gateway/acknowledgements_images/qtip2.png
  library/src/webapp/content/gateway/acknowledgements_images/quartz.png
  library/src/webapp/content/gateway/acknowledgements_images/recordrtc.png
  library/src/webapp/content/gateway/acknowledgements_images/sakaic.jpg
  library/src/webapp/content/gateway/acknowledgements_images/select2.png
  library/src/webapp/content/gateway/acknowledgements_images/simple-xml.png
  library/src/webapp/content/gateway/acknowledgements_images/slf4j.png
  library/src/webapp/content/gateway/acknowledgements_images/spring.png
  library/src/webapp/content/gateway/acknowledgements_images/urlrewritefilter.png
  library/src/webapp/content/gateway/acknowledgements_images/webjars.png
  library/src/webapp/content/gateway/acknowledgements_images/webrtc.png
  library/src/webapp/content/gateway/acknowledgements_images/weld.png
  library/src/webapp/content/gateway/acknowledgments.html
  library/src/webapp/content/gateway/acknowledgments_mn.html
  library/src/webapp/content/gateway/features.html
  library/src/webapp/content/gateway/features_mn.html
  library/src/webapp/content/gateway/training.html
  library/src/webapp/content/gateway/training_mn.html
  library/src/webapp/content/server_info.html
Labels: enhancement, future

#7303 SAK-42338 - Better images for the Acknowledgements page
  library/src/webapp/content/gateway/acknowledgements_images/fullcalendar.png
  library/src/webapp/content/gateway/acknowledgements_images/pnotify.png
  library/src/webapp/content/gateway/acknowledgements_images/simple-xml.png
Labels: low risk

#7288 SAK-42400 - Samigo: Restrict Students' feedback by date and score
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/AssessmentAccessControlIfc.java
  samigo/samigo-api/src/java/xml/author/v1p2/assessmentTemplate.xml
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBeanie.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SettingsDeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
  samigo/samigo-app/src/test/data/realizedAssessment.xml
  samigo/samigo-app/src/test/data/sample12Assessment.xml
  samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/ui/listener/FakeBeginDeliveryActionListener.java
  samigo/samigo-app/src/webapp/js/authoring.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentAccessControl.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBase.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAccessControl.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/assessment/AssessmentHelperBase.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: enhancement, future

#7307 SAK-42422 Update Apache commons-compress 1.19
  common/pom.xml
Labels: low risk

#7297 SAK-42408 Admin Tools: UI improvements for the users tool
  admin-tools/src/bundle/users.properties
  admin-tools/src/webapp/css/sakai-user-tool.css
  admin-tools/src/webapp/vm/user/chef_users_create.vm
  admin-tools/src/webapp/vm/user/chef_users_edit.vm
  admin-tools/src/webapp/vm/user/chef_users_view.vm
Labels: enhancement, future
