Repository sakaiproject/sakai, pull requests merged in 2019-06, with the labels that each got.

#6970 SAK-41690 Messages / Role issue when site language is set to Spanish …
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es_MX.properties
Labels: L10N

#7023 SAK-41939 SiteStats: Delete pom.xml commons-pool
  sitestats/sitestats-impl/pom.xml
Labels: low risk

#6930 SAK-41384 Single groups users now show group in roster
  roster2/tool/src/webapp/js/roster.js
Labels: low risk, work in progress

#7048 SAK-41952 - Forums/{Forum Title}/TopicSettings: customize buttons do …
  msgcntr/messageforums-app/src/webapp/js/permissions_header.js
Labels: accessibility

#7038 SAK-41985 accesskey c is reserved for the portal 'jump to content'
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/permissions/addGroupsUsers.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podAdd.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podDelete.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podFeedRevise.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podOptions.jsp
  podcasts/podcasts-app/src/webapp/podcasts/podRevise.jsp
  syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
Labels: accessibility

#7050 SAK-41998: Update spanish translations
  assignment/bundles/resources/assignment-noti-prefs_es.properties
  assignment/bundles/resources/assignment_es.properties
  basiclti/basiclti-blis/src/bundle/blis_es.properties
  basiclti/basiclti-impl/src/bundle/basicltisvc_es.properties
  basiclti/basiclti-impl/src/bundle/ltiservice_es.properties
  basiclti/basiclti-oidc/src/bundle/oidc_es.properties
  basiclti/basiclti-portlet/src/bundle/basiclti_es.properties
  basiclti/basiclti-tool/src/bundle/ltitool_es.properties
  chat/chat-tool/tool/src/bundle/chat_es.properties
  commons/api/src/bundle/org/sakaiproject/commons/bundle/Messages_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content_type/content_type_names_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  content/content-bundles/resources/content_es.properties
  content/content-bundles/resources/types_es.properties
  content/content-tool/tool/src/bundle/dropbox_es.properties
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/DelegatedAccessApplication_es.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
  jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/logmessage/Messages_es.properties
  lessonbuilder/tool/src/resources/messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  polls/impl/src/bundle/notifyDeletedOption_es.properties
  portal/portal-impl/impl/src/bundle/bullhorns_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  postem/postem-app/src/bundle/org/sakaiproject/tool/postem/bundle/Messages_es.properties
  profile2/bundle/src/resources/ProfileApplication_es.properties
  roster2/bundle/src/bundle/org/sakaiproject/roster/bundle/Messages_es.properties
  rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages_es.properties
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages_es.properties
  rwiki/rwiki-util/radeox/src/bundle/org/radeox/Messages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/MainIndexMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/TemplateMessages_es.properties
  sections/sections-app-util/src/bundle/sections_es.properties
  signup/tool/src/bundle/messages_es.properties
  site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  sitestats/sitestats-bundle/src/resources/Events_es.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
  sitestats/sitestats-bundle/src/resources/Navigator_es.properties
  syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages_es.properties
  webcomponents/src/main/bundle/org/sakaiproject/webcomponents/permissions/bundle/Messages_es.properties
Labels: I18N, translation

#7043 SAK-41898 - Error saving T&Q responses for other questions after nume…
  library/pom.xml
  library/src/webapp/js/headscripts.js
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fa_IR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fr_FR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_hi_IN.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ja.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_mn.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_pt_BR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_tr_TR.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_zh_CN.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/validator/FinResponseValidator.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: use squash+merge

#7066 SAK-42031 sections-service: TimeService => UserTimeService
  edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseSectionImpl.java
Labels: low risk

#7067 SAK-41974: property name change in documentation
  sitestats/server_wide_stats.md
Labels: low risk
