Repository sakaiproject/sakai, pull requests merged in 2020-09, with the labels that each got.

#8510 SAK-44206 Admin SU: cover => api
  admin-su/src/java/org/sakaiproject/tool/su/SuTool.java
Labels: low risk

#8509 SAK-44099: make some wicket links bookmarkable
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/DelegatedAccessApplication.java
  delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/BasePage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
Labels: low risk

#8512 SAK-44208 - Provide resorceLinkId with lineItems
  basiclti/basiclti-common/src/java/org/sakaiproject/lti13/LineItemUtil.java
Labels: low risk

#8524 SAK-44222 update Apache commons-codec 1.15
  master/pom.xml
Labels: low risk

#7663 SAK-42874 T&Qs remove 'copy from pool' option inside pool menu
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/selectQuestionType.jsp
Labels: use squash+merge

#8553 SAK-44150: samigo > further qualify copy to clipboard button label for screen readers
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Labels: accessibility, low risk

#8617 SAK-44347 Kernel: Validator.escapeHtml, Web.escapeHtml => FormattedText
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/HtmlPageFilter.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
  kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml
Labels: low risk
