Repository sakaiproject/sakai, pull requests merged in 2020-04, with the labels that each got.

#8123 SAK-43517 - Lessons: Serious performance loss in lessons in sites wit…
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
Labels: BLOCKER

#8122 SAK-31477: Manage Tools: News tool has two underscores in the id
  site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Labels: low risk

#8125 SAK-43525 Update commons-lang3 3.10
  master/pom.xml
Labels: future

#8120 SAK-43513 Update Spotbugs 4.0.1
  master/pom.xml
Labels: future, low risk

#8129 SAK-43530 Update JMock 2.12.0
  citations/citations-impl/impl/pom.xml
  providers/unboundid/pom.xml
Labels: future

#8138 SAK-43290 - Lessons, accessibility: Edit options cannot be accessed v…
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
Labels: accessibility

#8148 SAK-43512 - Tests & Quizzes: Cannot enter '+' '{' 'i' to represent co…
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
Labels: BLOCKER

#7926 SAK-43061 Add delete column to bulk edit modal in gbng
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.java
  gradebookng/tool/src/webapp/scripts/gradebook-bulk-edit.js
Labels: future

#8142 SAK-43533 - Site Info > Manage Groups: Auto-Groups Creation Wizard - …
  library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss
  site-manage/site-group-manager/src/main/resources/Messages.properties
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html
Labels: use squash+merge

#8145 SAK-43535 - Site Info > Manage Groups: Auto-Groups Creation Wizard - …
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/AutoGroupsController.java
  site-manage/site-group-manager/src/main/resources/Messages.properties
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html
Labels: use squash+merge

#8160 SAK-43571 Update opencsv 5.1
  master/pom.xml
Labels: low risk

#8165 SAK-43577 Update iCal4j 3.0.18
  master/pom.xml
Labels: low risk

#8169 SAK-43580 - Site Info > Manage Groups > Create Group > no longer able…
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/GroupController.java
  site-manage/site-group-manager/src/main/resources/Messages.properties
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html
Labels: BLOCKER

#8177 SAK-42641 Sitemanage: Rubrics deleted in soft deletion
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: BLOCKER
