Repository sakaiproject/sakai, pull requests merged in 2020-07, with the labels that each got.

#8346 SAK-42491 - Trim text fields in the Foorm layer
  basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
Labels: low risk

#8347 SAK-43889 - Make it clearer which placements work together.
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
  basiclti/basiclti-impl/src/bundle/ltiservice.properties
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
Labels: low risk

#8350 SAK-43886 - Add copy buttons to LTI 1.3 values
  basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_view.vm
  library/src/webapp/js/headscripts.js
Labels: accessibility, low risk

#8351 SAK-43887 - Change wording on "Add Learning App" page
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/BltiPickerProducer.java
  lessonbuilder/tool/src/resources/messages.properties
Labels: low risk

#8352 SAK-43885 - Add a LTI 1.3 data screen
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_post_insert.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_view.vm
Labels: low risk

#8363 SAK-43935 Update embedded-ldap-junit 0.8.1
  providers/unboundid/pom.xml
Labels: low risk

#8362 SAK-43933 Update Plugin spotbugs & extra-enforcer-rules
  master/pom.xml
Labels: low risk

#8374 SAK-43891 - Add family and given names to NRPS response
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
Labels: low risk

#8375 SAK-43892 - Use URNs for roles in NRPS
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13ConstantsUtil.java
  basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
Labels: low risk

#8377 SAK-43893 - Handle null grade semantics
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Labels: low risk

#8384 SAK-43980 - Auto close dialog
  basiclti/basiclti-tool/src/webapp/vm/lti_editor_done.vm
Labels: low risk

#8390 SAK-44000 - Make key pattern in hasAssociatedRubricMap consistent
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Labels: GradebookNG, priority

#8408 SAK-32679 - Refactor / Cleanup / Prepare for Assignments LTI
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-common/src/java/org/sakaiproject/lti13/LineItemUtil.java
  basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiBLTIUtilTest.java
  basiclti/basiclti-impl/src/bundle/ltiservice.properties
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
  basiclti/basiclti-tool/src/bundle/ltitool.properties
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
  basiclti/basiclti-tool/src/webapp/vm/lti_assignment_return.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_content_config.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_editor_select.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
  basiclti/tsugi-util/src/java/org/tsugi/basiclti/ContentItem.java
  basiclti/web-ifp/src/bundle/vm/main.vm
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
Labels: ready to test

#8416 SAK-43709 - Change length of keyset_url and remove tool_kid
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
Labels: low risk
