Repository sakaiproject/sakai, pull requests merged in 2020-03, with the labels that each got.

#7959 SAK-43314: site info > manage participants > show/hide credits column dynamically
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
Labels: for discussion

#7967 SAK-43363 SimpleBindRequest => BindRequest
  providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java
Labels: low risk

#7981 SAK-43388 - WebJars: Upgrade codemirror from 5.50.2 to 5.52.0
  library/pom.xml
  library/src/webapp/editor/elfinder/sakai/js/src/editors.js
Labels: future

#8030 SAK-43415 Samigo : Assessments should be the first tab
  samigo/samigo-app/src/webapp/jsf/author/allHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/assessmentHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/editAssessmentHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/restoreAssessmentsHeading.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/evaluationHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/event/eventLogHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/questionpoolHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivityHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/template/templateHeadings.jsp
Labels: future

#8028 SAK-43435 Profile2: fix texts next to icons
  profile2/tool/src/webapp/css/profile2.css
Labels: future

#7984 SAK-43386 - Webjars: CKEDITOR IMAGE2 plugin. Update to 4.14.0
  library/pom.xml
  master/pom.xml
Labels: future

#7982 SAK-43387 - WebJars: Upgrade elfinder from 2.1.50 to 2.1.53
  library/pom.xml
  library/src/webapp/editor/elfinder/sakai/elfinder.html
Labels: future

#8053 SAK-41936 - SignUp/Meeting Summary : 'Show the other default settings…
  signup/tool/src/webapp/signup/newMeeting/step2.jsp
Labels: accessibility

#8058 SAK-43461 - Assignments: Download All, Upload File, Release grade Lin…
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
Labels: BLOCKER

#8044 SAK-41937 - Forum Settings Error - Alert message
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
Labels: accessibility

#8063 SAK-41971 Resources/Upload Files/Copyright Status Combo Box Form labe…
  content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
Labels: accessibility

#8064 SAK-41964 - Tests&Quizzes: Edit Question form fields are not associat…
  samigo/samigo-app/src/java/com/corejsf/UploadRenderer.java
  samigo/samigo-app/src/java/org/sakaiproject/jsf/renderer/RichTextEditArea.java
  samigo/samigo-app/src/webapp/jsf/author/item/audioRecording.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/extendedMatchingItems.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/shortAnswer.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
Labels: accessibility

#8002 SAK-43377 - Centralize some kernel comparators for sorting consistency.
  admin-tools/src/java/org/sakaiproject/site/tool/AdminSitesAction.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/sort/UserComparator.java
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/ListItem.java
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/AliasCreatedTimeComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/AliasIdComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/AuthzGroupIdComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/GroupTitleComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/ResourceTypeLabelComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/RoleIdComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/ToolTitleComparator.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/UserSortNameComparator.java
  lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/ccexport/Assignment2Export.java
  lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/Assignment2Entity.java
  lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/MnemeEntity.java
  lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/ScormEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/CommentGradingPaneProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  mailsender/impl/src/java/org/sakaiproject/mailsender/logic/impl/ComposeLogicImpl.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/AuthzGroupComparator.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/GroupComparator.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
  portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/SiteNeighbourhoodServiceImpl.java
  site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/GroupController.java
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/MainController.java
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/util/UserComparator.java
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/JoinableSiteSettings.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/ParticipantFilterHandler.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
  site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/ToolComparator.java
Labels: future

#7883 SAK-43213 msgcntr: components.xml
  msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
Labels: future

#8085 SAK-43479 Profile2: Deprecated utils.FormattedText => api.FormattedText
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/AddFriend.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/ConfirmFriend.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/IgnoreFriend.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/RemoveFriend.java
  profile2/util/pom.xml
  profile2/util/src/java/org/sakaiproject/profile2/util/ProfileUtils.java
Labels: future

#7842 SAK-40892: Nested SqlService calls can lead to pool connection deadlock under certain conditions
  kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
Labels: for discussion

#8027 SAK-42643 - Switching from fonticonpicker to fontawesome-iconpicker f…
  basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
  basiclti/basiclti-portlet/src/webapp/edit.jsp
  basiclti/basiclti-tool/src/webapp/vm/lti_content_config.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_content_insert.vm
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
  basiclti/web-ifp/src/bundle/vm/edit.vm
  library/pom.xml
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/iconpicker.eot
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/iconpicker.svg
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/iconpicker.ttf
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/iconpicker.woff
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/jquery.fonticonpicker.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/css/jquery.fonticonpicker.min.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/demo.html
  library/src/webapp/js/fontIconPicker/2.0.1-cs/icons.json
  library/src/webapp/js/fontIconPicker/2.0.1-cs/jquery.fonticonpicker.js
  library/src/webapp/js/fontIconPicker/2.0.1-cs/jquery.fonticonpicker.min.js
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/bootstrap-theme/jquery.fonticonpicker.bootstrap.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/bootstrap-theme/jquery.fonticonpicker.bootstrap.min.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/dark-grey-theme/jquery.fonticonpicker.darkgrey.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/dark-grey-theme/jquery.fonticonpicker.darkgrey.min.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/grey-theme/jquery.fonticonpicker.grey.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/grey-theme/jquery.fonticonpicker.grey.min.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/inverted-theme/jquery.fonticonpicker.inverted.css
  library/src/webapp/js/fontIconPicker/2.0.1-cs/themes/inverted-theme/jquery.fonticonpicker.inverted.min.css
  library/src/webapp/js/fontIconPicker/README.md
  library/src/webapp/js/headscripts.js
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm
  web/web-portlet/src/bundle/vm/edit.vm
Labels: future, work in progress
