Repository sakaiproject/sakai, pull requests merged in 2020-02, with the labels that each got.

#7861 NOJIRA java.net.URLEncode => java.net.URLEncoder
  kernel/api/src/main/java/org/sakaiproject/util/api/FormattedText.java
  kernel/kernel-util/src/main/java/org/sakaiproject/util/Validator.java
Labels: low risk

#7889 SAK-43223 - New Assignments - Add due date to Calendar should be checked by default
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: use squash+merge

#7892 SAK-37753 Fix assignment complete checks in lessons
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonSubmission.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
  lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
Labels: work in progress

#7893 SAK-43233: Resources > enforce copyright selection for URLs on create if required
  content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm
Labels: low risk
