Repository sakaiproject/sakai, pull requests merged in 2020-05, with the labels that each got.

#7998 SAK-39989 Sitestats unit test modernization
  sitestats/pom.xml
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/SitePresenceTotal.java
  sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/SitePresenceTotalImpl.java
  sitestats/sitestats-impl/pom.xml
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/DBHelper.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/SiteStatsPersistenceConfig.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAuthzImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventRegistryServiceImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/detailed/DetailedEventsManagerImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportDefEntityProducer.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
  sitestats/sitestats-impl/src/test/ehcache.xml
  sitestats/sitestats-impl/src/test/fake-services.xml
  sitestats/sitestats-impl/src/test/hibernate-beans.xml
  sitestats/sitestats-impl/src/test/hibernate-test.xml
  sitestats/sitestats-impl/src/test/log4j.properties
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/DB.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/DBImpl.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/EventAggregatorTestPerf.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/ReportManagerTest.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/SiteStatsTestConfiguration.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsManagerTest.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/data/FakeData.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeAliasService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeEntityManager.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeEventRegistryService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeEventTrackingService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakePlacement.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeResourceProperties.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeServerConfigurationService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeSession.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeSessionManager.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeStatsManager.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeTool.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeToolManager.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeUser.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeUserDirectoryService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/EventAggregatorTestPerf.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/StatsUpdateManagerTestPerf.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockEventRegistryService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockSite.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockSiteService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockStatsManager.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockUsageSessionService.java
  sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/StubUtils.java
  sitestats/sitestats-impl/src/test/test-classes.xml
  sitestats/sitestats-impl/src/test/test-sakai.properties
  sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
Labels: future

#8186 SAK-43597 Time => Instant; Validator => FormattedText
  site-manage/datemanager/Instant
  site-manage/datemanager/api/src/java/org/sakaiproject/datemanager/api/DateManagerService.java
  site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
  site-manage/datemanager/impl/src/webapp/WEB-INF/components.xml
Labels: future

#8140 SAK-43551 Deprecated: import org.mockito.runners.MockitoJUnitRunner;
  jobscheduler/scheduler-component-shared/src/test/java/org/sakaiproject/component/app/scheduler/ScheduledInvocationTest.java
  kernel/api/src/test/java/org/sakaiproject/util/ToolListenerTest.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/authz/impl/SakaiSecurityTest.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/WrappedContentResourceTest.java
  mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java
  mailsender/api/src/test/org/sakaiproject/mailsender/AttachmentExceptionTest.java
  mailsender/api/src/test/org/sakaiproject/mailsender/MailsenderExceptionTest.java
  mailsender/api/src/test/org/sakaiproject/mailsender/model/ConfigEntryTest.java
  mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ComposeLogicImplTest.java
  mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ConfigLogicImplTest.java
  mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ExternalLogicImplTest.java
  master/pom.xml
  providers/cm-authz-provider/test/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProviderTest.java
  search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
  textarea/elfinder-sakai/src/test/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactoryTest.java
Labels: future

#8114 SAK-43504 Rwiki: Deprecated utils.FormattedText => api.FormattedText
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/ExcludeEscapeHtmlReference.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
Labels: future

#8102 SAK-43493 Search: Deprecated utils.FormattedText => api.FormattedTex
  search/search-tool/tool/src/java/org/sakaiproject/search/tool/OpenSearchBeanImpl.java
  search/search-tool/tool/src/java/org/sakaiproject/search/tool/SearchAdminBeanImpl.java
  search/search-tool/tool/src/java/org/sakaiproject/search/tool/SearchBeanImpl.java
  search/search-tool/tool/src/java/org/sakaiproject/search/tool/SherlockSearchBeanImpl.java
Labels: future

#7834 SAK-43113 Clean up ItemGradingData in Samigo
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Labels: future

#8192 SAK-43583 - Samigo > Retracted Warning Message Out of Date
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages.properties
Labels: L10N, use squash+merge

#8209 NOJIRA delete //import org.sakaiproject.util.FormattedText;
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
Labels: low risk

#8210 SAK-43630 Assignment test: Deprecated utils.FormattedText => api.Form…
  assignment/tool/src/test/org/sakaiproject/assignment/tool/AssignmentActionTestTools.java
Labels: low risk

#8212 SAK-43635 Profile2: update jar & plugins
  profile2/pom.xml
  profile2/tool/pom.xml
Labels: low risk

#8213 SAK-43636 Update Spotbugs 4.0.2
  master/pom.xml
Labels: low risk

#8222 SAK-43651 Update Rome 1.12.2
  podcasts/podcasts-impl/pom.xml
  simple-rss-portlet/pom.xml
Labels: low risk

#8226 SAK-43660 Make portal search honour seach.enable
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
Labels: low risk

#8231 SAK-43665 Update Apache jclouds 2.2.1
  cloud-content/impl/pom.xml
Labels: low risk

#6664 SAK-41505 Added direct memberships to GB sections columns
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
  gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
Labels: for discussion

#8252 SAK-43708 JFreeChart 1.5.0
  sitestats/pom.xml
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/ServerWideReportManagerImpl.java
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/chart/ChartServiceImpl.java
Labels: update commit message when merging
