Repository sakaiproject/sakai, pull requests merged in 2021-06, with the labels that each got.

#9295 SAK-45075 lessons - fix subpage renaming
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
Labels: use rebase+merge

#9172 SAK-44703: Samigo calculated questions do not evaluate large E expressions correctly
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
Labels: Unit Test Required

#9313 SAK-45565 - Rename MySQL8 reserved words
  kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java
  lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/simplepagegroup.hbm.xml
Labels: BLOCKER, use squash+merge

#8776 SAK-43640 T&Q: Style retract message
  library/src/morpheus-master/sass/base/_extendables.scss
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Labels: work in progress

#9357 SAK-45612 Citation: Deprecated Time
  citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
Labels: low risk

#9356 SAK-45611 Podcasts: Deprecated Time: GroupAwareEntity.getReleaseDate(…
  podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/BasicPodfeedService.java
Labels: low risk

#9349 SAK-40330 Assignment Allow TA with grade to update submission
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
Labels: BLOCKER

#9351 SAK-44985 Discussions topic and forum cache invalidation
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/DiscussionForumManager.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/UIPermissionsManager.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
  msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
Labels: BLOCKER

#9365 SAK-45628 site info > don't remove stealthed lti tools when manage tools list is edited
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge

#9370 SAK-45640 Mail archive: Validator.escapeHtml( => formattedText.escape…
  mailarchive/mailarchive-tool/tool/src/java/org/sakaiproject/mailarchive/entityprovider/MailArchiveEntityProvider.java
  mailarchive/mailarchive-tool/tool/src/webapp/WEB-INF/applicationContext.xml
Labels: low risk

#9374 SAK-45628 NPE protection
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: use rebase+merge

#9378 SAK-45649 Taggable: cover, Validator
  taggable/taggable-api/api/src/java/org/sakaiproject/taggable/api/TaggingManager.java
  taggable/taggable-impl/impl/src/java/org/sakaiproject/taggable/impl/TagImpl.java
  taggable/taggable-impl/impl/src/java/org/sakaiproject/taggable/impl/TaggingManagerImpl.java
  taggable/taggable-impl/impl/src/webapp/WEB-INF/components.xml
Labels: low risk

#9390 SAK-45565 - Lessons: GROUP is a MySQL8 reserved word
  lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/simplepageitem.hbm.xml
Labels: BLOCKER

#9399 SAK-45666 Samigo Statistics NumberFormatException parsing assessment id
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: BLOCKER

#9369 SAK-45655 content-metadata: organize Imports
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/logic/MetadataServiceAggregator.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/logic/MetadataServiceDublinCore.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/logic/MetadataServiceFromContent.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/logic/MetadataServiceLOM.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/BooleanMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/DurationMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/EnumMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/GroupMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/NumberMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/StringMetadataType.java
  content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/UserMetadataType.java
Labels: low risk

#9398 SAK-45674 - Calendar: Replace UI by fullcalendar
  calendar/calendar-bundles/resources/calendar.properties
  calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
  calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js
  calendar/calendar-tool/tool/src/webapp/vm/calendar/calendar_macros.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_view.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewDay.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewList.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewMonth.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewWeek.vm
  calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewYear.vm
  lessonbuilder/tool/src/webapp/js/lessons-calendar.js
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  library/pom.xml
Labels: use squash+merge
