Repository sakaiproject/sakai, pull requests merged in 2021-07, with the labels that each got.

#9207 SAK-45410 Rewrite the 'Email Template Tool UI' from RSF to Thymeleaf.
  emailtemplateservice/api/src/java/org/sakaiproject/emailtemplateservice/service/EmailTemplateService.java
  emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
  emailtemplateservice/tool/pom.xml
  emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/handler/ModifyEmailHandler.java
  emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/locators/EmailTemplateLocator.java
  emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/params/EmailTemplateViewParams.java
  emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/producers/MainViewProducer.java
  emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/producers/ModifyEmailProducer.java
  emailtemplateservice/tool/src/main/java/org/sakaiproject/emailtemplateservice/config/ThymeleafConfig.java
  emailtemplateservice/tool/src/main/java/org/sakaiproject/emailtemplateservice/config/WebAppConfiguration.java
  emailtemplateservice/tool/src/main/java/org/sakaiproject/emailtemplateservice/constants/EmailTemplateConstants.java
  emailtemplateservice/tool/src/main/java/org/sakaiproject/emailtemplateservice/controller/MainController.java
  emailtemplateservice/tool/src/main/resources/messages.properties
  emailtemplateservice/tool/src/main/resources/messages_ar.properties
  emailtemplateservice/tool/src/main/resources/messages_ca.properties
  emailtemplateservice/tool/src/main/resources/messages_de_DE.properties
  emailtemplateservice/tool/src/main/resources/messages_es.properties
  emailtemplateservice/tool/src/main/resources/messages_eu.properties
  emailtemplateservice/tool/src/main/resources/messages_fa_IR.properties
  emailtemplateservice/tool/src/main/resources/messages_fr_FR.properties
  emailtemplateservice/tool/src/main/resources/messages_hi_IN.properties
  emailtemplateservice/tool/src/main/resources/messages_ja.properties
  emailtemplateservice/tool/src/main/resources/messages_mn.properties
  emailtemplateservice/tool/src/main/resources/messages_pt_BR.properties
  emailtemplateservice/tool/src/main/resources/messages_sv.properties
  emailtemplateservice/tool/src/main/resources/messages_tr_TR.properties
  emailtemplateservice/tool/src/main/resources/messages_zh_CN.properties
  emailtemplateservice/tool/src/main/webapp/WEB-INF/templates/fragments/common.html
  emailtemplateservice/tool/src/main/webapp/WEB-INF/templates/fragments/menus.html
  emailtemplateservice/tool/src/main/webapp/WEB-INF/templates/index.html
  emailtemplateservice/tool/src/main/webapp/WEB-INF/templates/modify_email.html
  emailtemplateservice/tool/src/main/webapp/WEB-INF/web.xml
  emailtemplateservice/tool/src/main/webapp/tools/sakai.emailtemplateservice.xml
  emailtemplateservice/tool/src/webapp/WEB-INF/applicationContext.xml
  emailtemplateservice/tool/src/webapp/WEB-INF/requestContext.xml
  emailtemplateservice/tool/src/webapp/WEB-INF/web.xml
  emailtemplateservice/tool/src/webapp/css/Emailtemplateservice.css
  emailtemplateservice/tool/src/webapp/templates/main.html
  emailtemplateservice/tool/src/webapp/templates/modify_email.html
  emailtemplateservice/tool/src/webapp/templates/preview_email.html
  library/src/morpheus-master/sass/modules/tool/emailtemplates/_emailtemplates.scss
  library/src/morpheus-master/sass/tool.scss
Labels: future

#9451 SAK-45792 SiteStat: delete wicket-datetime
  sitestats/sitestats-tool/pom.xml
Labels: low risk

#9452 SAK-45793 Update ical4j 3.0.28
  master/pom.xml
Labels: low risk

#9474 SAK-45838 Update opencsv 5.5.1
  master/pom.xml
Labels: low risk

#9489 SAK-45870 Update Jericho-html 3.4
  mailsender/impl/pom.xml
  samigo/samigo-impl/pom.xml
Labels: low risk

#9491 SAK-45881 Chat index: MissingResourceException
  chat/chat-api/api/src/bundle/chat.properties
  chat/chat-api/api/src/bundle/chat_ar.properties
  chat/chat-api/api/src/bundle/chat_ca.properties
  chat/chat-api/api/src/bundle/chat_de_DE.properties
  chat/chat-api/api/src/bundle/chat_es.properties
  chat/chat-api/api/src/bundle/chat_eu.properties
  chat/chat-api/api/src/bundle/chat_fa_IR.properties
  chat/chat-api/api/src/bundle/chat_fr_FR.properties
  chat/chat-api/api/src/bundle/chat_hi_IN.properties
  chat/chat-api/api/src/bundle/chat_ja.properties
  chat/chat-api/api/src/bundle/chat_mn.properties
  chat/chat-api/api/src/bundle/chat_pt_BR.properties
  chat/chat-api/api/src/bundle/chat_sv.properties
  chat/chat-api/api/src/bundle/chat_tr_TR.properties
  chat/chat-api/api/src/bundle/chat_zh_CN.properties
  chat/chat-impl/impl/src/bundle/chat.properties
  chat/chat-impl/impl/src/bundle/chat_ar.properties
  chat/chat-impl/impl/src/bundle/chat_ca.properties
  chat/chat-impl/impl/src/bundle/chat_es.properties
  chat/chat-impl/impl/src/bundle/chat_eu.properties
  chat/chat-impl/impl/src/bundle/chat_fa_IR.properties
  chat/chat-impl/impl/src/bundle/chat_fr_FR.properties
  chat/chat-impl/impl/src/bundle/chat_hi_IN.properties
  chat/chat-impl/impl/src/bundle/chat_ja.properties
  chat/chat-impl/impl/src/bundle/chat_mn.properties
  chat/chat-impl/impl/src/bundle/chat_pt_BR.properties
  chat/chat-impl/impl/src/bundle/chat_sv.properties
  chat/chat-impl/impl/src/bundle/chat_tr_TR.properties
  chat/chat-impl/impl/src/bundle/chat_zh_CN.properties
Labels: I18N
