Repository sakaiproject/sakai, pull requests merged in 2021-09, with the labels that each got.

#9727 SAK-44984 - Group Manager: Remove use of multiselect-two-sides
  library/pom.xml
  site-manage/site-group-manager/src/main/resources/Messages.properties
  site-manage/site-group-manager/src/main/resources/Messages_ar.properties
  site-manage/site-group-manager/src/main/resources/Messages_ca.properties
  site-manage/site-group-manager/src/main/resources/Messages_es.properties
  site-manage/site-group-manager/src/main/resources/Messages_fr_FR.properties
  site-manage/site-group-manager/src/main/resources/Messages_tr_TR.properties
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html
Labels: for discussion

#9732 SAK-46155 Update ical4j 3.1.0
  master/pom.xml
Labels: low risk

#9526 SAK-45944 Add support for IMS key/value store for LTI Tools
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-common/src/java/org/sakaiproject/lti13/util/SakaiLaunchJWT.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
  lessonbuilder/tool/src/webapp/templates/ShowItem.html
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  library/src/webapp/js/sakai-lti-advantage.js
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
Labels: work in progress

#9755 SAK-46174 - Archive admin tool: Give the UI some love.
  admin-tools/src/webapp/vm/archive/chef_archive-batch.vm
  admin-tools/src/webapp/vm/archive/chef_archive-download.vm
  admin-tools/src/webapp/vm/archive/chef_archive.vm
  admin-tools/src/webapp/vm/archive/chef_archive_noaccess.vm
Labels: enhancement

#9757 SAK-46176 - Become user: Apply some styling
  admin-su/src/webapp/su/main.jsp
Labels: enhancement

#9756 SAK-46175 - Memory: Provide some styling
  admin-tools/src/webapp/vm/memory/chef_memory.vm
  admin-tools/src/webapp/vm/memory/chef_memory_noaccess.vm
Labels: enhancement

#9776 SAK-46194 - Fully qualify the Comment object
  edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
Labels: BLOCKER

#9775 SAK-45976 - Lessons > Add Question > Multiple Choice > UI Improvement…
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  lessonbuilder/tool/src/resources/messages.properties
  lessonbuilder/tool/src/webapp/js/show-page.js
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
Labels: enhancement, for discussion

#9815 SAK-46244 Update Jackson Release 2.12.5 & opencsv 5.5.2
  master/pom.xml
Labels: low risk

#9816 SAK-46036 missing msg bundle keys
  content/content-bundles/resources/content.properties
  content/content-bundles/resources/types.properties
Labels: low risk

#9833 SAK-46267: ERROR: org.sakaiproject.lessonbuildertool.service.LessonBuilderEntityProducer.makePage
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Labels: low risk

#9837 SAK-46279: ERROR: ProfileDaoImpl.invalidateCurrentProfileImage invalidateCurrentProfileImage failed. class java.lang.NullPointerException: null
  profile2/impl/src/java/org/sakaiproject/profile2/dao/impl/ProfileDaoImpl.java
Labels: low risk

#9860 SAK-46076 Conversations : remove question mark
  webcomponents/bundle/src/main/bundle/conversations.properties
Labels: low risk

#9487 SAK-45863 Remove use of Static Cover in PublishedAssessmentFacadeQueries
  samigo/samigo-pack/src/webapp/WEB-INF/components.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: low risk

#9539 SAK-45885: samigo, accessibility: Improve text of warning messages to students taking assessments
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
Labels: for discussion
