Repository sakaiproject/sakai, pull requests merged in 2021-04, with the labels that each got.

#9061 SAK-33621 remove Flash fallback in audio recorder, use library for waveform rendering
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  lessonbuilder/tool/src/webapp/templates/OSplayer.swf
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  lessonbuilder/tool/src/webapp/templates/StrobeMediaPlayback.swf
  lessonbuilder/tool/src/webapp/templates/jwflvplayer.swf
  lessonbuilder/tool/src/webapp/templates/swfobject.js
  library/pom.xml
  library/src/webapp/editor/FCKeditor/editor/plugins/movieplayer/movieplayer.js
  library/src/webapp/editor/ckextraplugins/audiorecorder/StrobeMediaPlayback.swf
  library/src/webapp/editor/ckextraplugins/audiorecorder/YouTubePlugin.swf
  library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.css
  library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.html
  library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.js
  library/src/webapp/editor/ckextraplugins/audiorecorder/player_flv_maxi.swf
  library/src/webapp/editor/ckextraplugins/audiorecorder/plugin.js
  library/src/webapp/js/recorder/README.txt
  library/src/webapp/js/recorder/jRecorder.js
  library/src/webapp/js/recorder/jRecorder.swf
  library/src/webapp/js/sakai-recorder.js
  library/src/webapp/js/swfobject/expressInstall.swf
  library/src/webapp/js/swfobject/swfobject.js
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/macros.vm
  rwiki/rwiki-tool/tool/src/webapp/scripts/localstore.swf
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/delivery/item/audioObject.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
Labels: future

#9168 SAK-45335 TermManager Update french translations
  site/term-manager/tool/src/java/org/sakaiproject/acadtermmanage/tool/AcademicSessionAdminApplication_fr_FR.properties
  site/term-manager/tool/src/java/org/sakaiproject/acadtermmanage/tool/pages/SemesterPage_fr_FR.properties
Labels: I18N

#9179 SAK-45360 delegatedaccess, admin-perms-tool: Update Joda-time => java.time
  delegatedaccess/impl/pom.xml
  delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
  site/admin-perms-tool/pom.xml
Labels: low risk

#9188 SAK-45377 Update jsr305 3.0.2
  kernel/kernel-impl/pom.xml
Labels: low risk
