Repository sakaiproject/sakai, pull requests merged in 2021-08, with the labels that each got.

#9509 SAK-45926 Chat: MessageFrom => Chat: Message From
  chat/chat-api/api/src/bundle/chat.properties
  chat/chat-api/api/src/bundle/chat_ar.properties
  chat/chat-api/api/src/bundle/chat_ca.properties
  chat/chat-api/api/src/bundle/chat_es.properties
  chat/chat-api/api/src/bundle/chat_eu.properties
  chat/chat-api/api/src/bundle/chat_fa_IR.properties
  chat/chat-api/api/src/bundle/chat_fr_FR.properties
  chat/chat-api/api/src/bundle/chat_hi_IN.properties
  chat/chat-api/api/src/bundle/chat_ja.properties
  chat/chat-api/api/src/bundle/chat_mn.properties
  chat/chat-api/api/src/bundle/chat_pt_BR.properties
  chat/chat-api/api/src/bundle/chat_sv.properties
  chat/chat-api/api/src/bundle/chat_tr_TR.properties
  chat/chat-api/api/src/bundle/chat_zh_CN.properties
Labels: I18N, low risk

#9519 SAK-45938 Update Passay 1.6.1
  kernel/kernel-impl/pom.xml
Labels: low risk

#9535 SAK-45957 Update Apache Tomcat 9.0.52
  master/pom.xml
Labels: low risk

#9562 SAK-45860 - Portal > Print > Print-out shows "Publish Now" and "Cance…
  library/src/morpheus-master/sass/print.scss
Labels: low risk

#9576 SAK-45893 - Remove cancel for assignments flow.
  basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
Labels: low risk

#9575 SAK-45990 - Restore "Add to Site" checkbox for Admin
  basiclti/basiclti-tool/src/webapp/vm/lti_content_insert.vm
Labels: low risk

#9585 SAK-44845 samigo > ToC and Show Feedback tabs give opportunity to trigger data discrepancy error
  samigo/samigo-app/src/webapp/js/questionProgress.js
  samigo/samigo-app/src/webapp/jsf/delivery/assessmentDeliveryHeading.jsp
Labels: low risk

#9592 SAK-46015 TII webhook logging too verbose
  content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
Labels: low risk

#9584 SAK-46005 samigo > make data discrepancy 'return' link/button text configurable
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/webapp/jsf/delivery/discrepancyInData.jsp
Labels: low risk

#9607 SAK-46027 soft delete warning does not provide info on how to remove yourself from the site
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
Labels: low risk

#9609 SAK-46028 site info > sort section sets alphabetically
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
Labels: low risk

#9613 SAK-46036 resources > better grouping of buttons and email notification component
  content/content-bundles/resources/content.properties
  content/content-bundles/resources/types.properties
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_cwiz_finish.vm
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_properties.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_replace_file.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_revise_html.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_revise_text.vm
  content/content-tool/tool/src/webapp/vm/resources/sakai_revise_url.vm
  library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
Labels: low risk

#9622 SAK-46042 request account's email should indicate the user's login id
  reset-pass/account-validator-impl/src/bundle/validate_requestAccount.xml
Labels: low risk

#9624 SAK-46048 hiding more than 1000 sites breaks in Oracle
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
Labels: use rebase+merge

#9626 SAK-46050 membership > enrolments > rosters attached to multiple sites get squished together
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/EnrolmentsHandler.java
  site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_enrolments.vm
Labels: low risk

#9628 SAK-46051 antisamy > whitelist microsoftstream.com
  kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml
Labels: low risk

#9631 SAK-46055 membership > joinable sites > filter out sites where user is an inactive member
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/JoinableSiteSettings.java
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
Labels: low risk

#9640 SAK-46058: improved language for locked groups
  site-manage/site-group-manager/src/main/resources/Messages.properties
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
Labels: low risk

#9648 SAK-46086 GBNG > export > include student #'s by default
  gradebookng/bundle/src/main/bundle/gradebookng.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Labels: low risk

#9649 SAK-46087 GBNG > import > item selection > no way to select all
  gradebookng/bundle/src/main/bundle/gradebookng.properties
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
  gradebookng/tool/src/webapp/scripts/gradebook-import.js
Labels: low risk

#9659 SAK-46093 GBNG > import > user data loss when navigating backwards through the wizard
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
Labels: use rebase+merge
