Repository sakaiproject/sakai, pull requests merged in 2022-04, with the labels that each got.

#10401 SAK-47117 Gradebook import fails if 2 or more users have the same name with different IDs
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UserIdentificationReport.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUnidentifiedUser.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUserBase.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedRow.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
Labels: BLOCKER

#10350 SAK-47050 Add a Sakai profile popup web component
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThreadBodyInclude.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
  profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
  providers/sample/src/java/org/sakaiproject/provider/user/SampleCandidateDetailProvider.java
  providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
  roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
  roster2/tool/src/webapp/js/roster.js
  webapi/pom.xml
  webapi/src/main/java/org/sakaiproject/webapi/beans/ProfileRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ProfileController.java
  webcomponents/bundle/src/main/bundle/profile.properties
  webcomponents/bundle/src/main/bundle/pronunciation-player.properties
  webcomponents/tool/src/main/frontend/.eslintrc.js
  webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar-create-event.js
  webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar.js
  webcomponents/tool/src/main/frontend/js/conversations/reactions-mixin.js
  webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
  webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
  webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
  webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
  webcomponents/tool/src/main/frontend/js/grader/submission.js
  webcomponents/tool/src/main/frontend/js/imageeditor/sakai-image-editor.js
  webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-item-delete.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-rating-edit.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-list.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
  webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js
  webcomponents/tool/src/main/frontend/js/sakai-icon.js
  webcomponents/tool/src/main/frontend/js/sakai-profile.js
  webcomponents/tool/src/main/frontend/js/sakai-pronunciation-player.js
Labels: future

#10305 SAK-46998 Move datepicker webcomponent to datetime-local
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm
  library/pom.xml
  library/src/webapp/js/headscripts.js
  webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar-create-event.js
  webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar.js
  webcomponents/tool/src/main/frontend/js/datepicker/flatpicker-styles.js
  webcomponents/tool/src/main/frontend/js/datepicker/sakai-date-picker.js
  webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
  webcomponents/tool/src/main/frontend/js/sakai-date-picker.js
  webcomponents/tool/src/main/frontend/js/sakai-portal-utils.js
  webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
  webcomponents/tool/src/main/frontend/package-lock.json
  webcomponents/tool/src/main/frontend/package.json
  webcomponents/tool/src/main/frontend/test/sakai-portal-utils.test.js
Labels: future

#10286 SAK-46436 Add ability for instructors to manually create Tasks that aren't automatically added via tools
  dashboard/tool/src/main/java/org/sakaiproject/dashboard/tool/MainController.java
  dashboard/tool/src/main/webapp/WEB-INF/templates/course_dashboard.html
  kernel/api/src/main/java/org/sakaiproject/tasks/api/AssignationType.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/TaskAssigned.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/TaskService.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/UserTaskAdapterBean.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/repository/TaskAssignedRepository.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/repository/UserTaskRepository.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/repository/TaskAssignedRepositoryImpl.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/repository/UserTaskRepositoryImpl.java
  kernel/kernel-impl/src/main/webapp/WEB-INF/tasks-components.xml
  kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTestConfiguration.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
  webcomponents/bundle/src/main/bundle/tasks.properties
  webcomponents/bundle/src/main/bundle/tasks_es.properties
  webcomponents/tool/src/main/frontend/js/coursedashboard/sakai-course-dashboard.js
  webcomponents/tool/src/main/frontend/js/sakai-editor.js
  webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js
  webcomponents/tool/src/main/frontend/js/sakai-pageable-element.js
  webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
  webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
  webcomponents/tool/src/main/frontend/js/widgets/sakai-tasks-widget.js
  webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-panel.js
Labels: future

#10425 SAK-47158 Assignments > trash doesn't indicate draft status
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
Labels: low risk

#10424 SAK-47157 assignments, samigo > submission page should display EID
  assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/StudentScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  webcomponents/tool/src/main/frontend/js/grader/submission.js
Labels: low risk

#10461 SAK-47199 Assignments > Trash > add spinners on buttons after click
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
Labels: low risk

#10465 SAK-47204 Update default.sakai.properties Oracle driver class name
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: low risk

#10445 SAK-47184 samigo > add messaging when beginning an assessment warning of multiple tab dangers
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
Labels: low risk

#10447 SAK-47185 warn users of the consequences of locking resources
  admin-tools/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
  admin-tools/src/webapp/vm/authz-helper/chef_permissions.vm
  content/content-bundles/resources/content.properties
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
  kernel/api/src/main/java/org/sakaiproject/authz/api/PermissionsHelper.java
  site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages.properties
  site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
Labels: low risk

#10462 SAK-47200 Site Info > Manage Groups > all buttons lack spinners
  library/src/webapp/js/spinner.js
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step1.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import_confirmation.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
  site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
Labels: low risk

#10481 SAK-47225 Samigo > update Data Discrepancy messaging to be more descriptive and accurate
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fr_FR.properties
  samigo/samigo-app/src/webapp/jsf/delivery/discrepancyInData.jsp
Labels: low risk, use rebase+merge

#10480 SAK-47224 Forums > Stats & Grading > EID is not displayed
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsList.jsp
  msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
Labels: low risk

#10422 SAK-47155 assignments > anon peer review > no warning that identity is revealed to instructors
  assignment/api/src/resources/assignment.properties
Labels: low risk
