Repository sakaiproject/sakai, pull requests merged in 2022-08, with the labels that each got.

#10777 SAK-46487 Roster- Card layout does not display on iPhone 6/7/8 & several Android devices
  roster2/tool/src/webapp/js/roster.js
Labels: low risk

#10771 SAK-47649 SITESTATS Avoid NULL when recompiling sitestats
  sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/SitePresenceTotalImpl.java
Labels: BLOCKER

#10792 SAK-47666 Assignments: Grading screen no longer visible
  assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
Labels: BLOCKER

#10764 Removed whitespace before full stop.
  README.md
Labels: cla?
