Repository sakaiproject/sakai, pull requests merged in 2022-05, with the labels that each got.

#10464 SAK-47202 Assignments > history log > time zone format displays offset rather than name
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: low risk

#10423 SAK-47156 Assignments > late status is not communicated to students
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
Labels: low risk

#10389 SAK-46974 MSGCNTR Provide private message scheduling
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/Message.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsTypeManager.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/SynopticMsgcntrManager.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/scheduler/PrivateMessageSchedulerService.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/PrivateMessageManager.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDelete.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgMove.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/topNav.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsTypeManagerImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/SynopticMsgcntrManagerImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/TopicEntityProviderImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/scheduler/PrivateMessageSchedulerServiceImpl.java
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
  msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.java
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/PrivateTopicImpl.java
Labels: future

#10310 SAK-46944 SIGNUP Provide a counter in the forms title
  signup/api/src/java/org/sakaiproject/signup/model/SignupMeeting.java
  signup/api/src/java/org/sakaiproject/signup/model/SignupTimeslot.java
  signup/tool/src/bundle/messages.properties
  signup/tool/src/bundle/messages_es.properties
  signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupMeetingWrapper.java
  signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupSorter.java
  signup/tool/src/java/org/sakaiproject/signup/tool/jsf/TimeslotWrapper.java
  signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/OrganizerSignupMBean.java
  signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
  signup/tool/src/webapp/signup/signupMeetings.jsp
Labels: future

#10546 SAK-47301 Update jfreechart 1.5.3
  sitestats/pom.xml
Labels: low risk

#10554 SAK-38240 Unnecessary optional has been removed
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: enhancement

#10566 SAK-47334 update Apache Commons Imaging 1.0-alpha3
  search/search-impl/impl/pom.xml
Labels: low risk

#10522 SAK-43768 SAMIGO: Randomize question pools with option: A student's questions are randomized once for all submissions
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: use squash+merge

#10582 SAK-47347 Update Jackson Release 2.13.3
  master/pom.xml
Labels: low risk

#10581 SAK-47344 Assignments Style is missing on Trash when the trash is empty
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
Labels: low risk

#10589 SAK-47348: Assignment: Webservice for consulting time in worklog to a task
  assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
Labels: use squash+merge
