Repository sakaiproject/sakai, pull requests merged in 2022-07, with the labels that each got.

#10694 SAK-47499 GB: stacktrace when attempting to set a rule for a TA
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
Labels: BLOCKER

#10711 SAK-47531 GRADEBOOKNG A lot of errors GradeSummaryTablePanel.populateItem Failed to configure rubric button for submission: org.sakaiproject.exception.IdUnusedException
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
Labels: BLOCKER

#10716 SAK-47548 T&Q and Rubrics: Grading a question in Spanish with decimal…
  samigo/samigo-app/src/webapp/js/samigo-global.js
Labels: I18N

#10718 SAK-47550 Admin Users: Performance issues introduced after SAK-47359
  kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
  kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/BaseDbFlatStorage.java
Labels: BLOCKER

#10719 SAK-47552 Admin Users: Student view users are returned by searching u…
  kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/UserServiceSqlDefault.java
Labels: BLOCKER

#10720 SAK-47357 Assignments: Back to list button is missing when student ch…
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: low risk

#10726 SAK-47499 GB stacktrace when attempting to set a rule for a TA
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html
Labels: BLOCKER

#10739 SAK-47573 - Insure the gradebook is initialised
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Labels: BLOCKER

#10731 SAK-47261 - Make NRPS / LineItems URLs context wide
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Labels: work in progress

#10763 SAK-46761 Roster / columns incorrect when using list view and hiding photos
  roster2/tool/src/handlebars/members_container_table.handlebars
Labels: low risk
