Repository sakaiproject/sakai, pull requests merged in 2022-11, with the labels that each got.

#10985 SAK-43542 Assignments: Provide more information in Removed Assignments/Trash list
  assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
  assignment/api/src/resources/assignment.properties
  assignment/api/src/resources/assignment_ca.properties
  assignment/api/src/resources/assignment_es.properties
  assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
Labels: Requires Conversion Script

#10984 SAK-48025 SITESTATS Avoid NULL when creating a report and there are folders from different TAs
  sitestats/sitestats-bundle/src/resources/Messages.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/FileSelectorPanel.java
Labels: low risk

#10964 SAK-47992 Add student special needs information and surface additional info in Roster
  kernel/api/src/main/java/org/sakaiproject/site/api/Site.java
  kernel/api/src/main/java/org/sakaiproject/user/api/CandidateDetailProvider.java
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  library/src/skins/default/src/sass/modules/tool/roster/_roster.scss
  providers/component/src/webapp/WEB-INF/candidate-details.xml
  providers/component/src/webapp/WEB-INF/components-demo.xml
  providers/sample/src/java/org/sakaiproject/provider/user/SampleCandidateDetailProvider.java
  providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
  providers/userdetail/src/java/org/sakaiproject/user/detail/ChainedDetailProvider.java
  providers/userdetail/src/java/org/sakaiproject/user/detail/FallbackDetailProvider.java
  providers/userdetail/src/java/org/sakaiproject/user/detail/MappingDetailProvider.java
  roster2/bundle/src/bundle/roster.properties
  roster2/tool/src/handlebars/additional_info_modal_content.handlebars
  roster2/tool/src/handlebars/members_cards.handlebars
  roster2/tool/src/handlebars/members_container_table.handlebars
  roster2/tool/src/handlebars/members_table.handlebars
  roster2/tool/src/handlebars/modal.handlebars
  roster2/tool/src/handlebars/overview.handlebars
  roster2/tool/src/java/org/sakaiproject/roster/api/RosterFunctions.java
  roster2/tool/src/java/org/sakaiproject/roster/api/RosterMember.java
  roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java
  roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
  roster2/tool/src/java/org/sakaiproject/roster/tool/RosterTool.java
  roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterPOIEntityProvider.java
  roster2/tool/src/webapp/WEB-INF/bootstrap.jsp
  roster2/tool/src/webapp/css/print.css
  roster2/tool/src/webapp/js/roster.js
Labels: accessibility

#10986 SAK-48028 Update Joda-time 2.12.1
  master/pom.xml
Labels: low risk

#10989 SAK-48034 User Properties: Cannot add user properties to external use…
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_user.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_user.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_user.sql
Labels: Requires Conversion Script

#10990 SAK-47879 Tasks add a permission for creating tasks
  kernel/api/src/main/java/org/sakaiproject/tasks/api/TaskPermissions.java
  kernel/api/src/main/java/org/sakaiproject/tasks/api/TaskService.java
  kernel/kernel-impl/pom.xml
  kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  kernel/kernel-impl/src/main/webapp/WEB-INF/tasks-components.xml
  kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTest.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTestConfiguration.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
  webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
Labels: Requires Conversion Script

#9194 SAK-45382 WebDav remove use of static cover
  dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
Labels: work in progress

#11001 SAK-47992 Add setters needed for injection to CDP
  providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
Labels: use squash+merge

#11003 SAK-48068 Assignments - Grader: Incomplete unicode in Spanish translations breaks bundle
  webcomponents/bundle/src/main/bundle/grader_es.properties
Labels: L10N

#11051 SAK-48085 - Extend Role Mapping for LTI Launches, NRPS Data, and Providers
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIRoleMapper.java
  basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/SiteMembershipUpdater.java
  basiclti/basiclti-blis/pom.xml
  basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiBLTIUtilTest.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIRoleMapperImpl.java
  basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/SiteMembershipUpdaterImpl.java
  basiclti/docs/LTIROLES.md
  basiclti/docs/sakai_lti_provider.md
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  kernel/api/src/main/java/org/sakaiproject/site/api/Site.java
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  msgcntr/messageforums-hbm/src/sql/mysql/mfr_conversion_28x-30x.sql
  msgcntr/messageforums-hbm/src/sql/oracle/mfr_conversion_28x-30x.sql
  site/admin-perms-tool/src/main/java/org/sakaiproject/adminsiteperms/tool/SitePermsController.java
Labels: Requires Conversion Script
