Repository sakaiproject/sakai, pull requests merged in 2022-09, with the labels that each got.

#10861 SAK-47850 Update SpotBugs 4.7.2
  master/pom.xml
Labels: low risk

#10874 SAK-47840 CONTENT: Error org.sakaiproject.portal.api.PortalHandlerException: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Tubería rota
  content/content-tool/tool/src/webapp/vm/content/sakai_resources_zipDownloadFinish.vm
Labels: low risk

#10883 SAK-47865: Error 500: /direct/lessons/user.xml
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
Labels: use squash+merge

#10885 SAK-46303 grader: use full ckeditor in notes sections
  webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
Labels: low risk

#10899 SAK-47889 Feedback error in logs when sending email to site contact in "Contact Us" tool
  feedback/src/java/org/sakaiproject/feedback/util/SakaiProxy.java
Labels: low risk

#10906 SAK-47899 - L10N: Update Spanish translation for consistency reasons
  access/access-impl/impl/src/bundle/access_es.properties
  admin-tools/src/bundle/archive_es.properties
  admin-tools/src/bundle/users_es.properties
  announcement/announcement-api/api/src/bundle/announcement_es.properties
  assignment/api/src/resources/assignment_es.properties
  basiclti/basiclti-impl/src/bundle/ltiservice_es.properties
  basiclti/basiclti-portlet/src/bundle/basiclti_es.properties
  basiclti/basiclti-tool/src/bundle/ltitool_es.properties
  calendar/calendar-bundles/resources/calendar_es.properties
  citations/citations-util/util/src/bundle/citations_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/type/types_es.properties
  content-review/impl/compilatio/src/main/resources/compilatio_es.properties
  content-review/impl/turnitin-oc/src/main/resources/turnitin-oc_es.properties
  content-review/impl/turnitin/src/main/resources/turnitin_es.properties
  content/content-bundles/resources/content_es.properties
  content/content-bundles/resources/types_es.properties
  content/content-tool/tool/src/bundle/helper_es.properties
  feedback/src/main/resources/org/sakaiproject/feedback_es.properties
  gradebookng/bundle/src/main/bundle/gradebookng_es.properties
  lessonbuilder/tool/src/resources/messages_es.properties
  mailsender/api/src/bundle/mailsender_es.properties
  message/search-adapters/impl/src/bundle/org/sakaiproject/search/component/adapter/message/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/i18n/pasystem_es.properties
  podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages_es.properties
  polls/api/src/bundle/org/sakaiproject/poll/bundle/Messages_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  postem/postem-app/src/main/resources/Messages_es.properties
  profile2/api/src/resources/ProfileApplication_es.properties
  profile2/api/src/resources/profile_es.properties
  reset-pass/reset-pass/src/main/resources/Messages_es.properties
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages_es.properties
  rwiki/rwiki-util/radeox/src/bundle/org/radeox/Messages_es.properties
  rwiki/rwiki-util/radeox/src/bundle/radeox_messages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/PrintMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  signup/tool/src/bundle/messages_es.properties
  simple-rss-portlet/src/main/java/au/edu/anu/portal/portlets/rss/utils/messages_es.properties
  site-manage/site-group-manager/src/main/resources/Messages_es.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties
  site/sakai-message-bundle-manager-tool/src/main/resources/Messages_es.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
  syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages_es.properties
  syllabus/syllabus-impl/src/bundle/siteemacon_es.properties
  tags/tags-tool/tool/src/java/org/sakaiproject/tags/tool/i18n/tagservice_es.properties
  textarea/FCKeditor/connector/src/bundle/org/sakaiproject/connector/fck/Messages_es.properties
  webcomponents/bundle/src/main/bundle/document-viewer_es.properties
  webcomponents/bundle/src/main/bundle/search_es.properties
  webcomponents/bundle/src/main/bundle/tasks_es.properties
Labels: L10N
