Repository sakaiproject/sakai, pull requests merged in 2023-02, with the labels that each got.

#11218 S2U-30 5.1.4.1 Assignments: When an assignment is created, assign it …
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: s2u-unidigital

#11227 S2U-30 5.1.4.1 Assignments: When an assignment is created, assign it …
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: s2u-unidigital

#11244 S2U-21 SEB: Only run pre-delivery phase for uploaded configs
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Labels: s2u-unidigital

#11245 S2U-21 Fix whitespaces being removed from assessment title
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
Labels: s2u-unidigital

#11248 S2U-21 Fix whitespaces being removed from assessment title again
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
Labels: s2u-unidigital

#11246 S2U-21 SEB: Remove demo configuration properties
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
Labels: s2u-unidigital

#11247 S2U-45 5.2.6.2 Roster: Add a column for each Section & Group to the Export
  roster2/bundle/src/bundle/roster.properties
  roster2/bundle/src/bundle/roster_ca.properties
  roster2/bundle/src/bundle/roster_es.properties
  roster2/bundle/src/bundle/roster_eu.properties
  roster2/tool/src/java/org/sakaiproject/roster/api/RosterGroup.java
  roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java
  roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
  roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterPOIEntityProvider.java
Labels: s2u-unidigital

#11281 S2U-21 SEB: Improve settings info, fix nullpointer and align buttons
  library/src/morpheus-master/sass/base/_extendables.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
  samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
Labels: s2u-unidigital

#11282 SAK-48503 Library Content Replace accented characters by HTML entities
  library/src/webapp/content/webdav_instructions_ca.html
  library/src/webapp/content/webdav_instructions_es.html
Labels: L10N

#11296 SAK-48536 - Remove ByteStorageConversionCheck individual char log
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/serialize/impl/test/ByteStorageConversionCheck.java
Labels: low risk
