Repository sakaiproject/sakai, pull requests merged in 2023-05, with the labels that each got.

#11510 SAK-48812 - Contact us: update the email body note as specified
  feedback/src/main/resources/org/sakaiproject/feedback.properties
Labels: low risk

#11507 s2u-46: BUG Fix. Error creating a group and add members at the same time
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
  site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/GroupController.java
Labels: s2u-unidigital

#11522 S2U-15 Tests & Quizzes: Improve navigation when grading
  library/src/morpheus-master/sass/base/_extendables.scss
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  library/src/morpheus-master/sass/tool.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetTotalScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionNavListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/submissionNav.jsp
Labels: s2u-unidigital

#11533 S2U-15 Make submission date format consistent and remove navigation to list when clicking update
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Labels: s2u-unidigital

#11535 S2U-15 Tests & Quizzes: Add back StudentScoreListener to Update button
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Labels: s2u-unidigital

#11542 S2U-14 Disable item cancellation for assessments with random question from question pool
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Labels: s2u-unidigital

#11239 S2U-11 5.1.1.7 Global variables in calculated questions
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemTextIfc.java
  samigo/samigo-api/src/java/xml/xsl/dataTransform/import/v1p2/extractItem.xsl
  samigo/samigo-app/pom.xml
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionAnswerIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionFormulaBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionGlobalVariableBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionVariableBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionAddGlobalVariableListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionDeleteGlobalVariableListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/js/authoring.js
  samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
Labels: Requires Conversion Script, s2u-unidigital

#11551 s2u-47 Upgrade meetings UI infrastructure
  meetings/ui/pom.xml
  meetings/ui/src/main/frontend/package-lock.json
  meetings/ui/src/main/frontend/package.json
  meetings/ui/src/main/frontend/src/components/sakai-accordion-item.vue
  meetings/ui/src/main/frontend/src/components/sakai-input-labelled.vue
  meetings/ui/src/main/frontend/src/components/sakai-input.vue
  meetings/ui/src/main/frontend/src/components/sakai-meeting-card.vue
  meetings/ui/src/main/frontend/src/components/sakai-select.vue
  meetings/ui/src/main/frontend/src/components/sakai-textarea.vue
  meetings/ui/src/main/frontend/src/main.js
  meetings/ui/src/main/frontend/src/router/index.js
  meetings/ui/src/main/frontend/src/stores/dataStore.js
  meetings/ui/src/main/frontend/src/views/CreateMeeting.vue
  meetings/ui/src/main/frontend/src/views/MeetingRecordings.vue
Labels: s2u-unidigital

#11370 SAK-48657 Profile: Restrict photos to site members only
  profile2/api/src/java/org/sakaiproject/profile2/logic/SakaiProxy.java
  profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java
  profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
  profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
Labels: for discussion

#11575 S2U-27 Messages: Convert a private message into a forum message in the FAQ forum
  kernel/api/src/main/java/org/sakaiproject/site/api/Site.java
  kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/DiscussionForum.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/DiscussionTopic.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java
  msgcntr/messageforums-app/pom.xml
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumPublishToFaqBean.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgPublishToFaqEdit.jsp
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/DiscussionForumImpl.java
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/DiscussionTopicImpl.java
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/OpenForum.hbm.xml
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/Topic.hbm.xml
Labels: s2u-unidigital

#11580 NOJIRA: Fix ES GB String.
  gradebookng/bundle/src/main/bundle/gradebookng_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
Labels: I18N, L10N

#11579 NOJIRA: Fix ES String in GB
  gradebookng/bundle/src/main/bundle/gradebookng_es.properties
Labels: I18N, L10N

#11584 S2U-29 5.1.3.3 Private Messages: Request a read receipt feature
  kernel/kernel-impl/src/main/webapp/WEB-INF/components.xml
  library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
  msgcntr/messageforums-api/pom.xml
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/DiscussionForumService.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/PrivateMessageBullhornHandler.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/PrivateMessageRecipient.java
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/PrivateMessageManager.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
  msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/PrivateMessageRecipientImpl.java
  portal/portal-impl/impl/src/bundle/bullhorns.properties
  portal/portal-impl/impl/src/bundle/bullhorns_ca.properties
  portal/portal-impl/impl/src/bundle/bullhorns_es.properties
Labels: s2u-unidigital

#11589 S2U-43 5.2.8.1 Admin: Ability to enrol, unenrol and disable multiple users in multiple sites.
  admin-bulk-user-membership/tool/src/main/resources/Messages_ca.properties
  admin-bulk-user-membership/tool/src/main/resources/Messages_es.properties
  admin-bulk-user-membership/tool/src/main/resources/Messages_eu.properties
Labels: s2u-unidigital

#11591 S2U-43 5.2.8.1 Admin: Ability to enrol, unenrol and disable multiple users in multiple sites - fix
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/controller/MainController.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/model/Summary.java
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/auto_membership_step_3.html
Labels: s2u-unidigital

#11605 SAK-48938 Remove unused fa_IR files
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/GeneralMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/MainIndexMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/PrintMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/SectionActivityMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages_fa_IR.properties
  samigo/samigo-app/bin/src/java/org/sakaiproject/tool/assessment/bundle/TemplateMessages_fa_IR.properties
Labels: I18N, L10N

#11505 SAK-48803 Portal revise tutorial pop-up content
  help/help-component/src/bundle/TutorialMessages.properties
  help/help-component/src/tutorial/Tutorial.config
  library/src/skins/default/src/sass/modules/tool/tutorial/_base.scss
  library/src/webapp/js/jquery/qtip/tutorial.js
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
Labels: BLOCKER

#11610 SAK-48349 Roster: Print views need to be fixed
  roster2/tool/src/webapp/css/print.css
Labels: BLOCKER

#11578 SAK-48430 autosave grading data if navigating between submissions
  webcomponents/bundle/src/main/bundle/grader.properties
  webcomponents/bundle/src/main/bundle/grader_ar.properties
  webcomponents/bundle/src/main/bundle/grader_ca.properties
  webcomponents/bundle/src/main/bundle/grader_de_DE.properties
  webcomponents/bundle/src/main/bundle/grader_es.properties
  webcomponents/bundle/src/main/bundle/grader_fr_FR.properties
  webcomponents/bundle/src/main/bundle/grader_ro_RO.properties
  webcomponents/bundle/src/main/bundle/grader_tr_TR.properties
  webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
Labels: L10N

#11617 S2U-24 Update I18N Strings
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DataTablesMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DataTablesMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_eu.properties
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Labels: s2u-unidigital

#11621 S2U-49: FIX - Included private channel folders
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftCommonService.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
Labels: s2u-unidigital

#11625 S2U-29 5.1.3.3 Private Messages: Request a read receipt feature - fix
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/PrivateMessageBullhornHandler.java
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Labels: s2u-unidigital

#11626 S2U-27 Handle deleted forums/topic and other fixes
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
  msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumPublishToFaqBean.java
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgPublishToFaqEdit.jsp
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
Labels: s2u-unidigital
