Repository sakaiproject/sakai, pull requests merged in 2023-10, with the labels that each got.

#11962 s2u-6 5.1.1.2 Tests & Quizzes: Show number of correct, incorrect and …
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Labels: s2u-unidigital

#11963 S2U-31 Assignments: Grades in the main view of assignments that have already been evaluated - MASTER
  assignment/api/src/resources/assignment.properties
  assignment/api/src/resources/assignment_ca.properties
  assignment/api/src/resources/assignment_es.properties
  assignment/api/src/resources/assignment_eu.properties
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Labels: s2u-unidigital

#11978 S2U-25 5.1.1.21 Test & Quizzes: Question pools export
  samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
Labels: s2u-unidigital

#11979 S2U-25 SAK-49354 Samigo: Export pool and clicking Cancel displays a console error - SPNR is not defined
  samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
Labels: s2u-unidigital

#11964 S2U-46: Minor fixes
  meetings/README.md
  microsoft-integration/README.md
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/GlobalController.java
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/config.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/autoConfig.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/newSiteSynchronization.html
Labels: s2u-unidigital

#11950 S2U-34 Assignments add rubric support for peer review
  assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
  assignment/api/src/resources/assignment.properties
  assignment/api/src/resources/assignment_ar.properties
  assignment/api/src/resources/assignment_ca.properties
  assignment/api/src/resources/assignment_de_DE.properties
  assignment/api/src/resources/assignment_es.properties
  assignment/api/src/resources/assignment_eu.properties
  assignment/api/src/resources/assignment_fr_FR.properties
  assignment/api/src/resources/assignment_ro_RO.properties
  assignment/api/src/resources/assignment_tr_TR.properties
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentEventObserver.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/impl/src/webapp/WEB-INF/components.xml
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
  assignment/tool/src/webapp/WEB-INF/applicationContext.xml
  assignment/tool/src/webapp/js/assignments.js
  assignment/tool/src/webapp/js/instructorNewEdit.js
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsConstants.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Evaluation.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/EvaluationRepository.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java
  rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
  webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js
  webcomponents/tool/src/main/frontend/js/grader/submission.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-api-mixin.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-utils.js
Labels: Requires Conversion Script, s2u-unidigital

#11973 UNIADAPTIVE Work package (s2u-22x)
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
  webapi/pom.xml
  webapi/src/main/java/org/sakaiproject/webapi/beans/LessonItemRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/beans/SiteEntityRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/beans/TimeExceptionRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/Conditions.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/LessonsController.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
Labels: s2u-unidigital

#11980 SAK-49355 Update Passay 1.6.4
  kernel/kernel-impl/pom.xml
Labels: low risk

#11988 S2U-21 Tests & Quizzes: Fixes seb.enabled=site
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Labels: s2u-unidigital

#11994 SAK-49363 Update Lombok 1.18.30
  master/pom.xml
Labels: low risk

#11998 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/RequestScopeSuperBean.java
Labels: s2u-unidigital

#11986 SAK-49258 UNIADAPTIVE Work package fixes (s2u-22x)
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
  webapi/src/main/java/org/sakaiproject/webapi/beans/SiteEntityRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
Labels: s2u-unidigital

#12014 SAK-49382 Missing header Samigo
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/TestsAndQuizzesUserNotificationHandler.java
Labels: low risk

#12023 S2U-23 5.1.1.19 Tests & Quizzes: Add the option to show the student …
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/AssessmentFeedbackIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/FeedbackComponent.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
  samigo/samigo-app/src/webapp/js/authoring.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverExtendedMatchingItems.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatching.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswer.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswerLink.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBase.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentFeedback.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedFeedback.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: Requires Conversion Script, s2u-unidigital

#12027 S2U-11 5.1.1.7 Tests & Quizzes: Global variables in calculated questions - MASTER
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemTextIfc.java
  samigo/samigo-api/src/java/xml/xsl/dataTransform/import/v1p2/extractItem.xsl
  samigo/samigo-app/pom.xml
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionAnswerIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionFormulaBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionGlobalVariableBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionVariableBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionAddGlobalVariableListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionDeleteGlobalVariableListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/js/authoring.js
  samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
Labels: Requires Conversion Script, s2u-unidigital

#12034 S2U-44 5.2.8.2 Portal – Visibility of the role that the user is using…
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-impl/impl/src/bundle/sitenav_ca.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_eu.properties
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
Labels: s2u-unidigital

#12035 S2U-37 5.2.1.2 Announcements: Ability to highlight announcements - Master
  announcement/announcement-api/api/src/bundle/announcement.properties
  announcement/announcement-api/api/src/bundle/announcement_ca.properties
  announcement/announcement-api/api/src/bundle/announcement_es.properties
  announcement/announcement-api/api/src/bundle/announcement_eu.properties
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/entityprovider/AnnouncementEntityProviderImpl.java
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementActionState.java
  announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
  announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
  lessonbuilder/tool/src/webapp/js/announcements.js
  library/src/skins/default/src/sass/modules/tool/announcements/_announcements.scss
  library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
  library/src/skins/default/src/sass/modules/tool/synoptic/_synoptic.scss
Labels: s2u-unidigital

#12036 S2U-30 5.1.4.1 Assignments: When an assignment is created, assign it by default to the groups where the user is an instructor - Master
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: s2u-unidigital

#12008 SAK-48898 Roster add aria-label and title to profile links
  roster2/bundle/src/bundle/roster.properties
  roster2/tool/src/handlebars/members_cards.handlebars
Labels: low risk

#12047 SAK-49414 Global update Apache Commons Text 1.11.0
  master/pom.xml
Labels: low risk
