Repository sakaiproject/sakai, pull requests merged in 2023-09, with the labels that each got.

#11856 S2U-35 Lessons: View items based on grade
  conditions/api/pom.xml
  conditions/api/src/java/org/sakaiproject/condition/api/ConditionEvaluator.java
  conditions/api/src/java/org/sakaiproject/condition/api/ConditionService.java
  conditions/api/src/java/org/sakaiproject/condition/api/exception/UnsupportedToolIdException.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/Condition.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionOperator.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionType.java
  conditions/api/src/java/org/sakaiproject/condition/api/persistence/ConditionRepository.java
  conditions/impl/pom.xml
  conditions/impl/src/java/org/sakaiproject/condition/impl/ConditionServiceImpl.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssessmentConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssignmentConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/BaseConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/LessonsConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/persistence/ConditionRepositoryImpl.java
  conditions/impl/src/webapp/WEB-INF/components.xml
  conditions/pom.xml
  kernel/api/src/main/java/org/sakaiproject/authz/api/SecurityAdvisor.java
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  lessonbuilder/tool/pom.xml
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/EditPageProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/FolderPickerProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/LessonConditionUtil.java
  lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
  lessonbuilder/tool/src/webapp/js/folder-picker.js
  lessonbuilder/tool/src/webapp/js/show-page.js
  lessonbuilder/tool/src/webapp/templates/EditPage.html
  lessonbuilder/tool/src/webapp/templates/FolderPicker.html
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  master/pom.xml
  pom.xml
  vuecomponents/bundle/src/main/bundle/condition.properties
  vuecomponents/bundle/src/main/bundle/condition_ca.properties
  vuecomponents/bundle/src/main/bundle/condition_es.properties
  vuecomponents/bundle/src/main/bundle/condition_eu.properties
  vuecomponents/docs/i18n.md
  vuecomponents/tool/pom.xml
  vuecomponents/tool/src/main/frontend/.gitignore
  vuecomponents/tool/src/main/frontend/build-dev.mjs
  vuecomponents/tool/src/main/frontend/src/api/conditions-api.js
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/alert.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/badges.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/card.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/form.scss
  vuecomponents/tool/src/main/frontend/src/components/condition-editor.vue
  vuecomponents/tool/src/main/frontend/src/components/condition-picker.vue
  vuecomponents/tool/src/main/frontend/src/components/condition-text.vue
  vuecomponents/tool/src/main/frontend/src/mixins/i18n-mixin.js
  vuecomponents/tool/src/main/frontend/src/utils/condition-utils.js
  vuecomponents/tool/src/main/frontend/src/utils/core-utils.js
  webapi/pom.xml
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java
Labels: s2u-unidigital

#11867 S2U-6 5.1.1.2 Tests & Quizzes: Show number of correct, incorrect and …
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: s2u-unidigital

#11898 S2U-35 Lessons: Fix non exact comparison
  vuecomponents/tool/src/main/frontend/src/api/conditions-api.js
Labels: s2u-unidigital

#11865 S2U-10 5.1.1.6 Tests & Quizzes: Ability to preview calculated questions in question pool - MASTER
  library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/movePool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: s2u-unidigital

#11907 S2U-28 Hide tags section from Lessons iframe
  assignment/tool/src/webapp/js/assignments.js
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Labels: s2u-unidigital

#11899 S2U-35 Lessons: Undo all exact comparisons for itemId
  conditions/api/src/java/org/sakaiproject/condition/api/model/Condition.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/ConditionServiceImpl.java
  vuecomponents/tool/src/main/frontend/src/components/condition-picker.vue
Labels: s2u-unidigital

#11866 S2U-25 5.1.1.21 Test & Quizzes: Question pools export - MASTER
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/qti/QTIServiceAPI.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/shared/impl/qti/QTIServiceImpl.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLController.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLImportBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ChooseExportTypeListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ExportPoolListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/CancelPoolListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/cp/DownloadCPServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/export/ExportMarkupTextServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoTool.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoToolServiceSoapBindingImpl.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoToolWebService.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
  samigo/samigo-app/src/webapp/jsf/qti/exportPool.jsp
  samigo/samigo-app/src/webapp/jsf/qti/importPool.jsp
  samigo/samigo-app/src/webapp/jsf/qti/xmlPoolDisplay.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/previewPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/subpoolsTreeTable.jsp
  samigo/samigo-cp/pom.xml
  samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ManifestGenerator.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/services/qti/QTIService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java
Labels: s2u-unidigital

#11915 S2U-5 Some fixes
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
  vuecomponents/tool/src/main/frontend/src/components/dynamic-criterion.vue
  vuecomponents/tool/src/main/frontend/src/components/dynamic-rubric.vue
  webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
Labels: s2u-unidigital

#11906 SAK-49269 Polls: Charts are not visible in Spanish (es_ES locale)
  polls/tool/src/java/org/sakaiproject/poll/tool/producers/ResultsProducer.java
Labels: I18N

#11923 SAK-49291 Update OpenSearch 1.3.12
  master/pom.xml
Labels: low risk

#11920 S2U-42 SAK-49260 Card Game: Keep the photo after a wrong response
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileImageLogicImpl.java
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/bundle/src/bundle/card_game_eu.properties
  roster2/tool/src/webapp/js/card-game/card-game.js
  webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Labels: s2u-unidigital

#11921 S2U-42 SAK-49261 Card Game: Instructors with full access can play with groups
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/tool/src/webapp/js/card-game/card-game-api.js
  roster2/tool/src/webapp/js/card-game/card-game.js
  roster2/tool/src/webapp/js/card-game/index.js
  webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Labels: s2u-unidigital

#11930 S2U-42 SAK-49271 Card Game: Do not require an answer
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital

#11929 SAK-49299 Grader: Spanish translation for 'filter_settings_warning' i…
  webcomponents/bundle/src/main/bundle/grader_es.properties
Labels: low risk, L10N

#11935 S2U-42 SAK-49271 Card game: Fix "null" displayed in info banner
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital

#11939 S2U-42 SAK-49260 Card game: Fix mark as learned
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital

#11937 SAK-49259 Card Game: Skip users with no photo
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileImageLogicImpl.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Labels: s2u-unidigital

#11938 SAK-49260 Card Game: Keep the photo after a wrong response
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/bundle/src/bundle/card_game_eu.properties
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital

#11940 SAK-49261 Card Game: Instructors with full access can play with groups
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/tool/src/webapp/js/card-game/card-game-api.js
  roster2/tool/src/webapp/js/card-game/card-game.js
  roster2/tool/src/webapp/js/card-game/index.js
  webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Labels: s2u-unidigital

#11941 SAK-49271 Card Game: Do not require an answer
  roster2/bundle/src/bundle/card_game.properties
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital
