Repository sakaiproject/sakai, pull requests merged in 2023-04, with the labels that each got.

#11450 SAK-27765: Entity Broker test fail
  entitybroker/rest/src/test/org/sakaiproject/entitybroker/rest/EntityDescriptionManagerTest.java
  entitybroker/rest/src/test/org/sakaiproject/entitybroker/rest/EntityHandlerImplTest.java
Labels: I18N, L10N

#11461 S2U-37 Announcements: Ability to highlight announcements
  announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
Labels: s2u-unidigital

#11462 S2U-31 Assignments: Grades in the main view of assignments that have already been evaluated
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Labels: s2u-unidigital

#11459 s2u-46: Fixed sorting bug on main screen
  microsoft-integration/admin-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_es.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_eu.properties
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/index.html
Labels: s2u-unidigital

#11466 S2U-14 Samigo: Several improvements related to question cancellation
  library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/ifc/GradebookServiceHelper.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/ItemCancellationTest.java
Labels: s2u-unidigital

#11468 S2U-10 5.1.1.6 Tests & Quizzes: Ability to preview calculated questions in question pools
  samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
Labels: s2u-unidigital

#11417 S2U-25 5.1.1.21 Test & Quizzes: Question pools export
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/qti/QTIServiceAPI.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/shared/impl/qti/QTIServiceImpl.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLController.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLImportBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ChooseExportTypeListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ExportPoolListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/CancelPoolListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/cp/DownloadCPServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/export/ExportMarkupTextServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoTool.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoToolServiceSoapBindingImpl.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ws/SamigoToolWebService.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
  samigo/samigo-app/src/webapp/jsf/qti/exportPool.jsp
  samigo/samigo-app/src/webapp/jsf/qti/importPool.jsp
  samigo/samigo-app/src/webapp/jsf/qti/xmlPoolDisplay.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/previewPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/subpoolsTreeTable.jsp
  samigo/samigo-cp/pom.xml
  samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ManifestGenerator.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/services/qti/QTIService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java
Labels: s2u-unidigital

#11500 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiObjectService.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/RequestScopeSuperBean.java
Labels: s2u-unidigital

#11496 SAK-48811 - Suppress X-Frame-Options when SakaiPlus is enabled
  kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
Labels: low risk

#11501 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/IndexMacro.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/SaveCommand.java
Labels: s2u-unidigital
