Repository sakaiproject/sakai, pull requests merged in 2023-07, with the labels that each got.

#11721 s2u-48: Show student items based on groups
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftCommonService.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/auxiliar/MediaGallerySessionBean.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/controller/MainController.java
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/body.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/fragments/common.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/js/common.js
Labels: s2u-unidigital

#11728 SAK-49070 Forums:Checking licenses
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/util/PrivateMessagesToolHelper.java
  msgcntr/messageforums-app/src/test/org/sakaiproject/msgcntr/tool/PrivateMessagesToolHelperTest.java
Labels: low risk

#11736 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiSecurityService.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
Labels: s2u-unidigital

#11740 S2U-32 More fixes (also S2U-28)
  library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
  webapi/src/main/java/org/sakaiproject/webapi/controllers/TagsController.java
Labels: s2u-unidigital

#11744 SAK-49083 Rubrics: fix ConcurrentModificationException
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
Labels: BLOCKER

#11754 S2U-11 5.1.1.7 Tests & Quizzes: Global variables in calculated questions
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
Labels: s2u-unidigital

#11752 S2U-28-32 Tags fixes
  tags/tags-impl/impl/src/java/org/sakaiproject/tags/impl/TagServiceImpl.java
Labels: Requires Conversion Script, s2u-unidigital

#11762 SAK-49073 SakaiGrader default property in the wrong language file
  webcomponents/bundle/src/main/bundle/grader-toggle.properties
  webcomponents/bundle/src/main/bundle/grader-toggle_ca.properties
Labels: I18N, L10N

#11774 SAK-49105 Update OpenSearch 1.3.11
  master/pom.xml
Labels: low risk

#11784 SAK-49112 Config: Direct uploads are disabled by default.
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Labels: low risk

#11780 S2U-21 Tests & Quizzes: Support for Safe Exam Browser
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Labels: s2u-unidigital

#11760 S2U-50: Microsoft Collaborative Documents
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_ca.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_eu.properties
  library/src/morpheus-master/sass/base/_icons.scss
  library/src/morpheus-master/sass/modules/tool/microsoft-collaborativedocuments/_microsoft-collaborativedocuments.scss
  library/src/morpheus-master/sass/tool.scss
  microsoft-integration/README.md
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/ConfigController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/ConfigRequest.java
  microsoft-integration/admin-tool/src/main/resources/Messages.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_es.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_eu.properties
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/config.html
  microsoft-integration/api/pom.xml
  microsoft-integration/api/src/bundle/microsoft.properties
  microsoft-integration/api/src/bundle/microsoft_ca.properties
  microsoft-integration/api/src/bundle/microsoft_es.properties
  microsoft-integration/api/src/bundle/microsoft_eu.properties
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftCommonService.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftConfigurationService.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftDriveItem.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftDriveItemFilter.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftTeamWrapper.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/exceptions/AjaxException.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/persistence/MicrosoftConfigRepository.java
  microsoft-integration/collaborative-documents/pom.xml
  microsoft-integration/collaborative-documents/src/main/java/org/sakaiproject/microsoft/collaborativedocuments/ThymeleafConfig.java
  microsoft-integration/collaborative-documents/src/main/java/org/sakaiproject/microsoft/collaborativedocuments/WebAppConfiguration.java
  microsoft-integration/collaborative-documents/src/main/java/org/sakaiproject/microsoft/collaborativedocuments/auxiliar/CollaborativeDocumentsSessionBean.java
  microsoft-integration/collaborative-documents/src/main/java/org/sakaiproject/microsoft/collaborativedocuments/controller/MainController.java
  microsoft-integration/collaborative-documents/src/main/resources/Messages.properties
  microsoft-integration/collaborative-documents/src/main/resources/Messages_ca.properties
  microsoft-integration/collaborative-documents/src/main/resources/Messages_es.properties
  microsoft-integration/collaborative-documents/src/main/resources/Messages_eu.properties
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/body.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/error.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/fragments/common.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/fragments/driveItems.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/fragments/menus.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/js/common.js
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/permissions.html
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/tools/microsoft.collaborativedocuments.xml
  microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/web.xml
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftConfigurationServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
  microsoft-integration/impl/src/webapp/WEB-INF/components.xml
  microsoft-integration/pom.xml
Labels: s2u-unidigital

#11737 S2U-12 5.1.1.8 Tests & Quizzes: Improving i18n and feedback on calculated questions - MASTER
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemFeedbackIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/print/preview_item/CalculatedQuestion.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemFeedback.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemFeedback.java
  samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoAssessmentHandler.java
  samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoPoolHandler.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/facade/ItemHashUtilTest.java
Labels: for discussion, Requires Conversion Script, s2u-unidigital

#11753 S2U-45 Roster: Add a column for each Section & Group to the Export - MASTER
  roster2/bundle/src/bundle/roster.properties
  roster2/bundle/src/bundle/roster_ca.properties
  roster2/bundle/src/bundle/roster_es.properties
  roster2/bundle/src/bundle/roster_eu.properties
  roster2/tool/src/java/org/sakaiproject/roster/api/RosterGroup.java
  roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java
  roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
  roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterPOIEntityProvider.java
Labels: s2u-unidigital

#11759 S2U-15 Tests & Quizzes: Improve navigation when grading - MASTER
  library/src/skins/default/src/sass/base/_extendables.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetTotalScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionNavListener.java
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/submissionNav.jsp
Labels: s2u-unidigital

#11769 S2U-38 Resources: Add "Download ZIP" event when downloading zip files from resources - MASTER
  content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
  kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
  sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml
  sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef_sakai-2-4-x.xml
  sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef_sakai-2-5-x.xml
  sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/report/ReportManager.java
  sitestats/sitestats-bundle/src/resources/Events.properties
  sitestats/sitestats-bundle/src/resources/Events_ca.properties
  sitestats/sitestats-bundle/src/resources/Events_es.properties
  sitestats/sitestats-bundle/src/resources/Events_eu.properties
  sitestats/sitestats-bundle/src/resources/Messages.properties
  sitestats/sitestats-bundle/src/resources/Messages_ca.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
  sitestats/sitestats-bundle/src/resources/Messages_eu.properties
  sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportsEditPage.java
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/WidgetTabTemplate.java
Labels: s2u-unidigital

#11787 SAK-49113 Sitestats: Unable to download reports when the site contain…
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportDataPage.java
Labels: BLOCKER

#11788 S2U-48: Permissions, accessibilitiy and more
  library/src/morpheus-master/sass/modules/tool/microsoft-mediagallery/_microsoft-mediagallery.scss
  microsoft-integration/README.md
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/ThymeleafConfig.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/controller/MainController.java
  microsoft-integration/media-gallery-tool/src/main/resources/Messages.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_es.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_eu.properties
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/body.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/fragments/driveItems.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/fragments/menus.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/info.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/js/common.js
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/permissions.html
Labels: s2u-unidigital

#11766 S2U-5 5.1.1.1 Tests & Quizzes: Dynamic Rubrics
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
  library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_scaffolding.scss
  library/src/morpheus-master/sass/themes/_base.scss
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsConstants.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/RubricRepository.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/RubricRepositoryImpl.java
  rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
  samigo/samigo-app/src/webapp/js/samigo-global.js
  samigo/samigo-app/src/webapp/jsf/author/item/rubricAssociation.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
  vuecomponents/bundle/src/main/bundle/dynamic-criterion.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_ca.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_es.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_eu.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_ca.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_es.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_eu.properties
  vuecomponents/tool/src/main/frontend/package-lock.json
  vuecomponents/tool/src/main/frontend/package.json
  vuecomponents/tool/src/main/frontend/src/api/dynamic-rubrics-api.js
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/buttons.scss
  vuecomponents/tool/src/main/frontend/src/components/dynamic-criterion.vue
  vuecomponents/tool/src/main/frontend/src/components/dynamic-rubric.vue
  vuecomponents/tool/src/main/frontend/src/utils/dynamic-rubrics-utils.js
  webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-preview-button.js
  webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
Labels: Requires Conversion Script, s2u-unidigital
