Repository sakaiproject/sakai, pull requests merged in 2023-06, with the labels that each got.

#11628 S2U-24 Tests & Quizzes: Event Log - Several fixes
  samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/EventLogBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EventLogListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/DataTableColumn.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/event/ExportEventLogServlet.java
Labels: s2u-unidigital

#11646 S2U-29 5.1.3.3 Private Messages: Request a read receipt feature
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Labels: s2u-unidigital

#11653 S2U-11 5.1.1.7 Tests & Quizzes: Global variables in calculated questions
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
Labels: s2u-unidigital

#11661 SAK-48453 - Lessons: Uncaught ReferenceError: resizeiframe is not defined
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
Labels: low risk

#11665 SAK-49001 - Fix duplicate id in Admin Site List
  admin-tools/src/webapp/vm/sites/chef_sites_list.vm
Labels: low risk

#11667 S2U-24 5.1.1.20 Tests & Quizzes: Improve event log UI
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DataTablesMessages_es.properties
Labels: s2u-unidigital

#11664 SAK-49000 - Remove duplicate id in Site Manage Overview
  site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageOverview.vm
Labels: low risk

#11673 S2U-48: Microsoft Stream integration
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_ca.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_eu.properties
  library/src/morpheus-master/sass/base/_icons.scss
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  library/src/morpheus-master/sass/modules/tool/microsoft-mediagallery/_microsoft-mediagallery.scss
  library/src/morpheus-master/sass/tool.scss
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftCommonService.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftDriveItem.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftDriveItemFilter.java
  microsoft-integration/authorization-tool/src/main/java/org/sakaiproject/microsoft/authorization/controller/MainController.java
  microsoft-integration/authorization-tool/src/main/resources/Messages.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_ar.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_de_DE.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_es.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_fr_FR.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_ro_RO.properties
  microsoft-integration/authorization-tool/src/main/resources/Messages_tr_TR.properties
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
  microsoft-integration/media-gallery-tool/pom.xml
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/ThymeleafConfig.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/WebAppConfiguration.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/auxiliar/MediaGallerySessionBean.java
  microsoft-integration/media-gallery-tool/src/main/java/org/sakaiproject/microsoft/mediagallery/controller/MainController.java
  microsoft-integration/media-gallery-tool/src/main/resources/Messages.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_es.properties
  microsoft-integration/media-gallery-tool/src/main/resources/Messages_eu.properties
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/error.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/fragments/common.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/fragments/driveItems.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/index_ws.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/info.html
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/js/common.js
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/tools/microsoft.mediagallery.xml
  microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/web.xml
  microsoft-integration/pom.xml
Labels: s2u-unidigital

#11680 S2U-34 Fix gradebook association
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Labels: s2u-unidigital

#11652 S2U-42 5.2.6.1 Roster: The Card Game!
  roster2/bundle/src/bundle/card_game_ca.properties
  roster2/bundle/src/bundle/card_game_es.properties
  roster2/tool/src/webapp/js/card-game/card-game.js
Labels: s2u-unidigital

#11684 SAK-49009 Catalan bundles update for current 22.x code
  access/access-impl/impl/src/bundle/access_ca.properties
  announcement/announcement-api/api/src/bundle/announcement_ca.properties
  assignment/api/src/resources/assignment_ca.properties
  basiclti/basiclti-impl/src/bundle/ltiservice_ca.properties
  basiclti/basiclti-oidc/src/bundle/oidc_ca.properties
  basiclti/basiclti-tool/src/bundle/ltitool_ca.properties
  calendar/calendar-bundles/resources/calendar_ca.properties
  commons/api/src/bundle/commons_ca.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content_ca.properties
  conversations/api/src/main/resources/conversations_ca.properties
  conversations/api/src/main/resources/conversations_noti_prefs_ca.properties
  conversations/api/src/main/resources/conversations_notifications_ca.properties
  gradebookng/bundle/src/main/bundle/gradebookng_ca.properties
  lessonbuilder/tool/src/resources/messages_ca.properties
  mailsender/api/src/bundle/mailsender_ca.properties
  message/search-adapters/impl/src/bundle/org/sakaiproject/search/component/adapter/message/bundle/Messages_ca.properties
  msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
  pasystem/pasystem-impl/impl/src/resources/org/sakaiproject/pasystem/impl/i18n/pasystem_ca.properties
  podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages_ca.properties
  polls/api/src/bundle/org/sakaiproject/poll/bundle/Messages_ca.properties
  portal/portal-impl/impl/src/bundle/sitenav_ca.properties
  portal/portal-service-impl/impl/src/bundle/connection-manager_ca.properties
  portal/portal-service-impl/impl/src/bundle/profile-popup_ca.properties
  postem/postem-app/src/main/resources/Messages_ca.properties
  profile2/api/src/resources/ProfileApplication_ca.properties
  profile2/util/src/java/org/sakaiproject/profile2/util/messages_ca.properties
  reset-pass/account-validator-tool/src/resources/messages_ca.properties
  reset-pass/reset-pass/src/main/resources/Messages_ca.properties
  rubrics/api/src/main/bundle/rubrics_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/TemplateMessages_ca.properties
  sections/sections-app/src/bundle/sections_ca.properties
  signup/tool/src/bundle/permissions_ca.properties
  site-manage/datemanager/impl/src/bundle/datemanager_ca.properties
  site-manage/datemanager/tool/src/main/resources/Messages_ca.properties
  site-manage/site-group-manager/src/main/resources/Messages_ca.properties
  site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties
  sitestats/sitestats-bundle/src/resources/Events_ca.properties
  sitestats/sitestats-bundle/src/resources/Messages_ca.properties
  textarea/FCKeditor/connector/src/bundle/org/sakaiproject/connector/fck/Messages_ca.properties
  webcomponents/bundle/src/main/bundle/document-viewer_ca.properties
  webcomponents/bundle/src/main/bundle/grader-toggle.properties
  webcomponents/bundle/src/main/bundle/grader_ca.properties
  webcomponents/bundle/src/main/bundle/permissions-wc_ca.properties
  webcomponents/bundle/src/main/bundle/profile_ca.properties
  webcomponents/bundle/src/main/bundle/pronunciation-player_ca.properties
  webcomponents/bundle/src/main/bundle/search_ca.properties
  webcomponents/bundle/src/main/bundle/tasks_ca.properties
Labels: I18N, L10N

#11656 S2U-22 5.1.1.18 Tests & Quizzes: Accept HTML in the markup editor
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/samlite/SamLiteBean.java
  samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
  samigo/samigo-app/src/webapp/jsf/samlite/samLiteValidation.jsp
  samigo/samlite-impl/src/java/org/sakaiproject/tool/assessment/samlite/impl/SamLiteServiceImpl.java
Labels: s2u-unidigital

#11685 S2U-28 Tags + private messages: more improvements and bug fixing
  library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
  msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/msgHeader.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
  tags/tags-tool/tool/src/java/org/sakaiproject/tags/tool/TagServiceServlet.java
  tags/tags-tool/tool/src/java/org/sakaiproject/tags/tool/handlers/IndexHandler.java
  tags/tags-tool/tool/src/java/org/sakaiproject/tags/tool/handlers/TagCollectionsHandler.java
  tags/tags-tool/tool/src/java/org/sakaiproject/tags/tool/views/index.hbs
  vuecomponents/tool/src/main/frontend/src/components/tag-selector.vue
Labels: s2u-unidigital

#11693 S2U-24 Tests & Quizzes: Event Log - Several fixes #2
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EventLogListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/DataTableColumn.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/event/ExportEventLogServlet.java
  samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
Labels: s2u-unidigital

#11697 S2U-32 Assignment tags - permission consistency
  assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
  assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Labels: s2u-unidigital

#11695 S2U-11 5.1.1.7 Tests & Quizzes: Global variables in calculated questions
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemTextIfc.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
Labels: s2u-unidigital

#11699 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/SiteEmailNotificationRWiki.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/CommentNewCommand.java
Labels: s2u-unidigital

#11698 S2U-42 Roster: Card Game - Make card game group aware
  roster2/tool/src/handlebars/navbar.handlebars
  roster2/tool/src/webapp/js/card-game/card-game.js
  webapi/pom.xml
  webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Labels: s2u-unidigital

#11707 S2U-22 5.1.1.18 Tests & Quizzes: Accept HTML in the markup editor - fix
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
Labels: s2u-unidigital

#11704 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiObjectService.java
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/model/RWikiObject.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/IndexMacro.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/SiteEmailNotificationRWiki.java
  rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWiki.hbm.xml
  rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWikiObjectImpl.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/CommentNewCommand.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/SaveCommand.java
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/view.vm
Labels: Requires Conversion Script, s2u-unidigital

#11710 S2U-46: New features
  kernel/api/src/main/java/org/sakaiproject/messaging/api/MicrosoftMessage.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
  library/src/morpheus-master/sass/modules/tool/microsoft-admin/_microsoft-admin.scss
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/AutoConfigController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/ConfigController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/GlobalController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/MainController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/SiteSynchronizationController.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/AjaxResponse.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/AutoConfigConfirmRequest.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/AutoConfigRequest.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/ConfigRequest.java
  microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/SiteSynchronizationRequest.java
  microsoft-integration/admin-tool/src/main/resources/Messages.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_ca.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_es.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_eu.properties
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/config.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/credentials.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/editGroupSynchronization.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/autoConfig.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/siteFilter.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/synchronizationRow.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/index.html
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/newSiteSynchronization.html
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftConfigurationService.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftSynchronizationService.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/SakaiSiteFilter.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/model/MicrosoftLog.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/model/SiteSynchronization.java
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/persistence/MicrosoftConfigRepository.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftConfigurationServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/jobs/RunSynchronizationsJob.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/persistence/MicrosoftConfigRepositoryImpl.java
  microsoft-integration/impl/src/webapp/WEB-INF/components.xml
Labels: s2u-unidigital

#11727 S2U-22 5.1.1.18 Tests & Quizzes: Accept HTML in the markup editor - fix
  samigo/samlite-impl/src/java/org/sakaiproject/tool/assessment/samlite/impl/SamLiteServiceImpl.java
Labels: s2u-unidigital

#11725 SAK-49068 Portal: Home site disappearing when accessing tools in other sites
  library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
Labels: BLOCKER
