Repository sakaiproject/sakai, pull requests merged in 2023-03, with the labels that each got.

#11368 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/IndexMacro.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/ReferencesBean.java
Labels: s2u-unidigital

#11375 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
Labels: s2u-unidigital

#11377 s2u-46 5.3.1: Update Messages_ca.properties
  microsoft-integration/admin-tool/src/main/resources/Messages_ca.properties
Labels: cla?, s2u-unidigital

#11382 S2u-46 5.3.1: Fix
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/autoConfig.html
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
Labels: s2u-unidigital

#11393 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/RequestScopeSuperBean.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
Labels: s2u-unidigital

#11411 SAK-48712 Update Apache commons-configuration 2.9.0
  master/pom.xml
Labels: low risk

#11413 SAK-48714 Update Joda-time 2.12.5
  master/pom.xml
Labels: low risk
