Repository sakaiproject/sakai, pull requests merged in 2023-12, with the labels that each got.

#12156 SAK-49531 - Decoupled LTI Debug from logging settings
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Labels: low risk

#12164 SAK-49537 - Switch !plussite Dashboard ot single column layout
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
Labels: low risk

#12163 SAK-49538 rm sakai.commons-logging.version (properties)
  master/pom.xml
Labels: low risk

#12165 SAK-49502 - Remove inactive users from LTI NRPS
  basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
Labels: low risk

#12183 S2U-23 5.1.1.19 Tests & Quizzes: Add the option to show the student t…
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/AssessmentFeedbackIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/FeedbackComponent.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
  samigo/samigo-app/src/webapp/js/authoring.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverExtendedMatchingItems.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverImageMapQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatching.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswer.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswerLink.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBase.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentFeedback.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedFeedback.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Labels: Requires Conversion Script, s2u-unidigital

#12185 S2U-6 5.1.1.2 Tests & Quizzes: Show number of correct, incorrect and …
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/StudentScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: s2u-unidigital

#12189 S2U-22 5.1.1.18 Tests & Quizzes: Accept HTML in the markup editor - master
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SamLite_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/samlite/SamLiteBean.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
  samigo/samigo-app/src/webapp/jsf/samlite/samLiteValidation.jsp
  samigo/samlite-impl/src/java/org/sakaiproject/tool/assessment/samlite/impl/SamLiteServiceImpl.java
Labels: s2u-unidigital

#12179 SAK-49551 T&Q: Escape translation strings in the assessment list
  samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Labels: I18N

#12195 S2U-13 5.1.1.9 Tests & Quizzes: Improve selector for sub question pools when creating assessments
  samigo/samigo-app/src/webapp/js/select2.js
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
Labels: s2u-unidigital

#12204 SAK-49580 Not all global variables are exported on the xml - S2U-11 - MASTER
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
Labels: s2u-unidigital

#12205 SAK-49580 Not all global variables are exported on the xml - S2U-11
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
Labels: s2u-unidigital

#12198 S2U-18: Search questions by keywords in question pools - master
  library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/DataTableColumn.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/DataTableConfig.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/js/samigo-global.js
  samigo/samigo-app/src/webapp/js/samigotree.js
  samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
Labels: s2u-unidigital

#12199 SAK-49575 Sometimes some answers are interchanged when clicking Solution - S2U-10 - MASTER
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
Labels: s2u-unidigital

#12200 SAK-49575 Sometimes some answers are interchanged when clicking Solution - S2U-10
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
Labels: s2u-unidigital

#12208 S2U-7 Samigo add Assessment Report
  samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramQuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/AssessmentReport.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/AssessmentReportSection.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/SamigoBaseServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExcelExportUtil.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/PdfExportUtil.java
  samigo/samigo-app/src/webapp/WEB-INF/web.xml
  samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
Labels: s2u-unidigital

#12215 S2U-17 T&Q: Question pool statistics and tags
  assignment/tool/src/webapp/js/assignments.js
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
  library/src/morpheus-master/sass/modules/_b5-polyfill.scss
  msgcntr/messageforums-app/src/webapp/js/messages.js
  msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/msgHeader.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
  msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
  msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
  samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemTagIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/TagIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/shared/TypeIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/model/Tree.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/business/questionpool/QuestionPoolTreeImpl.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolDataBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolTagsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/ClearSelectedTagsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/FilterByTagsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/PoolSaveListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/QuestionPoolListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/SamigoBaseServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/cp/QuestionPoolStatisticsServlet.java
  samigo/samigo-app/src/webapp/WEB-INF/web.xml
  samigo/samigo-app/src/webapp/js/questionPoolStatistics.js
  samigo/samigo-app/src/webapp/js/questionpoolTagFilter.js
  samigo/samigo-app/src/webapp/jsf/questionpool/addPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/statisticsModal.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/tagFilter.jsp
  samigo/samigo-pack/src/webapp/WEB-INF/components.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/ItemStatistics.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/QuestionPoolStatistics.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/questionpool/QuestionPoolTag.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/StatisticsFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/StatisticsFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/PersistenceService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/StatisticsService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/StatisticsUtil.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/StatisticsServiceTest.java
  tags/tags-api/api/src/java/org/sakaiproject/tags/api/TagService.java
  tags/tags-impl/impl/src/java/org/sakaiproject/tags/impl/TagServiceImpl.java
  vuecomponents/tool/src/main/frontend/src/components-api/tag-selector-input-sync.js
  vuecomponents/tool/src/main/frontend/src/components/tag-selector.vue
Labels: s2u-unidigital

#12220 SAK-49596 Lessons: Default placeholder not updated in Spanish
  lessonbuilder/tool/src/webapp/templates/instructions/placeholder_es.html
Labels: low risk, L10N

#12222 S2U-49 Microsoft: OneDrive integration fix infinite loop
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/data/MicrosoftDriveItem.java
Labels: s2u-unidigital

#12231 S2U-35 Lessons: Fix nullpointer when creating text item after opening a subpage
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/LessonConditionUtil.java
Labels: s2u-unidigital
