Repository sakaiproject/sakai, pull requests merged in 2023-11, with the labels that each got.

#12051 S2U-23 5.1.1.19 Tests & Quizzes: Add the option to show the student - fix
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBase.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
Labels: s2u-unidigital

#12045 S2U-16: Samigo bugfixes related to timers
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPublishedSettingsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
  samigo/samigo-app/src/webapp/css/timerbar.css
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/js/questionProgress.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/timed.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/getTimerStrings.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/questionProgress.jspf
  samigo/samigo-app/src/webapp/jsf/delivery/tableOfContents.jsp
  samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/progress.scss
Labels: s2u-unidigital

#12030 S2U-5 more descriptive texts
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
Labels: s2u-unidigital

#12052 S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - Master
  library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiObjectService.java
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiSecurityService.java
  rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/model/RWikiObject.java
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages.properties
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages_ca.properties
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages_es.properties
  rwiki/rwiki-impl/impl/src/bundle/uk/ac/cam/caret/sakai/rwiki/component/bundle/Messages_eu.properties
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/IndexMacro.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
  rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/SiteEmailNotificationRWiki.java
  rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWiki.hbm.xml
  rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWikiObjectImpl.java
  rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages.properties
  rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages_ca.properties
  rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages_es.properties
  rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages_eu.properties
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/RequestScopeSuperBean.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/ReferencesBean.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/helper/ViewParamsHelperBean.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/CommentNewCommand.java
  rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/SaveCommand.java
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/commandComponents.xml
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
  rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/view.vm
Labels: Requires Conversion Script, s2u-unidigital

#12056 S2U-21 Tests & Quizzes: Add seb resource collection and set display name property
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
  webapi/src/main/java/org/sakaiproject/webapi/controllers/SecureDeliveryController.java
Labels: s2u-unidigital

#12065 S2U-46: FIX allow null values to prevent Oracle errors
  microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/model/MicrosoftConfigItem.java
Labels: s2u-unidigital

#12061 S2U-43 5.2.8.1 Admin: Ability to enrol, unenrol and disable multiple users in multiple sites - Master
  admin-bulk-user-membership/pom.xml
  admin-bulk-user-membership/tool/pom.xml
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/ThymeleafConfig.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/WebAppConfiguration.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/controller/MainController.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/exception/UsersByEmailException.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/bulk/membership/service/BulkUserMembershipToolService.java
  admin-bulk-user-membership/tool/src/main/java/org/sakaiproject/model/Summary.java
  admin-bulk-user-membership/tool/src/main/resources/Messages.properties
  admin-bulk-user-membership/tool/src/main/resources/Messages_ca.properties
  admin-bulk-user-membership/tool/src/main/resources/Messages_es.properties
  admin-bulk-user-membership/tool/src/main/resources/Messages_eu.properties
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/auto_membership_step_1.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/auto_membership_step_1_5.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/auto_membership_step_2.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/auto_membership_step_3.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/fragments/box_list.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/fragments/common.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/fragments/javascript.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/templates/fragments/wizard.html
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/tools/bulk.user.membership.xml
  admin-bulk-user-membership/tool/src/main/webapp/WEB-INF/web.xml
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_ca.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_es.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools_eu.properties
  kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql
  library/src/skins/default/src/sass/base/_icons.scss
  library/src/skins/default/src/sass/modules/tool/bulk-user-membership/_bulk-user-membership.scss
  library/src/skins/default/src/sass/tool.scss
  pom.xml
Labels: s2u-unidigital

#12067 S2U-21 Samigo: Fixes around linear access through SEB
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/assessment/SecureDeliveryServiceImpl.java
Labels: s2u-unidigital

#12068 SAK-49405 T&Q: NPE when trying to import an xml file to the Question Pool
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
Labels: s2u-unidigital

#12078 S2U-7 T&Q: Several fixes
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramQuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/SamigoBaseServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java
  samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp
Labels: s2u-unidigital

#12080 S2U-7 Fix typo in debug log message
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java
Labels: s2u-unidigital

#12087 SAK-49451 - Fix height and resize in External Tool left nav
  basiclti/web-ifp/src/bundle/vm/main.vm
  webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js
Labels: low risk

#12097 S2U-7 T&Q: Several fixes
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/PdfExportUtil.java
  samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp
Labels: s2u-unidigital

#11463 SAK-27765 Fix Unit Tests on Windows environments and other locales.
  entitybroker/rest/src/test/org/sakaiproject/entitybroker/rest/EntityDescriptionManagerTest.java
  entitybroker/rest/src/test/org/sakaiproject/entitybroker/rest/EntityHandlerImplTest.java
  kernel/component-manager/src/test/java/org/sakaiproject/modi/EnvironmentTest.java
  kernel/component-manager/src/test/java/org/sakaiproject/modi/SysPropTest.java
Labels: I18N, L10N
