Repository sakaiproject/sakai, pull requests merged in 2023-01, with the labels that each got.

#11145 SAK-48244 Update OpenSearch 1.3.7
  master/pom.xml
Labels: low risk

#11161 SAK-48270 LTI ignore incoming institutional roles on context launch
  basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
  basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiBLTIUtilTest.java
  basiclti/docs/LTIROLES.md
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
Labels: Requires Conversion Script

#11137 SAK-48238 Kernel support single instance store in ContentHosting
  kernel/api/src/main/java/org/sakaiproject/content/api/ContentResource.java
  kernel/api/src/main/java/org/sakaiproject/content/api/ContentResourceEdit.java
  kernel/api/src/main/java/org/sakaiproject/entity/api/ResourceProperties.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/AbstractContentResource.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlDefault.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_content.sql
  kernel/kernel-impl/src/main/sql/hsqldb/sakai_content_delete.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_content.sql
  kernel/kernel-impl/src/main/sql/mysql/sakai_content_delete.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_content.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_content_delete.sql
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/ContentHostingServiceTest.java
  kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/MockContentResource.java
  kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/StorageUtils.java
Labels: Requires Conversion Script

#11155 S2U-44 5.2.8.2 Portal display the user's role of the current site
  config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-impl/impl/src/bundle/sitenav_ca.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
  portal/portal-impl/impl/src/bundle/sitenav_eu.properties
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
Labels: s2u-unidigital

#11196 SAK-48327 Update Apache FreeMarker 2.3.32
  kernel/kernel-impl/pom.xml
Labels: low risk

#11193 S2U-10 5.1.1.6 Tests & Quizzes: Ability to preview calculated questions in question pools
  library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
Labels: s2u-unidigital

#11198 SAK-48329 Message is sent even after removing scheduling date
  msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Labels: cla?

#11209 SAK-48350 Profile: mail templates internationalization
  profile2/api/src/resources/templates/connectionConfirm.xml
  profile2/api/src/resources/templates/connectionRequest.xml
  profile2/api/src/resources/templates/wallPostMyWallNew.xml
Labels: I18N

#11207 S2U-31 5.1.4.2 Assignments: Grades in the main view of assignments
  assignment/api/src/resources/assignment.properties
  assignment/api/src/resources/assignment_ca.properties
  assignment/api/src/resources/assignment_es.properties
  assignment/api/src/resources/assignment_eu.properties
  assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Labels: s2u-unidigital

#11214 SAK-48368 Update MariaDB Connector/J 2.7.8
  master/pom.xml
Labels: low risk
