Repository sakaiproject/sakai, pull requests merged in 2024-05, with the labels that each got.

#12540 SAK-49346 LTI adjust input width on icon selector
  basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
Labels: cla?

#12594 SAK-49881 Wiki improve wiki search ui with dark background
  library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss
Labels: low risk

#12595 SAK-46866 Search improve results page in dark mode
  library/src/skins/default/src/sass/modules/tool/search/_search.scss
Labels: low risk

#12617 SAK-50075 Question Pool: calculated question solution cancel button console error
  samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
Labels: s2u-unidigital
