Repository sakaiproject/sakai, pull requests merged in 2024-01, with the labels that each got.

#12236 S2U-26 Gradebook for groups: fix csv export case
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Labels: s2u-unidigital

#12238 S2U-32 S2U-28 Spacing fixes
  assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
  assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
  msgcntr/messageforums-app/src/webapp/js/messages.js
Labels: s2u-unidigital

#12245 S2U-35 Add missing licence headers
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionOperator.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionType.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/BaseConditionEvaluator.java
Labels: s2u-unidigital

#12213 SAK-49591 T&Q: Show historical changes for questions in question pools
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemHistoricalIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/convert/AccessTypeConverter.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/convert/UsernameConverter.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
  samigo/samigo-app/src/webapp/jsf/questionpool/previewQuestion.jsp
  samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemHistorical.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
Labels: Requires Conversion Script

#12251 SAK-49619 Update Joda-time 2.12.6
  master/pom.xml
Labels: low risk

#12224 S2U-47 Meetings tool : fix search and improve i18n
  meetings/tool/src/main/resources/card.properties
  meetings/tool/src/main/resources/card_ca.properties
  meetings/tool/src/main/resources/card_es.properties
  meetings/tool/src/main/resources/card_eu.properties
  meetings/tool/src/main/resources/create-meeting_ca.properties
  meetings/tool/src/main/resources/main_ca.properties
  meetings/ui/src/main/frontend/src/components/sakai-meeting-card.vue
  meetings/ui/src/main/frontend/src/views/CreateMeeting.vue
  meetings/ui/src/main/frontend/src/views/Main.vue
Labels: s2u-unidigital

#12225 S2U-46 Microsoft admin: fix search teams
  microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/newSiteSynchronization.html
Labels: s2u-unidigital

#12255 S2U-35 Lessons: Fixes related to conditions
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssignmentConditionEvaluator.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
Labels: s2u-unidigital

#12219 SAK-49592 Avoid enter parenthesis from instructors while operating with global variables
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: s2u-unidigital

#12256 SAK-49592 Avoid enter parenthesis from instructors while operating with global variables - 22.x
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Labels: s2u-unidigital

#12259 S2U-18 SAK-49622 T&Q Fix question pool item sorting - s2u-22x
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
  samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
Labels: s2u-unidigital

#12262 SAK-49609 Library: templates.js console errors
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
Labels: low risk

#12263 Lessons: Default placeholder not updated in Spanish (22.x)
  lessonbuilder/tool/src/webapp/templates/instructions/placeholder_es.html
Labels: low risk

#12257 S2U-9 5.1.1.5 Tests & Quizzes: PDF export for assessment submissions (Fixes)
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java
Labels: s2u-unidigital

#12134 S2U-19 5.1.1.15 Tests & Quizzes: New option to use fixed questions and random questions from question pools on a part
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPublishedQuestionPoolPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/js/select2.js
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Labels: Requires Conversion Script, s2u-unidigital

#12276 S2U-21 SAK-49642 T&Q: Access denied on repeated attempts - MASTER
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/SebValidation.hbm.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
Labels: s2u-unidigital

#12277 S2U-21 SAK-49642 T&Q: Access denied on repeated attempts - s2u-22x
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/SebValidation.hbm.xml
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
Labels: s2u-unidigital

#12278 SAK-49643 LDAP: Very verbose logs when users are deleted or hidden fr…
  providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java
Labels: low risk

#12279 S2U-14 5.1.1.10 T&Q: Canceled questions and score re-calculation - MASTER
  library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
  samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/js/authoringQuestionCancellation.js
  samigo/samigo-app/src/webapp/js/deliveryQuestionCancellation.js
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
  samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/ItemCancellationTest.java
Labels: Requires Conversion Script, s2u-unidigital

#12296 S2U-46 Create Teams as PRIVATE
  microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
Labels: s2u-unidigital

#12221 S2U-20 Tests & Quizzes: random questions from multiple pools
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
  samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Labels: s2u-unidigital

#12282 S2U-21 SAK-49646 T&Q: Fix early timer start with SEB - s2u-22x
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SebSetupActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java
  samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueriesAPI.java
Labels: s2u-unidigital

#12283 S2U-21 SAK-49646 T&Q: Fix early timer start with SEB - MASTER
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SebSetupActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java
  samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueriesAPI.java
Labels: s2u-unidigital

#12295 S2U-21 SAK-49651 T&Q: Add config key input - s2u-22x
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
  samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Labels: s2u-unidigital

#12286 S2U-21 SAK-49651 T&Q: Add config key input - MASTER
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
  samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js
  samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
  samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Labels: s2u-unidigital

#12241 S2U-5 5.1.1.1 Tests & Quizzes: Dynamic Rubrics - MASTER
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
  library/src/skins/default/src/sass/themes/_base.scss
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
  msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsConstants.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java
  rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/RubricRepository.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
  rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/RubricRepositoryImpl.java
  rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
  samigo/samigo-app/src/java/org/sakaiproject/jsf/util/SamigoJsfTool.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
  samigo/samigo-app/src/webapp/js/samigo-global.js
  samigo/samigo-app/src/webapp/jsf/author/item/rubricAssociation.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
  vuecomponents/bundle/src/main/bundle/dynamic-criterion.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_ca.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_es.properties
  vuecomponents/bundle/src/main/bundle/dynamic-criterion_eu.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_ca.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_es.properties
  vuecomponents/bundle/src/main/bundle/dynamic-rubric_eu.properties
  vuecomponents/tool/src/main/frontend/package-lock.json
  vuecomponents/tool/src/main/frontend/package.json
  vuecomponents/tool/src/main/frontend/src/api/dynamic-rubrics-api.js
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/buttons.scss
  vuecomponents/tool/src/main/frontend/src/components/dynamic-criterion.vue
  vuecomponents/tool/src/main/frontend/src/components/dynamic-rubric.vue
  vuecomponents/tool/src/main/frontend/src/utils/dynamic-rubrics-utils.js
  webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricAssociation.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionStudent.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudent.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentPreviewButton.js
Labels: s2u-unidigital

#12299 S2U-17 Add dialog label for modal
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/TagIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolTagsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/ClearSelectedTagsListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/FilterByTagsListener.java
  samigo/samigo-app/src/webapp/jsf/questionpool/statisticsModal.jsp
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/questionpool/QuestionPoolTag.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/StatisticsService.java
Labels: accessibility, s2u-unidigital

#12243 S2U-35 Lessons: View items based on grade - MASTER
  conditions/api/pom.xml
  conditions/api/src/java/org/sakaiproject/condition/api/ConditionEvaluator.java
  conditions/api/src/java/org/sakaiproject/condition/api/ConditionService.java
  conditions/api/src/java/org/sakaiproject/condition/api/exception/UnsupportedToolIdException.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/Condition.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionOperator.java
  conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionType.java
  conditions/api/src/java/org/sakaiproject/condition/api/persistence/ConditionRepository.java
  conditions/impl/pom.xml
  conditions/impl/src/java/org/sakaiproject/condition/impl/ConditionServiceImpl.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssessmentConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssignmentConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/BaseConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/LessonsConditionEvaluator.java
  conditions/impl/src/java/org/sakaiproject/condition/impl/persistence/ConditionRepositoryImpl.java
  conditions/impl/src/webapp/WEB-INF/components.xml
  conditions/pom.xml
  kernel/api/src/main/java/org/sakaiproject/authz/api/SecurityAdvisor.java
  kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
  kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
  lessonbuilder/tool/pom.xml
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/EditPageProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/FolderPickerProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
  lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/LessonConditionUtil.java
  lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
  lessonbuilder/tool/src/webapp/js/folder-picker.js
  lessonbuilder/tool/src/webapp/js/show-page.js
  lessonbuilder/tool/src/webapp/templates/EditPage.html
  lessonbuilder/tool/src/webapp/templates/FolderPicker.html
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
  master/pom.xml
  pom.xml
  vuecomponents/bundle/src/main/bundle/condition.properties
  vuecomponents/bundle/src/main/bundle/condition_ca.properties
  vuecomponents/bundle/src/main/bundle/condition_es.properties
  vuecomponents/bundle/src/main/bundle/condition_eu.properties
  vuecomponents/docs/i18n.md
  vuecomponents/tool/pom.xml
  vuecomponents/tool/src/main/frontend/.gitignore
  vuecomponents/tool/src/main/frontend/build-dev.mjs
  vuecomponents/tool/src/main/frontend/src/api/conditions-api.js
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/alert.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/badges.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/buttons.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/card.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/form.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/list-group.scss
  vuecomponents/tool/src/main/frontend/src/bootstrap-styles/misc.scss
  vuecomponents/tool/src/main/frontend/src/components/condition-editor.vue
  vuecomponents/tool/src/main/frontend/src/components/condition-picker.vue
  vuecomponents/tool/src/main/frontend/src/components/condition-text.vue
  vuecomponents/tool/src/main/frontend/src/mixins/i18n-mixin.js
  vuecomponents/tool/src/main/frontend/src/utils/condition-utils.js
  vuecomponents/tool/src/main/frontend/src/utils/core-utils.js
  webapi/pom.xml
  webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java
Labels: s2u-unidigital

#12288 S2U-6 5.1.1.2 Tests & Quizzes: Show number of correct, incorrect and …
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
Labels: s2u-unidigital

#12302 S2U-26: Add GB to import on pre-existing sites
  site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Labels: s2u-unidigital

#12306 S2U-26 Update GradebookNgBusinessService - remove comment
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Labels: s2u-unidigital

#12305 S2U-16 Add missing EU translations
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
Labels: low risk, s2u-unidigital

#12280 S2U-19 5.1.1.15 Tests & Quizzes: New option to use fixed questions and random questions from question pools on a part - MASTER
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPublishedQuestionPoolPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/js/select2.js
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
  samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
  samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueriesAPI.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Labels: Requires Conversion Script, s2u-unidigital

#12303 S2U-9 5.1.1.5 Tests & Quizzes: PDF export for assessment submissions - MASTER
  samigo/samigo-app/pom.xml
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Labels: s2u-unidigital

#12312 S2U-6 SAK-49674 T&Q: Summary performance fix
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
Labels: s2u-unidigital

#12319 S2U-26 SettingsGradingSchemaPanel remove comment
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
Labels: s2u-unidigital

#12321 S2U-21 SAK-49651 Fix endless loading on race condition - s2u-22x
  samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js
Labels: s2u-unidigital

#12320 S2U-21 SAK-49651 Fix endless loading on race condition - MASTER
  samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js
Labels: s2u-unidigital

#12308 S2U-20 Add i18n for multiselect
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
Labels: s2u-unidigital

#12307 S2U-20 Tests & Quizzes: random questions from multiple pools - MASTER
  samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
  samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
  samigo/samigo-app/src/webapp/css/tool_sam.css
  samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
  samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
  samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentData.java
  samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
  samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Labels: s2u-unidigital

#12331 SAK-49664 Webcomponents: Add missing utility function to 22.x
  webcomponents/tool/src/main/frontend/js/sakai-portal-utils.js
Labels: BLOCKER
