Repository sakaiproject/sakai, pull requests merged in 2025-03, with the labels that each got.

#13379 SAK-51084 CALENDAR: Some errors on CalendarImpl Tests (Spanish)
  calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/CSVReaderTest.java
Labels: BLOCKER

#13381 SAK-51083 SITESTATS: 'Information about last update' text is hardcoded
  sitestats/sitestats-bundle/src/resources/Messages.properties
  sitestats/sitestats-bundle/src/resources/Messages_es.properties
  sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/LastJobRun.java
  sitestats/sitestats-tool/src/webapp/html/components/LastJobRun.html
Labels: I18N

#13378 SAK-51082 Wiki: Last modified by and Date info is missing on Spanish
  rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages_es.properties
Labels: low risk, I18N

#13401 SAK-51102 Library fix headscripts eval
  library/src/webapp/js/headscripts.js
Labels: BLOCKER

#13409 SAK-51107 Polls cc+ import log messages should be debug not info
  polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
Labels: low risk

#13299 SAK-50987 webcomponents Refactor rubrics tests into one per component
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/RubricsElement.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricAssociation.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricReadonly.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudent.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentPreviewButton.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/data.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/i18n.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-association.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-criteria.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-criterion-edit.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-criterion-preview.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-edit.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-grading.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-manager.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-pdf.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-readonly.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-student-preview-button.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-student.test.js
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubrics.test.js
Labels: low risk

#13425 SAK-50827 T&Q cc+ Feedback "Show the correct answer" not present
  samigo/samigo-api/src/java/xml/author/v1p2/assessmentTemplate.xml
  samigo/samigo-api/src/java/xml/author/v2p0/assessmentTemplate.xml
  samigo/samigo-app/src/test/data/realizedAssessment.xml
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
  samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/assessment/AssessmentHelperBase.java
Labels: low risk

#13468 SAK-51164 Portal: Enter Student View - serious aXe issue
  portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
Labels: low risk

#13480 NOJIRA Checking licenses
  webapi/src/main/java/org/sakaiproject/webapi/beans/GradebookItemRestBean.java
  webapi/src/main/java/org/sakaiproject/webapi/beans/GradebookRestBean.java
Labels: low risk

#13503 SAK-51206 CC+Archive Fails with Error Log Message (regression)
  common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteMerger.java
Labels: BLOCKER
