Repository sakaiproject/sakai, pull requests merged in 2025-04, with the labels that each got.

#13527 SAK-51229 Gradebook - Error when Set Score for Empty Cells
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradeTableData.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Labels: BLOCKER

#13535 SAK-51267 Gradebook oracle requires a sequence for database generated IDs
  gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/AbstractGradeRecord.java
  gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradingEvent.java
Labels: BLOCKER

#13526 SAK-51249 Gradebook oracle doesn't allow inserting empty values GB_GRADING_EVENT_T.IS_EXCLUDED
  gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradingEvent.java
Labels: BLOCKER

#13540 SAK-51283 Gradebook - ORACLE - ORA-00001: restriccion unica (SAKAI_UPGRADE.SYS_C00813796) violada
  gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Comment.java
Labels: BLOCKER

#13542 SAK-51285 Gradebook - ORACLE Error when trying to exclude a grade
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java
  gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Labels: BLOCKER

#13543 SAK-51291 Gradebook - Error when on Course Grade try to Set Zero Scor…
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/SetZeroScoreAction.java
Labels: BLOCKER

#13556 SAK-51313 Update Joda-time 2.14.0
  master/pom.xml
Labels: low risk

#13610 SAK-51377 Gradebook: Globe icon is missing when sending gradebook item from external tool
  gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Labels: low risk

#13611 SAK-51329 Rubric Preview text is hardcoded
  webcomponents/tool/src/main/frontend/packages/sakai-rubrics/sakai-rubrics-utils.js
Labels: low risk, I18N

#13613 SAK-51150 Roster: hide portal components in pdf
  roster2/tool/src/webapp/css/print.css
Labels: low risk

#13614 SAK-51288 Roster: The tooltip is not visible when hovering the mouse over the photos.
  roster2/tool/src/handlebars/members_cards.handlebars
  roster2/tool/src/handlebars/members_photogrid.handlebars
  roster2/tool/src/handlebars/members_table.handlebars
Labels: low risk
