Repository sakaiproject/sakai, pull requests merged in 2025-01, with the labels that each got.

#13154 SAK-50821 Update Apache Commons Codec 1.17.2
  master/pom.xml
Labels: low risk

#13163 SAK-50832 ORACLE: NOW is not accepted
  kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
Labels: BLOCKER

#13161 SAK-50830 Update Apache Commons BeanUtils 1.10.0
  master/pom.xml
Labels: low risk

#13186 SAK-50860 ORACLE: Error GROUP BY. Not possible to create sites, also error when clicking on Manage Tools
  lti/lti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java
Labels: BLOCKER

#13190 SAK-50866 i18n resources email text when uploading
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon_ca.properties
  config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon_es.properties
Labels: L10N

#13202 SAK-50878 Adding overflow hidden for the large sites on the menu
  library/src/skins/default/src/sass/modules/more-sites/_more-sites.scss
Labels: low risk

#13203 SAK-50879 Assignment: Restore profile photo in Assignments by Student
  assignment/tool/src/webapp/js/assignmentsByStudent.js
Labels: low risk

#13212 SAK-50820 Assignments / LTI Hide sakai_tool_checksum from UI
  lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java
Labels: low risk

#13227 SAK-50901 Samigo - Icons are missing on Solution on Calculated Question on Question pools
  samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
Labels: low risk

#13228 SAK-50902 Samigo - Bad style on question box on Solution on Calculated Question on Question pools
  samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
Labels: low risk

#13247 SAK-50928 Lesson Add translations for custom file name upload and link title
  lessonbuilder/api/src/resources/lessons.properties
  lessonbuilder/tool/src/webapp/js/show-page.js
  lessonbuilder/tool/src/webapp/templates/ShowPage.html
Labels: I18N

#13258 SAK-50931 Assignment: Change text-info class (blue color)
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
  assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Labels: low risk

#13256 SAK-50080 Portal display a user's current role in site
  portal/portal-impl/impl/src/bundle/sitenav.properties
  portal/portal-impl/impl/src/bundle/sitenav_es.properties
Labels: low risk
