Repository sakaiproject/sakai, pull requests merged in 2025-02, with the labels that each got.

#13269 SAK-50935 LTI Dynamic Reg support custom_parameters
  lti/lti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
  lti/lti-tool/src/webapp/vm/lti_tool_edit.vm
Labels: low risk

#13277 SAK-50103 LTI add i18n translation for 'Launch' text
  lti/lti-portlet/src/bundle/basiclti.properties
  lti/lti-portlet/src/bundle/basiclti_es.properties
  lti/lti-portlet/src/java/org/sakaiproject/portlets/IMSLTIPortlet.java
Labels: I18N

#13297 SAK-50976 cc+ import of group submission assignment: server log error on edit
  assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm
Labels: low risk

#13298 SAK-50800 Discussions CC+ Support the notifications checkboxes
  msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Labels: low risk

#13324 SAK-51032 LTI Change terminiology in the UI
  lti/lti-impl/src/bundle/ltiservice.properties
Labels: low risk

#13322 SAK-51007 Kernel saving a pronunciation in profile causes SQL syntax error ORA-00933
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSql.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlDefault.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java
  kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
Labels: BLOCKER

#13328 SAK-51035 Portal incorrect menu on gateway when setting property gatewaySiteList
  portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
Labels: BLOCKER

#13341 SAK-51047 CC+Archive Include server name in export content
  common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
Labels: low risk

#13345 SAK-51020 Roster - Export funcionality is broken
  roster2/bundle/src/bundle/roster_es.properties
Labels: low risk

#13348 SAK-50980 CKEditor: Embedded image links in polls need to be updated with cc+ import
  polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
Labels: low risk

#13353 SAK-51052 Windows - Tsugi test error
  lti/tsugi-util/src/java/org/tsugi/time/InstantUtil.java
  lti/tsugi-util/src/test/org/tsugi/time/InstantUtilTest.java
Labels: BLOCKER
